### ISSUE TITLE
compile without nightly compiler

### ISSUE THREAD

**Issue by warlord500** [alexcrichton/futures-rs#103]
the current futures code doesnt compile with stable due to use of the scoped_tls.
I tried to use the code with just future-rs and futures-cpupool.

**Comment by pmarino90** [comment]
@warlord500 I've been able to compile with 1.11.0 without any issue.

**Comment by alexcrichton** [comment]
@warlord500 what compiler version are you using? Currently this library requires 1.10.0+

**Comment by alexcrichton** [comment]
Closing as this may have just been an off-by-one issue, but if it still shows up let me know!

**Comment by yzarubin** [comment]
The hello-world example didn't work for me using rustc 1.10.0, it failed to compile security-framework v0.1.10. Got it to work working after updating to 1.14.0.
