### ISSUE TITLE
Atomically draining & dropping a consumer of Channel / Oneshot

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/futures-rs#104]
`Channel` and `Oneshot` are multithreaded "message passing" constructs. Both include some level of internal storage for in-flight messages.

There would be utility in providing a way for the receiving end to atomically drain & drop (shutdown) their handles. This would provide a way to guarantee that values don't get "lost" in the internal storage.

I implemented this initially as a `try_release` fn, but this may or may not be the best way to expose the functionality:

https://github.com/tokio-rs/tokio/blob/master/src/util/future/channel.rs#L126

**Comment by alexcrichton** [comment]
I don't think these'd be too difficult to implement, but @carllerche do you have a use case in mind as well? It might be good to have one just to help designing the APIs to work with it.

**Comment by carllerche** [comment]
Off the top of my head, a `Task` is managing a Tcp connection for a client. The client handle sends requests to the connection task using a channel. The connection errors. It would be nice for the channel that sends requests to be closed cleanly. Aka, the consuming end can drop knowing that it received all pending requests and completed them w/ an error and that the client handle will not be able to send any further requests to the dead connection.

Hope this makes sense.

**Comment by jwilm** [comment]
I've run into the exact problem @carllerche describes with mpsc::channel. Atomic close and drain from the receiver side would be nice to have here.

**Comment by alexcrichton** [comment]
Ok I think that makes sense yeah. I think this is going to need coordination/APIs on both ends. That is, the producer half will need a `Result` of some form to hand back the message or at least indicate that delivery failed. The production half probably just needs a `try_release` method of some form then that attempts to shut down the channel but fails if there's items in flight.

I think for `stream::channel` we have a vector to return the item with a result, but for `oneshot` we do not. This can likely be solved by just returning a result from `complete`, akin to `SendError` in mpsc

**Comment by alexcrichton** [comment]
added to `channel` in https://github.com/alexcrichton/futures-rs/pull/245
