### ISSUE TITLE
Consider lifting `Result` from `Poll`

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/futures-rs#108]
Currently, `Poll` is an enum of `Ok`, `Err`, and `NotReady`. This disallows being able to use `try!` with a `Poll` value.

Consider switching from `Poll<T, E>` to `Result<Async<T>, E>` where:

```rust
pub enum Async<T> {
  Ready(T),
  NotReady,
}
```

This would allow using `try!` with poll results, such as:

```rust
if let Async::Ready(value) = try!(my_future.poll()) {
  // do something with the value
}
```

Another option would be to use `Option` instead of `Async`. The pro of using `Option` would be one less type to import. The con is that `Option` is less descriptive than `Async`.

**Comment by ksf** [comment]
This will probably be solved nicely by the [carrier trait to come along with `?`](https://github.com/rust-lang/rfcs/issues/1718).

In the meantime I don't think having to use `try!(try_poll!( x )` is much of an issue, especially considering that only combinators and primitive streams/futures should ever call poll, so the wart is pretty localised as well as (in principle) forwards-compatible.

(Also, this ties in with the `Poll::Yield` thing which we might want to have (and I do))

**Comment by sinkuu** [comment]
Even with `Carrier`, doesn't `Poll` need to be `Result`-like anyway?

```rust
enum Async<T> {
    Ready(T),
    NotReady,
    // Yield?
}

impl<T, E> Carrier for Poll<T, E> {
    type Success = Async<T>;
    type Error = E;

    ...
}
```

Just using `Result` is simpler and allows using `try!` from now.

```rust
pub type Poll<T, E> = Result<Async<T>, E>;
```

**Comment by ksf** [comment]
I think `NotReady` should count as `Error` in this context: It kind of *is* an error, a very transient one. In particular, `?` should pass it through unchanged, and if the success branch of `?` is taken we should have a bare, plain, `T` at our hands.  That is:

    impl<T, E> Carrier for Poll<T, E> {
        type Success = T;
        ...
    }

As for `Poll`'s `Carrier::Error`: It can't be Poll so I guess yes we need a split. `Poll<T,E> = Result<T, Async<E>>` would work, where:

    enum Async<E> {
        NotReady,
        // Yield,
        Other<E>
    }

which looks just like any other random custom error type.

**Comment by josephDunne** [comment]
👍 for `Async` over `Option`

**Comment by alexcrichton** [comment]
To test out the ergonomics of this, I've got a [WIP branch](https://github.com/alexcrichton/futures-rs/tree/new-poll) implementing this change.

So far my thoughts are:

* For the `futures` crate itself it seems like this is a bit of a loss in ergonomics, I felt like there was a lot of typing.
* It was *super* nice to use `try!`
* I've also modified `try_poll!` to propagate both errors and "not ready", this feels more correct than the previous semantics of only propagating "not ready"

Next step is to propagate this to the tokio I/O crates, where we expect some real benefit.

**Comment by partim** [comment]
A thought taking the issue a little further:

There are already quite a few cases of futures and streams that don’t return errors.

If `Poll<T, E>` becomes an `Async<Result<T, E>>`, perhaps `Future` could loose its `Error` associated type, instead making the `Item` a `Result<T, E>` if errors can happen.

The prize would be the loss of `Future::and_then()` and `Future::or_else()` but maybe that could be fixed via an extension trait implemented for all `Future<Item=Result<T, E>>`?

**Comment by ksf** [comment]
@partim 

`Iterator` does it like that and suffers from a lot of boilerplate when dealing with errors: All those conversions between Iterators that work on `T` vs. `Result<T,E>`, not to mention having to get things right in cases of `Some(Err(EndOfFile))` vs. `None`. A success of the base type (that is, `Poll`) should indeed yield an element, or things quickly become ugly: It should be trivial to just pass errors downstream.

I guess it's also safe to assume that carrying errors will be the case for most streams anywhere as they're bound to do some IO, which can fail for an infinite number of reasons. If you want error-free streams -- e.g. using them in a pure setting as `Iterator`-replacement -- you can always use `()` as Error type, and incur no additional boilerplate.

**Comment by alexcrichton** [comment]
Ok, after implementing the change across various repos, my conclusions from before haven't really changed *that* much. I think overall I/O got nicer to write (as `try!` works) and future combinators got both worse and better. The ability to work with `try!`, however, seems too nice to pass up, so I think we're going to move forward with this change. Specifically:

```rust
type Poll<T, E> = Result<Async<T>, E>;
enum Async<T> {
    Ready(T),
    NotReady,
}

macro_rules! try_ready {
    ($e:expr) => (match $e {
        Ok($crate::Async::Ready(t)) => t,
        Ok($crate::Async::NotReady) => return Ok($crate::Async::NotReady),
        Err(e) => return Err(From::from(e)),
    })
}
```

That is, use the above types, remove `try_poll!`, and add `try_ready!` which propagates both not ready and the error.

**Comment by alexcrichton** [comment]
Ah yes, and @partim we've discussed that in the past (not having an error type baked in). Unfortunately though almost all uses of futures right now are related to I/O, and we can bake in some nice combinators *and* semantics if it all has an error associated type. That is, not only do we get `and_then` and `or_else`, but `join` can return early on errors by default.
