### ISSUE TITLE
only epoll blocking?

### ISSUE THREAD

**Issue by MarkusJais** [alexcrichton/futures-rs#11]
Question for the comment in locks.rs 

" As a futures library the eventual call to `epoll` should be the only thing
 that ever blocks"

Does that mean that only epoll will be supported for network calls (at least on Linux)?

A Future could hold a blocking network call or any other longer-running computation.

e.g.

let str: Future<String> = count_words_in_rust_doc();

Maybe I do not understand the comment correctly. I assume that futures are meant to be generic.

I like this project a lot and I also like that that Rust community is not rushing this. It took Java many years and JDK 8 to finally get usable futures (CompletableFuture).
Similar for Python and C+++. 
And Scala is still improving it's futures:
https://github.com/viktorklang/blog/blob/master/Futures-in-Scala-2.12-part-1.md

So it is good to design this carefully, maybe together with non-blocking IO. It will be crucial for Rust and very important for anyone working on stuff like databases, web servers, big data analytics and many other distributed systems.

**Comment by alexcrichton** [comment]
Ah yeah this was just a bit of a cast away comment, we definitely want to work with more than just `epoll`! The futures library itself is intended to not link to any particular event loop, but instead most futures-related code will be agnostic to the underlying event loop.

Right now `mio` directory contains bindings to the `mio` library which uses epoll on Linux, kqueue on OSX, and IOCP on Windows. So in that sense this should work with just about anything!

You also bring up some very good points in taking time to get this all right, and they're definitely all well received! We're hoping to have more vectors for contribution soon on this library, we just wanted to build a solid foundation to grow on top of first. 

This should be mostly ready for experimentation though! The I/O layers are still a bit in flux, but the futures part itself is pretty stable.

**Comment by alexcrichton** [comment]
If you've got anything you're particularly interested in just let me know though! May be able to help get you up to speed if you'd like.

**Comment by MarkusJais** [comment]
Thanks for the comments. I'll have a deeper look at the code next week and get back to you. Keep up the great work.
