### ISSUE TITLE
Ooops futures-mio documentation is unavailable 

### ISSUE THREAD

**Issue by Kerosene2000** [alexcrichton/futures-rs#115]
http://alexcrichton.com/futures-rs/futures_mio/

**Comment by alexcrichton** [comment]
Oh this has since moved to https://github.com/tokio-rs/tokio-core, perhaps there's still a dead link lying around though?

**Comment by Kerosene2000** [comment]
Haha yup on google 😞 
The 7th link:
https://www.google.fr/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=futures-rs+timeout

**Comment by alexcrichton** [comment]
Ah ok, hopefully those'll get purged soon!
