### ISSUE TITLE
Send + 'static trait requirements?

### ISSUE THREAD

**Issue by tomaka** [alexcrichton/futures-rs#12]
Are these trait really required on [`Future`](https://github.com/alexcrichton/futures-rs/blob/e1474b0570c6ef497dd0c5bd30be4a326a352bb8/src/lib.rs#L111) and [`Stream`](https://github.com/alexcrichton/futures-rs/blob/e1474b0570c6ef497dd0c5bd30be4a326a352bb8/src/stream/mod.rs#L91)?
I don't really see how Futures or Streams in general absolutely need to be Send or 'static.

If mio requires them, they should probably be enforced in the code of the `futures-mio` crate and not in `futures` itself.

**Comment by alexcrichton** [comment]
Thanks for the issue! I've added an FAQ to the main repository as I suspect there'll be quite a few questions along these lines! And this is now the [first answered question](https://github.com/alexcrichton/futures-rs/blob/master/FAQ.md#why-send--static).

If you have more thoughts on that, though, please feel free to ask here!

**Comment by tomaka** [comment]
I'm not so concerned about `Send`, but more about `'static`. The fact that futures are static means that it is almost mandatory to use `Arc`s everywhere.

**Comment by alexcrichton** [comment]
Ah interesting! We've discussed a few times how we might get rid of `'static`, but unfortunately it always seems to end up akin to "add a lifetime parameter everywhere", which to us seems like it's not worth the ergonomic cost.

Another way to think about it is that if you were writing an event loop by hand, all lifetimes of borrowed objects which persist across event loop iterations have to live longer than the event loop itself, and that's the lifetime that would get threaded everywhere.

In general though the cost of an allocation for `'static` data shouldn't be too bad as it's only required once per task, not once per future or once per `poll` or anything like that.
