### ISSUE TITLE
Consider type parameters instead of associated items

### ISSUE THREAD

**Issue by alexcrichton** [alexcrichton/futures-rs#120]
For example, this definition of `Future` instead:

```rust
trait Future<T, E> {
    // ...
}
```

The pros of this approach are:

* `Future<T, E>` is more ergonomic than `Future<Item=T, Error=E>`

The cons of this approach are:

* More type parameters when working generically

We expect the vast majority of future consumers to *not* be working generically but rather with `Future` directly with concrete types, and we also expect trait objects and/or `impl Trait` to be very common. We should test and see if type parameters are too onerous or not.

**Comment by alexcrichton** [comment]
Aha, another downside is that we can't have `IntoFuture` if we do this:

```
error[E0119]: conflicting implementations of trait `IntoFuture<_, _>` for type `core::result::Result<_, _>`:
   --> src/lib.rs:823:1
    |
815 | impl<T, E, F: Future<T, E>> IntoFuture<T, E> for F {
    | - first implementation here
...
823 | impl<T, E> IntoFuture<T, E> for Result<T, E> {
    | ^ conflicting implementation for `core::result::Result<_, _>`

error: aborting due to previous error
```

That... may be a dealbreaker

**Comment by ksf** [comment]
This works (with `feature(spezialisation)`):
    
    trait IntoFuture<T,E> 
    
    impl<T,E,F> IntoFuture<T,E> for F {}

    impl<T,E> IntoFuture<T,E> for Result<T,E> {}

That the additional trait bound makes this not work might be a bug in the implementation: A concrete type surely looks like it should always be more specific than a variable, trait-bound or not.

----

Then there's the possibility of

    trait Fut<T,E> : Future<Item=T,Error=E> {}
    impl<T,E, F: Future<Item=T,Error=E>> Fut<T,E> for F {}

(just for referencing things, but in implementations the associated type syntax shouldn't be a bother, anyway)

and, lastly, it could also be `Fut<T,Error=E>`.

---

In case of the latter approach (which really is a no-op library-wise, users can just do it themselves) it is actually necessary that the library uses associated types as if you do it the other way around  you get under-constrained variables in the alias impl. It's not, after all, all just syntactic sugar.

**Comment by sinkuu** [comment]
> That the additional trait bound makes this not work might be a bug in the implementation: A concrete type surely looks like it should always be more specific than a variable, trait-bound or not.

IIUC, `F : Future<T, E>` is not a super set of `Result<T, E>` (we can't say `Result<T, E>: Future<T, E>`) so you can't use specialization with that trait bound.
Then it runs into a coherence error: https://github.com/rust-lang/rust/issues/28881 (exactly equivalent - `Base` = `Future`, `Foo` = `IntoFuture`, `Bar` = `Result`). Compiler doesn't consider `std` is an upstream crate here.

**Comment by aturon** [comment]
@ksf We tried the latter approach but hit compiler bugs, sadly.

**Comment by alexcrichton** [comment]
Yes thanks for the response @ksf!

After some discussion though, the current limitations seem to essentially force our hand on this issue. Ergonomics basically require `IntoFuture` to exist, and this library also requires to compile on stable (no specialization), and otherwise compiler bugs have prevented us from exploring alternatives.

As a result, I'm going to close this.
