### ISSUE TITLE
Tutorial + docs needs to be updated for removal of .forget()

### ISSUE THREAD

**Issue by Ameobea** [alexcrichton/futures-rs#123]
At the moment, there is no clear reference (that I could find) to explain how to go about implementing the functionality of .forget().  In addition, the Tutorial still has references to .forget() in it although they have been removed from the documentation.

EDIT: I read in other issues that Executors seem to be the new accepted way of consuming a future in the background.  However, their documentation is rather sparse and there are no examples showing how to go about utilizing that functionality.

**Comment by alexcrichton** [comment]
Indeed! At this point unfortunately the tutorial basically needs to be rewritten probably from scratch :(

**Comment by alexcrichton** [comment]
Ok, updated!

**Comment by Ameobea** [comment]
Woohoo!! :D
