### ISSUE TITLE
Consider having `Oneshot` be generic over `Error`

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/futures-rs#125]
Currently, `Oneshot` has a fixed Error of `Canceled`, this means that it takes a few steps to send an error via the `Oneshot`.

I propose making `Oneshot` generic over error, so it would become `Oneshot<T, E>` and add a `fail` fn to `Complete` allowing it to send the error.

In the event that `Complete` drops without sending a value, I think that a panic on the `Oneshot` end is valid behavior. Dropping a `Complete` w/o sending a value is a bug, which means that there isn't really any correct way to handle it except for killing the task

**Comment by dwrensha** [comment]
> Dropping a `Complete` w/o sending a value is a bug

I disagree. Cancellation can be a common occurrence. To cancel a `Future`, you drop it, causing all of the resources it owns to be dropped. Some of those resources might very well be `Complete`s.

For example, consider the following function, which allows a separate task to be notified on completion of a future:


```rust
fn when_done<T, E, F>(f: F) -> (Box<Future<Item=T, Error=E>>, Oneshot<()>)
    where F: Future<Item=T, Error=E> + 'static
{
    let (complete, oneshot) = futures::oneshot();
    let f1 = f.map(move |t| {
        complete.complete(());
        t
    });

    (Box::new(f1), oneshot)
}
```

It might be useful to do `let (f1, done) = when_done(f);` and then to wait for `done` in a separate task from `f1`. If `f1` gets dropped, that other task ought to be able to recover.

**Comment by alexcrichton** [comment]
I also feel that we should propagate cancellation as a panic. Similar to channels in the standard library we'd do that via a result instead. To propagate a panic, though, it should be an easy:

```rust
rx.then(|r| r.unwrap())
```

That is, if the type of a `Oneshot` is actually `Result<T, E>`, then the `then` closure receives `Result<Result<T, E>, Canceled>` which can then be trivially unwrapped to assert that cancellation didn't happen.

**Comment by alexcrichton** [comment]
Er, I feel that we should *not* propagate as a panic.

**Comment by carllerche** [comment]
Yeah, the main issue is that mapping the error makes it more difficult to reference the future as a type w/o boxing (since it will take a closure that cannot be named). So, if you want to send an error type, you will mostly be forced to make a custom receiver type each time :)

Either way, it's not a huge problem, I don't disagree w/ @dwrensha's point, but I also think that wanting to send an error will be fairly common, so perhaps there can be an easier way to map the error out of the box?

**Comment by aturon** [comment]
OK, I've digested this an basically agree with @alexcrichton's stance. In particular, there are two kinds of "errors" that are likely to arise with oneshots: cancellation, and some kind of custom error you want to transmit. Having cancellation as the *outer* `Result` is probably the right thing to do, because you're likely to dispatch on that first (or use `unwrap` to immediately panic), then digging out the internal result.

We could consider supplying a type alias that injects a custom error type, or other conveniences here, but I think the current base setup is the right one.
