### ISSUE TITLE
Consider Task fairness

### ISSUE THREAD

**Issue by drewhk** [alexcrichton/futures-rs#128]
The consumption loop here has no upper bound: https://github.com/alexcrichton/futures-rs/blob/master/src/task/mod.rs#L283

I only took a shallow look at the code so far, so correct me if I am mistaken but this means that a Task always runs/polls until nonreadiness without suspending earlier which can lead to unfairness. This might be an issue on a pool with limited threads where some Tasks are busier than others and can poll-spin for longer times taking a worker thread for a long time without returning it for others to use.

**Comment by alexcrichton** [comment]
Thanks for the report! This is definitely something to keep in mind, and we want to make sure that there aren't any unnecessarily unbounded loops in the core library at least.

That loop in particular is required because the purpose of the method is to block the current thread to wait for a result, however, so it's perhaps not related to this? I believe we don't have many of these loops in this library, but do you perhaps have another in mind?

**Comment by drewhk** [comment]
> That loop in particular is required because the purpose of the method is to block the current thread to wait for a result, however, so it's perhaps not related to this?

Yep, that loop is unrelated. I am not even sure why I linked to that... I think I meant this: https://github.com/alexcrichton/futures-rs/blob/master/src/task/mod.rs#L365 but now I am not sure :D

I was just hunting for the place where Tasks are executed and see how it works and if it can pull/poll multiple elements in one go. Do you reschedule after every poll, successful or not, or do you only reschedule once the poll is not successful (or an upper bound is met)?

**Comment by alexcrichton** [comment]
Ah yes indeed that is one case of perhaps an unbounded loop! That is, however, only *one* method of executing tasks, and one that almost no tasks take by default (unless you're using `CpuPool`).

I think though we could finagle that not being a loop and just performing a yield.

**Comment by drewhk** [comment]
Ok, I thought that since it is defined on Task it is something that all "schedulers" call. So I need to look at `CpuPool`, too :) I think this is safe to close now.
