### ISSUE TITLE
Check if task is parked before parking thread.

### ISSUE THREAD

**Issue by Stebalien** [alexcrichton/futures-rs#132]
So, I'm worried about a race condition in future's like `Join` when one of the sub-futures calls `thread::park()` internally. Basically, what if we have the following sequence of events:

1. Someone calls `spawn(future).wait_future()` where `future` is a `Join` of two sub-futures.
2. Sub-future 1 parks the task and schedules it to be unparked.
3. Sub-future 1 returns `NotReady`.
4. An event happens and the task is unparked. This will call `thread::unpark` on the current thread.
5. Future 2 communicates with another thread and, in the process, some internal method calls `Thread::park`. This isn't really the "correct" way to communicate in an async environment but I can see some library doing this if it knows that it's thread will be unparked *really* quickly.
6. The `Join` returns `NotReady`.
7. `Spawn`'s `wait_future` method calls `thread::park` and waits indefinitely because step 4 cleared the park flag.

A fix for this is to set a `task_is_parked` flag, set/unset it from within `task::park()`/`Task::unpark()` and check this before calling `thread::park()`. This is still racy but the race is safe: If `task_is_parked` is unset *after* we check it but before we call `thread::park()`, we *know* that no user-specified code could have called `thread::park()` and swallowed our unpark event in the interim. This also protects us from user code that returns `NotReady` without parking.

Is this actually a problem? I haven't tested it (writing concurrent tests like this is not fun) but I can't see how the current code could prevent this.

**Comment by alexcrichton** [comment]
Thanks for the report! This is something thought that I believe is handled by `thread::park` and such. A call to `thread::current` doesn't clear any flags or actually block the current thread, and `thread::park` itself isn't called until a call to `poll` is finished entirely.

In that sense if a call to `Thread::unpark` comes it'll just prevent the later `thread::park` from blocking. That is, in step 4 above the flag I believe isn't cleared.

**Comment by Stebalien** [comment]
The problem is that the internal `thread::park` eats that flag.

* We tell some scheduler to unpark us when ready.
* Our scheduler unparks us.
* Some user-specified code (on our thread) calls `while !some_atomic_condition() { thread::park() }`.
* Eventually some other user-specified code (not on our thread) sets the condition and unparks our thread.
* We call `thread::park()` and wait forever because that park loop above ate our flag.

**Comment by alexcrichton** [comment]
Hm are you basically saying that if futures arbitrarily call `thread::park` that'll wreak havoc? I believe that will, but it also seems counter to "a `poll` implementation should return quickly"

**Comment by Stebalien** [comment]
My point is that a small, harmless delay (a user spinning up a thread at the beginning of the program) could turn into a deadlock.

On September 9, 2016 3:31:47 AM EDT, Alex Crichton <notifications@github.com> wrote:
>Hm are you basically saying that if futures arbitrarily call
>`thread::park` that'll wreak havoc? I believe that will, but it also
>seems counter to "a `poll` implementation should return quickly"
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/alexcrichton/futures-rs/issues/132#issuecomment-245840791

-- 
Steven Allen

**Comment by alexcrichton** [comment]
Hm I'm not sure I quite follow that part, could you clarify with a code example of what you're thinking? I do agree that `thread::park` *during* a call to `poll` would cause problems, but I'm not sure how surrounding code outside a `poll` would cause problems.

**Comment by Stebalien** [comment]
I'm talking about a call to `thread::park` during a call to poll. A better, concrete example is the following:

```rust
lazy_static!(static ref LOGGER: MyLogger = MyLogger::new());
// ...
my_future.and_then(|x| {
    my_logger.log(x);
})
// ...
my_future2.and_then(|x| {
    my_logger.log(x);
})
```

If both of these try to log from two different threads at the very beginning of the program (before the logger has been initialized), once of them will synchronize using `thread::park()` (internally, `lazy_static` uses `sync::Once` which calls `thread::park`). This will only happen early on in the execution of the program so from an efficiency standpoint, it's not an issue. However, a developer will definitely *not* expect their program to deadlock here and will have a vary hard time figuring out *why* it's deadlocking.

**Comment by alexcrichton** [comment]
Oh dear, that does indeed sound bad! Ok if we're only worked about `park` during a poll, though, we may be able to just implement `wait` differently with our own version of park and unpark. That way we can guarantee that all calls to park are our own.

**Comment by alexcrichton** [comment]
Oh @carllerche pointed out that we just need an `AtomicUsize` here actually, I'll just do that!

**Comment by carllerche** [comment]
To be fair, this is also what @Stebalien suggested in his original report :)

**Comment by alexcrichton** [comment]
Gah sorry I'm bad at reading recently :(

**Comment by oconnor663** [comment]
I'm coming back to read this issue from that linked PR (https://github.com/alexcrichton/futures-rs/pull/566). @alexcrichton could you clarify these parts for me:

> Sub-future 1 parks the task and schedules it to be unparked.

> This also protects us from user code that returns `NotReady` without parking.

Do these sentences refer to an old way that the futures library used to work, which no longer applies? The way the futures library currently works, the only `park` function available to user code is `std::thread::park`, which most futures should never call, yes?

**Comment by alexcrichton** [comment]
Nah I think everything is roughtly the same there's just been a few renamings. It's rare, yes, to call `std::thread::park` but also perhaps not unheard of

**Comment by carllerche** [comment]
I wouldn't even say it is "rare". It is completely legitimate to use locks w/ small critical sections in a future. For example, `futures::sync::mpsc` does this. Which also means that it is perfectly fine to call `std::thread::park` (and potentially even "common").
