### ISSUE TITLE
Too many channels

### ISSUE THREAD

**Issue by stepancheg** [alexcrichton/futures-rs#135]
futures-rs with tokio-core with rust stdlib has too many `channel` functions, so it is hard to understand which one is it when reading code.

So I'm proposing to at least rename `channel` in futures-rs to something like`sync_channel`.

**Comment by jwilm** [comment]
Usually to disambiguate these things it's nice to import the module where the function is defined so you can immediately see which version it is. For example, using the std lib's channel can be written as

```rust
use std::sync::mpsc;
let (tx, rx) = mpsc::channel();
```

And it's super clear what's going on.

`sync` in this case has a specific meaning, and I'd be reluctant to choose that specifically if that's not true to the implementation.

**Comment by alexcrichton** [comment]
Yes it's unfortunate they're all called `channel`, but that's also intentional because they're all doing very similar actions and a shared name is often useful for understanding what they're doing.

Also yes `sync_channel` has a specific meaning in the standard library which isn't necessarily applicable here.

**Comment by Diggsey** [comment]
What about renaming `channel` in `futures-rs` to `multishot` (since it is the stream equivalent to `oneshot`) and then add an implementation of `sync_channel` to tokio which mirrors the one in `std` (ie. it's a channel with a fixed-size buffer and back-pressure).

**Comment by alexcrichton** [comment]
At this point I don't think we're going to rename `channel` and the various types, so I'm going to close this.
