### ISSUE TITLE
Poll<T, E> = Result<Async<T>, E> vs Async<Result<T,E>>

### ISSUE THREAD

**Issue by Matthias247** [alexcrichton/futures-rs#141]
Hi,
why was the type of poll to be chosen to be `Result<Async<T>,E>` instead of `Async<Result<T,E>>`.
Imho the latter signature matches better to the typical definition of a future, which is it's either
- not resolved
- or resolved with either an error or a value

It also matches better the fact that the thing is a boxed (in the sense of 'monadic', not) version of the actual Result of the call.

**Comment by Stebalien** [comment]
In one word: `try!`. This way, one can `try!(something.poll())` (or, in when it stabilizes, `something.poll()?`) and then handle the non-error cases. Also, semantically, returning an error doesn't mean that the value has resolved. It could have, e.g., timed out.

Note, this could* possibly be changed in the future depending on what the final form of the [`Carrier`](https://github.com/rust-lang/rfcs/issues/1718) trait looks like. That is, it may eventually become possible to apply the `?` operator to `Async<Result<T, E>>`.

*I'm not a dev; I'm just speculating.

**Comment by alexcrichton** [comment]
Thanks for the report @Matthias247! This actually was indeed what we used to do, but after the discussion on https://github.com/alexcrichton/futures-rs/issues/108 we decided to settle on what we've got today. @Stebalien hit the nail on the head with the primary rationale being to support the use of `try!`.

**Comment by alexcrichton** [comment]
Closing due to previous discussion on this topic.

**Comment by AGausmann** [comment]
I do think this design decision should be reconsidered once the [`try_trait`](https://github.com/rust-lang/rust/issues/42327) feature gets stabilized.

**Comment by Nemo157** [comment]
With futures 0.3 removing the error type from the base `Future` type this has _basically_ happened, `TryFuture<Item = T, Error = E>` is equivalent to a `Future<Output = Result<T, E>>` so the return type of `Future::poll` is `Poll<Result<T, E>>` (in 0.3 `Poll` is now what was called `Async`, so this is similar to 0.1's `Async<Result<T, E>>`).

There are also some [`Try` implementations included for `Poll`](https://rust-lang-nursery.github.io/futures-rs/blog/2018/07/30/futures-0.3.0-alpha.2.html#try-impl-for-poll) now.

**Comment by AGausmann** [comment]
That's also a great step forward! I'm glad to see that, and a bit ashamed I didn't see that. Looking forward to the 0.3 rewrite then.
