### ISSUE TITLE
Is it correct to poll after error? Does stream end with error?

### ISSUE THREAD

**Issue by stepancheg** [alexcrichton/futures-rs#145]
`poll` documentation clearly states that it is an error to `poll` after `NotReady`.

However, it does not tell, is it allowed to call `poll` after error?

Why does it matter:

`Stream::then` may transform an error into a success.

```
stream.then(|_| {
    Ok(())
})
```

So if `then` is polled again after it seen error and converted it into success, `then` will be polled again, thus calling `poll` of underlying stream which previously returned error.

So, my question is: does stream ends with error?

IMHO, if `then` converted an error into success, then next `poll` on `then` should return EOF without calling underlying stream.

In another words, `then` callback should be called with `Err` parameter at most once.

**Comment by alexcrichton** [comment]
Ah yes it's intended that a stream *only* terminates on `Ready(None)`. An error can be thought of as just another element as part of an iteration, but the stream should still be valid after an error.

**Comment by stepancheg** [comment]
Are you sure? I think this design can cause lots of headaches.

For example, `skip` may never finish if polled until `Read(None)`, because it does not decrement `remaining` on error.

**Comment by alexcrichton** [comment]
Well, yes I'm sure that's the current intention. Otherwise a combinator like `or_else` would only be able to run at most once for an error.

**Comment by stepancheg** [comment]
OK, thanks!
