### ISSUE TITLE
Can a Stream be a Future?

### ISSUE THREAD

**Issue by amluto** [alexcrichton/futures-rs#146]
After pondering futures a bit, it seems to me that a `Stream<Item=I, Err=E>` is actually very close to being a `Future`, even if perhaps Rust can't express it right now.  Specifically, it's the trait `F` where `F` is:

```
Future<Item=(I, F), Err=e>
```

This is really quite close to `StreamFuture`, but I think it could be quite handy if they were actually the same thing.  Could this be made to work?

**Comment by alexcrichton** [comment]
A stream can indeed be a future! I believe the [`Stream::into_future`](http://alexcrichton.com/futures-rs/futures/stream/trait.Stream.html#method.into_future) method should work here?

**Comment by amluto** [comment]
Indeed.  What I mean is: can it literally be a future without needing to use an adapter?  IMO it would be quite neat, and would possibly save some typing and improve usability in generic code, if Stream had a trait bound on Future or was actually a Future for real.

I could imagine this causing a bit of confusion, though, as the Stream combinators don't do quite the same thing as the Future combinators.

I don't immediately see a way to make this work cleanly in Rust as it exists today, but maybe there is.

**Comment by alexcrichton** [comment]
Right yeah the stream combinators are a little different even with the same names so there can't be an inheritance relation. You could presumably write a simple combinator that takes a stream and is always a `Future`, though? Basically just a `StreamFuture` that yields `StreamFuture`, right?

**Comment by amluto** [comment]
More concretely, I mean something conceptually like:

```
trait Future {
    type Item;
}

trait Stream {
    type Item;
}

impl<S: Sized> Future for Stream<Item = S> {
    type Item = Option<(S, Box<Self::Item>)>;
}
```

This *parses*, but it blows up:
```
error: overflow evaluating the requirement `<Stream<Item=S> + 'static as Future>::Item` [E0275]
```

If I replace `Self::Item` with `Self`, it works.

Anyway, this is food for thought.  It might also be better if I asked the rust language folks.

**Comment by carllerche** [comment]
Yeah, you can't go with a recursive type and that would require an allocation for *every* stream for *every* iteration, which isn't ideal.

What is the requirement that you have that isn't fulfilled by having a Stream -> Future conversion?

**Comment by amluto** [comment]
I don't think the Box should be necessary if this were to work.  That being said, I think that my use case doesn't work the way I thought it did.  As a less useful usecase, a user could more easily select over both Futures and Streams at the same time (no into_future() needed), but this isn't such a big deal.

OTOH, I think it really could be done.  This variant of my code above does work:

```
trait Future {
    type Item;
}

trait Stream {
    type Item;
}

impl<S, I> Future for S
    where S: Stream<Item = I> {
    type Item = Option<(I, S)>;
}
```

So there wouldn't be a trait bound, but a more direct conversion would be possible.

Feel free to close this if you don't like the idea.

**Comment by alexcrichton** [comment]
@amluto would this work?

```rust
extern crate futures;

use futures::{Poll, Async, Future};
use futures::stream::Stream;

struct Stream2Future<S> {
    stream: Option<S>,
}

impl<S: Stream> Future for Stream2Future<S> {
    type Item = Option<(S::Item, Stream2Future<S>)>;
    type Error = S::Error;

    fn poll(&mut self) -> Poll<Self::Item, Self::Error> {
        let mut inner = self.stream.take().unwrap();
        match try!(inner.poll()) {
            Async::NotReady => {
                self.stream = Some(inner);
                Ok(Async::NotReady)
            }
            Async::Ready(None) => Ok(None.into()),
            Async::Ready(Some(e)) => {
                let inner = Stream2Future { stream: Some(inner) };
                Ok(Some((e, inner)).into())
            }
        }
    }
}
```

**Comment by alexcrichton** [comment]
Closing due to [this implementation](https://github.com/alexcrichton/futures-rs/issues/146#issuecomment-246915529), but @amluto would it be beneficial to move that into the `futures` crate itself?
