### ISSUE TITLE
Improper use of TaskRc should be detected at compile-time

### ISSUE THREAD

**Issue by taralx** [alexcrichton/futures-rs#148]
See tokio-rs/tokio-core#31.

I suspect that if we create an auto-trait (OIBIT) and constrain task::spawn to it, we can detect these cases at compile-time instead of run-time.

**Comment by alexcrichton** [comment]
Would be an awesome vector to explore! I'm not entirely sure how this would be done, but it'd be quite nice to rule this case out statically.

**Comment by taralx** [comment]
Well, I was thinking this:

```rust
#[feature(optin_builtin_traits)]

trait TaskSend { }
impl TaskSend for .. { }
impl<T> !TaskSend for TaskRc<T> { }

pub fn spawn<T: TaskSend>(obj: T) -> Spawn<T>
```

**Comment by alexcrichton** [comment]
Would be neat to explore!

**Comment by tikue** [comment]
This seems like a wart right now, because the reason for failures in combining `io::split` and spawned futures is not very discoverable and hard to remember the rules for.

**Comment by alexcrichton** [comment]
We're thinking of [deprecating `TaskRc`](https://github.com/alexcrichton/futures-rs/commit/d0be53a6a908faa0d8ceed522e4d063479fd3f80) so this problem will go away in the 0.2 release as it'll be removed.
