### ISSUE TITLE
Get an ironclad guarantee about safety of TaskData

### ISSUE THREAD

**Issue by alexcrichton** [alexcrichton/futures-rs#15]
Right now the safety of `TaskData` relies on the fact that the `id` field of `Task` is *never* reused. Thinking through this now I'm not actually sure that there's any reasonable way we can reuse it, however, as we would have to otherwise invalidate all existing `TaskData` handles.

We may need to alter the scheme to make `TaskData` resilient when used with a recycled `Task`. I have a few ideas.

cc @aturon

**Comment by MarkusJais** [comment]
Is recycling a Task necessary? After it is completed it might be better to create a new Task. 
Or is recycling necessary for performance reasons if Task has a lot of internal data?

**Comment by alexcrichton** [comment]
Ah I wasn't thinking of recycling a task per-se but moreso if we accidentally re-use IDs. That is, I'd expect a server to be able to service more than 4B requests over its lifetime, so we'll probably recycle an id at some point (but not the task allocation itself)

**Comment by MarkusJais** [comment]
Ah, now I understand :-)
There is something like  BigUint:
http://huonw.github.io/primal/num/bigint/struct.BigUint.html

Does the id have to be an int? What about UUID?

But both not optimal solutions as they would require more memory.

And UUIDs could collide although the risk is very, very small (but not strictly zero).

**Comment by alexcrichton** [comment]
It's true yeah, we could use something like a UUID with an incredibly large state space (to never overflow). The only restriction we have is we need the ability to atomically update it, but tbh a mutex here would be fine, so it's probably not a problem after all!

**Comment by MarkusJais** [comment]
The overhead of the mutex should be minimal or we might hit a wall under heavy load. 

On the other hand, that could be a sign of bad architecture and using to many threads in the application.

If there are only as many threads as CPUs then a mutex  that doesn't cover a lot of code might be perfectly fine.

**Comment by alexcrichton** [comment]
Ok, I think I've actually completely addressed this in https://github.com/alexcrichton/futures-rs/commit/4be64f371387aeaca0d890e7f4116bbdde6b0a6d, as we no longer need ids at all!

@aturon if you see this, we should talk very carefully about this API, and make sure I'm not going crazy.
