### ISSUE TITLE
futures-minihttp links are broken

### ISSUE THREAD

**Issue by yanns** [alexcrichton/futures-rs#159]
There are many links on http://aturon.github.io/blog/2016/08/11/futures/ to futures-minihttp that is now deleted on this repository.

**Comment by hgallagher1993** [comment]
Pretty much every link is dead in the post. . .At the bottom under `The Future` *all* the examples are dead.

**Comment by alexcrichton** [comment]
Thanks for the report! Unfortunately this was somewhat inevitable as links change over time, but we should have more news shortly with working links!

**Comment by yanns** [comment]
Just for info, a mini http server based on tokio:
https://github.com/tokio-rs/tokio-minihttp
