### ISSUE TITLE
[channels] Consider switching Sender / FutureSender -> Sender w/ poll_ready() fn

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/futures-rs#164]
The `Sender::send(self, ...) -> FutureSender` API is to back pressure. However, in Tokio the API is converging to having having functions return with an Error (and provide the input) when the type is not ready to have data pushed in. In order to get notified of readiness, a `poll_ready` fn is provided.

Perhaps `Sender` should be adapted to follow this style as well?

**Comment by alexcrichton** [comment]
Yeah I kinda prefer this style as well. It feels less ownership-heavy in terms of threading through a bunch of objects. We may want to provide an adapter though to get similar behavior.

This would also lead to a very natural solution to https://github.com/alexcrichton/futures-rs/issues/169

**Comment by carllerche** [comment]
The problem of back pressure with APIs that provide a value in an argument is a general one that comes up a lot. When at capacity, the function needs to be able to return the value. Other big APIs that have the same problem:

* `FramedIo::write`
* `Service::call`

I wonder if there would be value in having a trait or enum that is shared across all of these errors that indicate that the operation failed due to reaching capacity and here is the value.

**Comment by alexcrichton** [comment]
@aturon's also been thinking that we may want some kind of trait for this as well (e.g. a general trait for sinks of data) and that would perhaps provide a number of combinators.

**Comment by alexcrichton** [comment]
I believe this is now basically finished with the work on sinks.
