### ISSUE TITLE
Probably shouldn't use git paths in tutorial

### ISSUE THREAD

**Issue by Aatch** [alexcrichton/futures-rs#165]
Currently, if you try to follow the tutorial, you'll get two different versions of `futures`, resulting in a confusing error message about `futures::Future` not being in scope. This is because `tokio-core` uses `futures = "0.1"`, so the versions pulled are different. The same applies to `tokio-tls` and `tokio-core`, with `tokio-tls` pulling in the crates.io version.

**Comment by alexcrichton** [comment]
Indeed! Changed.
