### ISSUE TITLE
Consider a combinator that passes through values

### ISSUE THREAD

**Issue by partim** [alexcrichton/futures-rs#168]
Because of the requirement of `Send + 'static` on `Future::boxed()`, I try to avoid using boxed futures when building state machines. This results in using an enum for the various states where each variant holds the data for that state. A problem with that is when a state holds data that needs to be moved into the next state. After trying to build some rather unwieldy code, I instead implemented a little helper future that passes through this data when being resolved:

```rust
 struct Passthrough<F: Future, T> {
    future: F,
    data: Option<T>
}

impl<F: Future, T> Passthrough<F, T> {
    fn new(future: F, data: T) -> Self {
        Passthrough{future: future, data: Some(data)}
    }
}

impl<F: Future, T> Future for Passthrough<F, T> {
    type Item = (F::Item, T);
    type Error = F::Error;

    fn poll(&mut self) -> Poll<Self::Item, Self::Error> {
        let item = try_ready!(self.future.poll());
        let data = mem::replace(&mut self.data, None);
        if let Some(data) = data {
            Ok((item, data).into())
        }
        else {
            panic!("called poll() on a resolved Passthrough")
        }
    }
}
```

I know that `impl Trait` helps with solving this in most cases, but if I understand things correctly, I’d still need to box the result for certain combinator types if I were to embed it in some other type. So this would still be useful.

**Comment by alexcrichton** [comment]
This can be done with `map`, right? That is, `Passthrough::new(f, t)` is the same as `f.map(|v| (v, t))`

**Comment by partim** [comment]
Yes, but because of the closure, you can't express the resulting type and therefore  can't embed that into some other type. For an example, see one of these [DNS service implementations](https://github.com/partim/domain/blob/unified-services/src/resolv/service/sequential.rs#L27).

**Comment by alexcrichton** [comment]
Ah yes, indeed! That problem, however, is intended to be solved with `impl Trait` eventually (a new feature in the compiler) and can today be solved with trait objects. Does that suffice for now?

**Comment by partim** [comment]
How would I refer to the concrete type returned by a call to `map()` inside some function when declaring an `enum` or `struct`, though?

**Comment by alexcrichton** [comment]
Oh right yeah you couldn't refer to the concrete `Map` returned itself, but you could convert it to a trait object with `.boxed()` and refer to that instead.

**Comment by partim** [comment]
That’s probably alright, but at some point at least the `Send + 'static` bound was a bit of a problem.

In any case, I am fine with keeping this a private thing (the actual implementation I am now using got a little more complex and allows stealing both the future and the passed through data mid-flight). So, closing the issue.
