### ISSUE TITLE
[stream::channel] Sent message should dispatch immediately and not wait for `FutureSender::poll`

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/futures-rs#169]
I'm finding the behavior of `Sender::send` unexpected. There are times where my logic doesn't require immediately waiting for `FutureSender` to become ready again but may block on some other work first. In this case, the message sent doesn't actually fire.

Imagine a ping / pong loop that involves two senders. Fire a ping, wait for a pong, then repeat. If the order of operations is:

1) send ping
2) wait for pong
3) wait for ping sender to be ready again
4) loop

then the logic will not progress since the second task never receives ping.

**Comment by alexcrichton** [comment]
Agreed this should be fixed, and my favorite idea for how is actually https://github.com/alexcrichton/futures-rs/issues/164

**Comment by alexcrichton** [comment]
I believe this has been fixed with the work on sinks
