### ISSUE TITLE
futures_cpupool::CpuPool does not implement Sync

### ISSUE THREAD

**Issue by tomaka** [alexcrichton/futures-rs#17]
I guess it probably should.

**Comment by alexcrichton** [comment]
Indeed! This actually originally used crossbeam but it started segfaulting so I went back to channels. I believe you've [found what was at fault](https://github.com/aturon/crossbeam/pull/82) though, and now it works like a charm!

I've [gone back to that implementation](https://github.com/alexcrichton/futures-rs/commit/ef16d5d9778744e8221ff5dd3be7bc3c1f8b5cb2) and also [added an assert](https://github.com/alexcrichton/futures-rs/commit/cf26f7fbc667ede635c709b30b26f7315724c456), so closing.

**Comment by tomaka** [comment]
My PR wasn't merged and crossbeam can still crash, so I'm not sure about revert.

**Comment by alexcrichton** [comment]
Ah yeah I've got an override for now so tests pass locally, but I believe Michael-Scott queues are intended to have uninitialized data, so I think the error was just to ensure that the discriminant is always initialized.
