### ISSUE TITLE
hello world fails to compile

### ISSUE THREAD

**Issue by sumproxy** [alexcrichton/futures-rs#171]
For some reason I cannot compile https://github.com/alexcrichton/futures-rs/blob/master/TUTORIAL.md#hello-world, the error message is: https://t.co/SXdl3ej9Hp.
I'm on macOS, using rustc 1.11.0 (9b21dcd6a 2016-08-15)

**Comment by tmiasko** [comment]
Using git dependencies currently doesn't work for reasons explained in #165.
Following should work:

```Cargo
[dependencies]
futures = "0.1"
tokio-core = "0.1"
tokio-tls = { git = "https://github.com/tokio-rs/tokio-tls" }
```

**Comment by sumproxy** [comment]
Thanks, @tmiasko!
