### ISSUE TITLE
Stream::catch_unwind should return both errors inside Error.

### ISSUE THREAD

**Issue by tmiasko** [alexcrichton/futures-rs#174]
`Stream::catch_unwind()` for a stream S, returns a new stream with
 * `Item=Result<S::Item, S::Error>`
 * `Error=Box<Any + Send>`

Return type suggests that after you poll out `Ok(Async::Ready(Some(Err(..))))`,
additional items could be produced. Which is not true. In fact both the error
from stream S and panic finish the stream.

This seems to be potentially error prone. In fact implementation of
`CatchUnwind` already makes this mistake. It does not record that error has
been returned from S, and continues to poll from it. Instead it should return
`Ok(Async::Ready(None))` at least once.

Thus, I propose that `Stream::catch_unwind()` returns a new stream with:
 * `Item=S::Item`
 * `Error=Either<S::Error, Box<Any + Send>>>`

Where `Either` could be either a completely new type, or just a result.
Similar change could be done on `Future::catch_unwind` for consistency, but in
that case it not that essential.

**Comment by alexcrichton** [comment]
Would it clarify things here if I mentioned that if a stream returns an error it is *not* done? It can continue to return errors in general?

**Comment by tmiasko** [comment]
Thanks, that makes sense. I incorrectly assumed that error means that stream is done, not sure why at this point.
