### ISSUE TITLE
Can't call .forget() on a Box<Future>

### ISSUE THREAD

**Issue by tomaka** [alexcrichton/futures-rs#18]
Unfortunately the `forget()` function requires `Self: Sized`, which `Box<Future>` doesn't implement.

**Comment by tomaka** [comment]
Actually I just saw that there's `impl<T, E> Future for Box<Future<Item=T, Error=E>> where T: Send + 'static, E: Send + 'static`

I'm getting the following error:
> src\main.rs:178:19: 178:25 error: the trait bound `futures::Future<Item=std::opt
> ion::Option<Box<scene::Scene + Send>>, Error=Box<std::any::Any + Send>>: std::ma
> rker::Sized` is not satisfied [E0277]
> src\main.rs:178         new_scene.forget();
>                                   ^~~~~~

Not sure why...

**Comment by tomaka** [comment]
`futures::Future::forget(new_scene);` instead of `new_scene.forget()` works. Not sure if it's some sort of weird behavior in Rust.

**Comment by alexcrichton** [comment]
Oh dear, that's odd! It's definitely intended to be able to call `forget` on `Box<Future>`. With the UFCS weirdness, I wonder if this is perhaps a compiler bug?

**Comment by tomaka** [comment]
Oh my bad. The problem is actually that the trait was not imported. There's still the problem that the error message doesn't say that at all, but at least it's a logical behavior.
