### ISSUE TITLE
Futures for receiving a single value from an std::sync::mpsc channel

### ISSUE THREAD

**Issue by NeoLegends** [alexcrichton/futures-rs#187]
I've got code that wraps an mpsc channel in a future and uses `rx.try_recv()` for the value and `task::park().unpark()` for getting polled again. Is this the right way? And if so, could we add a future that does exactly this to the crate?

**Comment by alexcrichton** [comment]
Unfortunately this can't be done without *also* consuming the sender as we need to hook a notification of when an item is sent on a channel. That is, given an arbitrary `std::sync::mpsc::Receiver<T>` we don't have the necessary plumbing to give you a future :(

**Comment by NeoLegends** [comment]
Couldn't the sender be cloned? Or does the notification ever only apply to a single sender?

**Comment by alexcrichton** [comment]
This depends what the signature is. But yes, given purely just a `Receiver<T>`, I don't think this is possible unfortunately. (today)

**Comment by NeoLegends** [comment]
Well, one could do it the way I currently do it now, via try_recv and repeated polls. It just doesn't really seem that efficient, though.

**Comment by jonhoo** [comment]
For others wanting to do this, this macro may come in handy:
```rust
macro_rules! recv_one {
    ($ch:ident) => {{
        match $ch.into_future().wait() {
            Ok((next, ch)) => {
                #[allow(unused_assignments)]
                $ch = ch;
                next
            },
            Err((_, ch)) => {
                #[allow(unused_assignments)]
                $ch = ch;
                None
            }
        }
    }};
}
```
