### ISSUE TITLE
Stream::take and Stream::skip mismatch

### ISSUE THREAD

**Issue by tmiasko** [alexcrichton/futures-rs#188]
`Stream::take` includes errors in the number of elements it will take from the
stream, on the other hand `Stream::skip` does not include errors in the number
of elements skipped.

In both cases I think it would be better to apply those limits only to
`Stream::Item`s and just pass all errors through without counting them in.

**Comment by alexcrichton** [comment]
Oh right, now I'm remembering why `take` didn't include errors originally.

I'm of two minds about this. On one hand it seems conceptually correct to consider an error part of take/skip, but on the other hand it seems bad to *knowingly* drop errors on the ground.

@aturon @carllerche, thoughts about what the most appropriate behavior here is?

**Comment by NeoLegends** [comment]
Since most of the combinators only work on the `Item`s and not on the `Error`s, I would make `Stream::skip` and `Stream::take` behave the same.

**Comment by tmiasko** [comment]
Let me expand a little bit on rationale for suggested behaviour, because I
didn't include it in initial comment. 

In general I would expect `Stream::take(n)` and `Stream::skip(n)`, for given
`n`, to be complementary with respect to produced results. They could be
complementary with respect to both stream items and stream errors, but this has
unfortunate effect of ignoring some of the errors in skip as mentioned by Alex.

Thus, given special treatment errors receive in stream combinators overall, the
second best thing to do, would be making them complementary with respect to
items produced while passing all stream errors as is.

**Comment by alexcrichton** [comment]
Fixed by #199
