### ISSUE TITLE
compilation of futures-tls fails due to dependence on openssl release

### ISSUE THREAD

**Issue by tomyan** [alexcrichton/futures-rs#19]
Hi Alex

You probably know about this already, but when trying to use futures-tls the compilation fails with this message:

    futures-tls-0.1.0/src/openssl.rs:66:32: 66:63 error: failed to resolve. Could not find `HandshakeError` in `openssl::openssl::ssl` [E0433]

Digging into it, it looks like it's because the changes you made to the openssl crate (HandshakeError) haven't made it into a release yet. Give me a shout when there's an updated dependency that fixes this, or if you know of an easy workaround (just learning Rust). Looks like a really promising library, so thanks!

Regards

Tom

**Comment by alexcrichton** [comment]
Indeed! I've actually mostly just published on crates.io to reserve the name, but right now this actually [requires the `master` branch of OpenSSL](https://github.com/alexcrichton/futures-rs/blob/7c4fbe29ae8860ad23b19c7fd5516992f94fc60b/Cargo.toml#L32-L38) which works best through the `[replace]` mechanism. I hope to lift that restriction soon though as @sfackler indicates that a publish of OpenSSL is near on the horizon!

**Comment by alexcrichton** [comment]
Ok, I've removed all `[replace]` annotations and now they're all just git dependencies, so should be fixed!
