### ISSUE TITLE
Forward old docs to new docs

### ISSUE THREAD

**Issue by NeoLegends** [alexcrichton/futures-rs#205]
The old documentation at alexcrichton.com/futures-rs/futures/index.html is still available, even though the link in the readme points to docs.rs.

**Comment by alexcrichton** [comment]
Indeed! I plan on having the gh-pages docs be the "master" docs while all releases point to docs.rs. In general it'd be great for rustdoc to give you more versioning information at a glance, but that's not necessarily an issue for here...

**Comment by NeoLegends** [comment]
Alright, I see!
