### ISSUE TITLE
Error types should be bounded by std::error::Error

### ISSUE THREAD

**Issue by malbarbo** [alexcrichton/futures-rs#208]
Shouldn't   `Future::Error`, `Stream::Error` and `IntoFuture::Error` be bounded by `std::error::Error`?

This would facilitate error chaining...

**Comment by alexcrichton** [comment]
Thanks for the report! This was initially considered but we ended up deciding against it. Unfortunately this ends up being very limiting in terms of generics and bounds, so the flexibility earned by being lax here seemed too good to pass up.

Put another way, the `Error` bound can always be introduced after-the-fact. The core combinators, however, work both with and without this bound.
