### ISSUE TITLE
Provide `SinkError`

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/futures-rs#213]
This issue represents a discussion had in https://gitter.im/tokio-rs/tokio w/ @aturon.

At a high level, any type that has values pushed into it needs a way to return an error that contains this value in the event that it is not currently able to process the value (similar to `TrySendError` in [std](https://doc.rust-lang.org/std/sync/mpsc/enum.TrySendError.html))

The conclusion was to provide something like:

``` rust
/// Custom errors should provide a conversion to SinkError.
///
/// For example:
///     impl From<HttpError> for SinkError<HttpRequest, HttpError> {
///     }
///
pub enum SinkError<T, E> {
    NotReady(T),
    Other(E),
}

/// Example middleware that uses SinkError
impl<S> Service for Retry<S>
    where SinkError<S::Request, S::Error>: From<S::Error>,
{
    type Request = S::Request;
    type Error = S::Error;

    fn call(&self, request: S::Request) -> impl Future<S::Response, S::Error> {
        // Bump Arc count
        let retry = self.clone();

        self.inner.upstream.call(request).then(move |res| {
            match res {
                Ok(resp) => Ok(resp),
                Err(e) => {
                    match SinkError::from(e) {
                        SinkError::NotReady(request) => {
                            // Some global timer
                            timer::sleep(Duration::from_secs(10))
                                .and_then(|_| retry.call(request))
                        }
                        SinkError::Other(e) => Err(e),
                    }
                }
            }
        })
    }
}
```

**Comment by alexcrichton** [comment]
cc https://github.com/alexcrichton/futures-rs/issues/164, this'd likely be used there. Also a time to perhaps consider addition of a `Sink` trait

**Comment by Ralith** [comment]
`Sink::map` would certainly be useful to have.

**Comment by tailhook** [comment]
Does this request also mean that `poll_ready` in Service might be removed?

I wish tokio_service to land on crates.io soon, and with `poll_ready` removed, because I don't think it can be useful in the current form.

The idea described here and some kind of `Service + Sink` might be more useful.

**Comment by carllerche** [comment]
Would you be able to elaborate on "I don't think it can be useful in the current form"? Leaving your statement without any support doesn't provide much for us to understand your reasoning.

**Comment by alexcrichton** [comment]
@tailhook it sounds like you may want to open an issue on tokio-service? Perhaps that could be where we continue discussing `Service`?

For now I believe 0.1 of tokio-service is not blocked on this at all.

**Comment by tailhook** [comment]
@carllerche, @alexcrichton created an issue https://github.com/tokio-rs/tokio-service/issues/5

**Comment by alexcrichton** [comment]
I believe this was basically done with sinks, so closing.
