### ISSUE TITLE
Impl Future for &Future

### ISSUE THREAD

**Issue by tikue** [alexcrichton/futures-rs#217]
I was trying to return an `&Future` because (1) it didn't have a static lifetime and (2) it contained unnameable closures. It turns out that because this doesn't impl `Future`, you can't actually do anything useful with it.

**Comment by alexcrichton** [comment]
Unfortunately this isn't possible because the `poll` method requires `&mut self`. This is similar to how `io::Write` isn't implemented for `&io::Write` (but it is for `&mut io::Write`!)

**Comment by tikue** [comment]
Oh duh!
