### ISSUE TITLE
Consider `CoreFuture`/`Future` split

### ISSUE THREAD

**Issue by aturon** [alexcrichton/futures-rs#224]
We've talked a couple of times before about splitting the `Future` trait into a `CoreFuture` trait that covers all the required methods, and `Future` that is all defaulted methods.

Such a split could have a couple of benefits:

- The docs for each trait could be more focused on that "level" of work; that means, in particular, that docs for `Future` would be strictly oriented around combinator use, without delving into details about polling/task mechanics. That might make it easier to get a handle on the library.

- Potentially `CoreFuture` can use associated types for `Item` and `Error`, while `Future` uses type parameters. (There's currently a compiler bug blocking this).

OTOH, this would make life worse for people who *want* to use the lower-level APIs. A prelude might help.

**Comment by carllerche** [comment]
I am personally hesitant to make splits that are primarily for documentation reasons as, IMO this could be handled at the doc layer.

If there is a good API reason to make the split, than sure, but i'd rather hear about the API justification for it than to do it for docs.

**Comment by alexcrichton** [comment]
I'm also personally quite hesitant to do this. I have yet to be sold on type parameters (I thought we put that to rest already?) and I wouldn't want to take such a core concept and split it (e.g. would we do this for iterators?)

**Comment by aturon** [comment]
I'm going to close this out; I don't see us taking this step.
