### ISSUE TITLE
Proposal: Bounded MPSC channel with back pressure handling

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/futures-rs#229]
# Problem

"Multi producer, single consumer" (MPSC) channels are a great way for communicating across task boundaries. However, providing an implementation of a bounded MPSC channel that is future aware has some complications.

When the channel has not reached capacity, the producer handles are always "ready" to send a value. However, at some point, the channel will become full, at which point the producers will no longer be able to send the value. To be "future aware", when the channel is out of capacity, any request to send a value should be rejected and the producer task should be parked. From there, the easiest implementation would unpark all blocked tasks when the channel has additional capacity.

The issue with the easiest implementation is that it is subject to the [thundering herd problem](https://en.wikipedia.org/wiki/Thundering_herd_problem). Imagine that there are 1000 producer tasks. When the consumer receives the next value, the channel now has a single available slot. The consumer must unpark all 1000 waiting producers. This is because it is not guaranteed that a producer will actually send a value. However, it is *likely* that the producer will send a value, which means that 1000 tasks will race to send a value and only one will "win" and the 999 other tasks will become blocked again.

# Solution

**Note** I have not put much thought into optimizing the proposed implementation. I have only focused on a strategy that is possible. For example, I use Mutex, but really a spin lock would most likely be better or maybe there is a way to implement this without locks.

A MPSC channel is created with a capacity of `cap`, however it actually has a capacity of `cap + num-senders`. The structs look something like this:

```rust
struct Channel<T> {
	len: AtomicUsize,
	cap: usize,
	message_queue: MpscQueue<T>,
	blocked_queue: MpscQueue<Arc<Mutex<SenderState>>>,
}

struct SenderState {
	is_blocked: bool,
	task: Task,
}

pub struct Sender<T> {
	sender_state: Arc<Mutex<SenderState>>,
	channel: Arc<Channel<T>>,
}

pub struct Receiver<T> {
	channel: Arc<Channel<T>>,
}
```

The insight is that by having the true capacity be `cap + num-senders`, then every sender has one available slot once the channel capacity is reached.

So, the algorithms look something like this:

### Send

```
- Lock sender_state.
- Read is_blocked, if true, reject send.
- Increment len.
- If len > cap
	- park task
	- is_blocked = true
	- queue sender_state into blocked_queue
- Queue message on message_queue
```

### Receive

```
- Receive message from message_queue, if none return
- Decrement len
- Receive from blocked_queue, if none return
- Lock received sender_state
- is_blocked = false
- unpark task
```

This also has the advantage of providing fair scheduling to producers since the wait queue is first in, first out.

**Comment by alexcrichton** [comment]
This seems plausible to me, yeah. One thing I'm worried about though with avoiding the thundering herd problem is deadlocks. With blocking code (e.g. `sync_channel` we have a guarantee that when a thread wakes up it'll send a message). With async code, though, we have no idea if the unparked task will send a message. It could be disinterested in the queue by the time it wakes up.

Does that make sense? The easy solution to this is to indeed wake up everyone, but to be realistic I think we need to avoid that. Otherwise we need a way to hook "disinterest in sending a value" so when we wake up a task we have a guarantee that it'll eventually get around to sending it.

**Comment by carllerche** [comment]
Here is the current implementation. It could use some cleanup, documentation, and further testing, but it should get the point across as is.

https://github.com/carllerche/futures-mpsc
