### ISSUE TITLE
The `done` and `finished` names are hard to distinguish

### ISSUE THREAD

**Issue by aturon** [alexcrichton/futures-rs#230]
The names seem like synonyms, but they are subtly different. Maybe we can find more evocative names for 0.2.

**Comment by alexcrichton** [comment]
Agreed they're hard to distinguish, but I don't think this should block the 0.2 release. We can rename at any time really.

**Comment by aturon** [comment]
See thoughts [here](https://github.com/alexcrichton/futures-rs/issues/222#issuecomment-258717503) on connection to 0.2.

**Comment by alexcrichton** [comment]
Alternate proposal:

* `future::ok` - same as `finished` today
* `future::err` - same as `failed` today
* `future::done` - same as today

I kinda like `ok` and `err`, but not sold on `done`

**Comment by dwrensha** [comment]
[`ok()`](http://docs.capnproto-rust.org/gj/struct.Promise.html#method.ok) and [`err()`](http://docs.capnproto-rust.org/gj/struct.Promise.html#method.err) are eventually what I converged on for GJ, and I have been happy with the choice.

**Comment by tailhook** [comment]
> I kinda like `ok` and `err`, but not sold on `done`

`future::result` ?

**Comment by alexcrichton** [comment]
@tailhook 

That... makes sense! (I also like it)
