### ISSUE TITLE
Version of Stream::merge() without Both?

### ISSUE THREAD

**Issue by jugglerchris** [alexcrichton/futures-rs#239]
I have an application where I'd like to receive events from several `Stream`s, but I only want to receive one event at a time.  `Stream::merge()` is *nearly* right, but instead of receiving `Both(a,b)` if both sub-streams are ready, I would prefer to just receive one of the two, and leave the other to the next `poll`.

So my proposal would be to add a new method like `merge` (for lack of a better name, `mesh`), which returns something just like `stream::Merge` (say `Mesh`), which returned a `MeshedItem` which lacks the `Both` variant.

One complication is that you need to have a policy for which one you return; the simplest would be to favour the first (but risk never getting to the second if it's busy); otherwise a round robin policy might be better (but less ideal if you mesh several together in pairs).

In my application I want to expose a blocking "get next event" API to the client, where the events would be things like keypresses, timers, and signals; my current idea is to mesh the event sources together as above and block on `core.run(meshed.into_future())`.  Happy to hear it's a dumb idea and there's a better way to do it.  :-)

**Comment by Stebalien** [comment]
One way to do this is to use flatten. That is,

```rust
enum Event {
    Key(Key),
    Button(Button)
}
stream_mouse.merge(stream_keyboard).map(|event| {
    let (first, second) = match event {
        Both(button, key) => (Event::Button(button), Some(Event::Key(key)))
        First(button) => (Event::Button(button), None),
        Second(key) => (Event::Key(key), None),
    };
    stream::iter(iter::once(first).chain(second).map(Ok))
}).flatten()
```

However, I think this would be better served with a `Stream::select` method (like the one on `Future`). Basically merge but:

1. Only accepts one type.
2. Has round-robin polling.

That way you could write:

```rust
stream_mouse.map(Event::Button).select(stream_keyboard.map(Event::Key))
```

**Comment by alexcrichton** [comment]
@Stebalien your idea sounds great to me, and I think that'd solve @jugglerchris's use case as well! @jugglerchris what do you think of that?

**Comment by jugglerchris** [comment]
Hi,

A `select` as described sounds good to me, and does solve my problem.

The one niggle I'd have with just a 2-way select is that the round robin doesn't compose: `a.select(b.select(c))` becomes "unfair" and would produce a,b,a,c,a,b,a,c if all three are ready. It'd be nice to be able to solve this fairly somehow.

Perhaps all it needs is a new method on the Select struct, so you'd do:

```rust
a.select(b).also_select(c)
```

Chris

**Comment by alexcrichton** [comment]
@jugglerchris hm true yeah but that'd be the case no matter what for what you were thinking above as well, right?

**Comment by Stebalien** [comment]
@jugglerchris we could also add a `select_all` method.

**Comment by jugglerchris** [comment]
@alexcrichton Yes, the select is at least as good as my idea. :-)

**Comment by alexcrichton** [comment]
I've posted a PR for this in https://github.com/alexcrichton/futures-rs/pull/241

**Comment by jugglerchris** [comment]
Wow, thanks for implementing this so quickly!

**Comment by jugglerchris** [comment]
I've tried it out, and so far so good, thanks!
