### ISSUE TITLE
Future ~ Result, Stream ~ Iterator

### ISSUE THREAD

**Issue by killercup** [alexcrichton/futures-rs#24]
@alexcrichton, in the tutorial (and other places) you liken `Future` to `Iterator`, and `Stream` to… errr, nothing, IIRC.

But isn't the correlation more like this?

| # items | Sync | Async | Common operations |
| ----- | ----- | ------ | ----- |
| 1 | `Result<T, E>` | `Future<T, E>` | `map`, `and_then`, `joinN` (a.k.a. `zip`!) |
| ∞ | `Iterator<_>` | `Stream<_>`| `map`, `fold`, `collect`, `flatten` |

Many operators on `Option`/`Result`/`Iterator` has the same/similar names and semantics (… monads…), so the key differentiator is the number of items they can yield. (With respect to `Stream`'s error handling, the sync side should be `Iterator<Item=Result<T,E>`.)

Or am I missing some key insight of the implementation? I started reading the tutorial on this earlier, and my background is JS async primitives. (That Streams are actually Futures yielding `(val, next_future)` is a pretty nice property, btw.)

**Comment by killercup** [comment]
Evidence supporting this: 😉 

> The `done` variant takes a `Result<T, E>` and returns a `Future<Item=T, Error=E>`.

**Comment by alexcrichton** [comment]
Oh dear, I definitely didn't intend to liken futures to iterators! You're spot on with the issue title, futures are to results as streams are to iterators of results.

I... might shamelessy steal your nifty table! Could you point out though what gave you the impression that futures are to iterators? I'd like to wordsmith those bits specifically.

**Comment by killercup** [comment]
> I... might shamelessy steal your nifty table!

Of course! (You might want to leave the nod towards join/zip having different names though, to not confuse readers.)

> Could you point out though what gave you the impression that futures are [like] iterators? I'd like to wordsmith those bits specifically.

Sure! Fresh out of `TUTORIAL.md`:

> The Future trait, like Iterator, doesn't specify […]

> The combinators are designed to be very similar to the Iterator combinators. That is, they all consume the receiving future and return a new future.

> Usage of the combinators should feel very similar to the Iterator trait in Rust […]

> […] return a Future! Like with the Iterator trait, however, this isn't […]

(Okay, I admit, I just searched for "Iterator" in that file and quoted the first few results 😉)

**Comment by alexcrichton** [comment]
Aha! To the word smithy!

**Comment by killercup** [comment]
> word smithy!

May I suggest you use 'forge' instead? :trollface:

**Comment by alexcrichton** [comment]
Ok, I've bolstered the [`Stream` section](https://github.com/alexcrichton/futures-rs/blob/master/TUTORIAL.md#the-stream-trait) which should hopefully address this!
