### ISSUE TITLE
Misleading description of sink error

### ISSUE THREAD

**Issue by tailhook** [alexcrichton/futures-rs#248]
[Documentation states](http://alexcrichton.com/futures-rs/futures/sink/trait.Sink.html#errors):

> If the sink encounters an error other than being temporarily full, it uses the Err variant to signal that error. In most cases, such errors mean that the sink will permanently be unable to receive items.

I think "In most cases" does mean in all cases here, right? If it is not, there is no way to find out if is it allowed to call `poll_complete` again or not. Because of this:

> # Panics
> [..snip..]
> A previous call to start_send or poll_complete yielded a permanent error.

I.e. there is no way to find out which error is permanent and which isn't.

**Comment by alexcrichton** [comment]
I believe the intended semantics here were:

* If you're working with `S: Sink`, then you have to abide by "error == fatal"
* If you're working with a *specific* sink, you're not contractually obliged to translate "error == fatal"

In other words, sinks may or may not be safe to use after an error (like iterators after they're exhausted).
