### ISSUE TITLE
Mod design question 

### ISSUE THREAD

**Issue by softprops** [alexcrichton/futures-rs#249]
Apologies for this not really being a bug report but more of a design question. 

A pattern I often see in rust libraries is to define a "new" method inside an impl which serves as a constructor for instances of struts with the same name.

I noticed this crate deviates a bit in the location of those "new" methods. I see them defined them as free functions exported at the mod level. I was wondering if this was a personal preference, a new emerging design pattern, or just experimentation?

In many regards I like the structure of this project. Each struct it is own mod with a mod level "new". This ends up being less boiler plate as well as forces mods to stay focused. I'm curious about the design decisions going on here. Can you comment on them?

**Comment by alexcrichton** [comment]
Ah so the structure here is actually a little special compared to the status quo elsewhere. The public structs here, for example `future::Map`, doesn't actually have a public constructor. The way to construct that is the `Future::map` trait method.

Put another way all the structs here aren't intended to be constructed directly (like many others) but they're rather just adapters which serve the purpose of `impl Future` being returned from the `Future` trait itself.

So in terms of organization, the `future` module defines the `Future` trait, but the `future::map` module defines the `Map` struct. The `future` module needs to access *some* constructor for the `Map` type to implement the `Future::map` method. That could be `Map::new` but then anyone could call that (e.g. it's a public API) so it's not quite what we want. Instead we use a public `future::map::new` function which the `future` module can call. Note, though, that the `map` module is private and not reexported at the crate level, so downstream crates can't call `future::map::new`.

Does all that make sense? Basically I wouldn't recommend this for user-facing constructors where `Foo::new` is recommended, but for private constructors I've found it to be convenient!

**Comment by softprops** [comment]
That makes great sense. Thanks for the thoughtful explanation
