### ISSUE TITLE
join_all is not parallel

### ISSUE THREAD

**Issue by stepancheg** [alexcrichton/futures-rs#254]
AFAIU, `join_all` does not call `poll` on second and following futures (thus not starting them) until first future resolves.

It is
* inconvenient
* counter-intuitive
* different from e. g. `join5`, which polls all underlying futures on poll

**Comment by alexcrichton** [comment]
Heh this combinator was added *long long ago* where making it parallel was basically entirely infeasible. Should be much easier nowadays! Would you be interested in sending a PR for this?

**Comment by dwrensha** [comment]
For what it's worth, I wrote a parallel `All` future [here](https://github.com/dwrensha/zillions/blob/e3af5668b026073d7285a17ad7142b870454ad42/src/stresstest.rs#L32-L90).

**Comment by alexcrichton** [comment]
Perfect! That's exactly what I was thinking. @dwrensha want to send a PR?

**Comment by dwrensha** [comment]
Sure: #255.
