### ISSUE TITLE
mpsc::Sender should provide a way to check if a send will succeed

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/futures-rs#256]
In some cases, it would be very helpful to be able to check if the `Sender` will be able to accept a new value before "generating" this value. Right now, using `Sender` always requires an extra "buffer" slot to accept values that are rejected. However, the `Sender` knows if it can accept another value...

This applies to a number of other `Sink` implementors as well.

**Comment by carllerche** [comment]
I propose `Sink::poll_ready` (in part so that `poll_ready` shows up when I search the issue tracker!)

**Comment by alexcrichton** [comment]
We likely want to add this in the form of a `try_send` method which just returns the message back if it couldn't be sent (e.g. to make it atomic)

**Comment by carllerche** [comment]
Try_send doesn't satisfy the original issue which wants a way to know if the channel can accept a value before generating it.

**Comment by carllerche** [comment]
Being able to check before generating will (probably) be an important feature to correctly implement Service backpressure.

**Comment by alexcrichton** [comment]
Ah sorry yes right, forgot about that!

**Comment by carllerche** [comment]
This is resolved by `Sender::poll_ready()`
