### ISSUE TITLE
futures 0.1.4 depends on libstd even with default-features=false

### ISSUE THREAD

**Issue by arielb1** [alexcrichton/futures-rs#258]
## STR

Build something with no_std against futures 0.1.4. Observe that it links against libstd.

## Notes

This is a regression from futures 0.1.3.

**Comment by alexcrichton** [comment]
Fixed in https://github.com/alexcrichton/futures-rs/commit/2f4fd0c8a9afe6b6810010962ca04114a9cade73, thanks for the report!
