### ISSUE TITLE
Ergonomics of channel send

### ISSUE THREAD

**Issue by compressed** [alexcrichton/futures-rs#261]
Consider this code:

```rust
use futures::*;

fn main() {
    let (mut tx, rx) = futures::sync::mpsc::unbounded();
    tx.send(1);
}
```
You might think this is actually sending the message on the channel, but it's not because `Sink` has been imported via the glob import (and I'd imagine most users are using the glob import) so it's calling `Sink::send` not `UnboundedSender::send` (since `UnboundedSender` impls `Sink`).

We'd have to use UFCS instead:

```rust
fn main() {
    let (mut tx, rx) = futures::sync::mpsc::unbounded();
    UnboundedSender::send(&mut tx, 1).unwrap();
}
```

I guess the compiler warnings will lead the user to fix the code, but figured I would at least document it here.

**Comment by alexcrichton** [comment]
Yes this was an unfortunate oversight on my part. I mistakenly assumed that the inherent `send` method would take precedent, so `foo.send(bar)` would work just fine. Unfortunately the trait (likely also in scope) take `self` by value while the inherent method takes a mutable reference. As a result I believe the `Sink` method takes precedent.

I think that to fix this we'll need to figure out another method name for the unbounded send method. In the meantime though you can also do this inline with `(&mut tx).send(1)` without UFCS (although it's still quite bad)

**Comment by compressed** [comment]
Yeah I actually thought that the inherent `send` would take precedent as well, a bit unintuitive.

I think a new function name is probably the best fix. Something like `send_msg` maybe?

**Comment by casey** [comment]
I like `send_unbounded()` to make it clear that it's a method that is specific to an UnboundedSender.

**Comment by kc1212** [comment]
I also came across this problem too and made a workaround using `(&tx).send(msg)`. What I'm curious about is, what are the use cases of using the `Sink`'s `send`?

**Comment by alexcrichton** [comment]
@kc1212 it can in general be a helpful combinator for arbitrary sinks, so I think we'll want that to stick around in one way shape or form.

**Comment by arthurprs** [comment]
Lost a good 6 hours this week because of this :cry:

**Comment by golddranks** [comment]
I found this unergonomic as well. Sorry for just another me too -post :D
