### ISSUE TITLE
Add If/Else combinator

### ISSUE THREAD

**Issue by ghost** [alexcrichton/futures-rs#270]
I believe it could be useful to add an if/then/else combinator to return a single type implementing future from an if/then/else, even if the branches don't return the same type (as long as they return futures ultimately resolving to the same type)

Example:

``` rust
(if a {
    IfElse::If(futures::lazy(|| x))
} else {
    IfElse::Else(futures::finished(y))
}).and_then(|z| ...)
```

**Comment by alexcrichton** [comment]
Agreed! I've thought that we should have some useful enums (Perhaps like 2-4 variants) for a situation like this.

Want to send a PR?

**Comment by alexcrichton** [comment]
I believe this is now done with `Either`, so closing.
