### ISSUE TITLE
FromFinished trait to provide default implementations

### ISSUE THREAD

**Issue by ghost** [alexcrichton/futures-rs#273]
(sorry for the long message, I'm confused and I don't know whether this is a usage question or a feature request).

My use case is the following: in Thrussh, I implemented the whole SSH 2 protocol, which means in particular that clients and servers must be ready to handle *lots* of different requests, and reply with futures (for instance after interacting with a webserver and/or a database).

However, one cool feature of thrussh's is to be able to write clients and servers that accept only a subset of the protocol, and reject everything else.

With default implementations for most parts of the handlers, writing a new server becomes really easy, but it requires an extra trait, `FromFinished`:

https://docs.rs/thrussh/0.7.0/thrussh/server/trait.Handler.html

Question: should this trait be moved to futures? It seems different, but complementary to `IntoFuture` for when you need a "convertible to *that* future" instead of just "convertible to *some* future".

**Comment by alexcrichton** [comment]
Closing due to previous comment, but feel free to reopen if it's not suitable!
