### ISSUE TITLE
Turn owned iterator into stream

### ISSUE THREAD

**Issue by theduke** [alexcrichton/futures-rs#274]
It would be great to have a utility function that takes an owned iterator and converts it into a `Stream`.

This can be done with `stream::unfold`, but requires quite a bit of plumbing.

Something like this:

```rust
let iter = vec![1,2,3].into_iter();
let mut stream = unfold_iter(iter);
```

**Comment by theduke** [comment]
Whoops, there already is stream::iter.

**Comment by alexcrichton** [comment]
Ah yes this does indeed exist and looks like you found it,  so closing

**Comment by theduke** [comment]
Oh I thought I closed it yesterday myself, must have forgotten.
