### ISSUE TITLE
Broken link in TUTORIAL.md

### ISSUE THREAD

**Issue by zetok** [alexcrichton/futures-rs#277]
in the part `Defining the behavior of poll after resolution (fuse)` link to the `fuse` is broken

**Comment by theduke** [comment]
It's not just that link, it's all the doc links.

I created a PR pointing to docs.rs instead.

Please note that some parts of the tutorial are out of date and refer to types/functions that no longer exist.

**Comment by zetok** [comment]
Thanks for the fix :)

>Please note that some parts of the tutorial are out of date and refer to types/functions that no longer exist.

And thanks for the heads-up.
