### ISSUE TITLE
forward merge 

### ISSUE THREAD

**Issue by josephDunne** [alexcrichton/futures-rs#278]
I would like to add an API to the `Merge<S1,S2>` stream but before I do would like some feedback.
I would like to add the following function to the Merge stream:

```
forward_into<Sink1, Sink2>(Self, s1: Sink1, s2: Sink2) -> ForwardMerge<Sink1, Sink2>
  where Sink1: Sink<SinkItem=S1>,
        Sink1: Sink<SinkItem=S2>,
        Self::Error: From<Sink1::SinkError>,
        Self::Error: From<Sink2::SinkError>,
        Self: Sized
```

the idea being that we can split a stream and then merge it again into two sinks - one for the left item and one for the right. My concern is that perhaps the better way is to use the existing `forward` function on each half of the split stream and then join the two resulting `Foward` futures.
(side note: why is Forward not implemented as a `SendAll`? they seem to do the same thing on the surface)

My use case is I have a stream that produces items that have the same shape as `MergeItem` i.e. one item for left, one for right or both. This stream is not created via a split or merge - it just happens to produce items that have this shape. So perhaps we could turn `MergeItem` into a trait and then implement `forward_into` for any stream whose item implements `MergeItem`

```
trait MergeItem {
   type Left;
   type Right;

   fn get_left(&self) -> Option<Self::Left>;
   fn get_right(&self) -> Option<Self::Right>;
}
```

at the end of the day this might be to specific to my use case so wanted to get feedback before I do anything

**Comment by alexcrichton** [comment]
Thanks for the report! Seems like a nifty feature to me.

I'm not sure where exactly this'd show up, either on futures or sinks. We could also combine two sinks to create a new sink of a type that disambiguates. I'd prefer to keep the forward/send_all logic in `send_all` and `forward` if at all possible.

**Comment by carllerche** [comment]
Is there an action item to take from this? The issue has been inactive for a year.

**Comment by josephDunne** [comment]
No, it can be closed
