### ISSUE TITLE
adding certificates using backend ssl context object

### ISSUE THREAD

**Issue by kteza1** [alexcrichton/futures-rs#29]
```
let tls_handshake = socket.and_then(|socket| {
        let mut cx = ClientContext::new().unwrap();
        {
            let backend_cx = cx.ssl_context_mut();
            backend_cx.set_CA_file(ca);
            backend_cx.set_certificate_file(crt,  X509FileType::PEM);
            backend_cx.set_certificate_file(key, X509FileType::PEM);
        }
        cx.handshake(host_name, socket)
    });
```
I need to use this type
```
use futures_tls::backend::openssl::x509::X509FileType;
```
But seems like not everything from backend is exposed.

http://alexcrichton.com/futures-rs/futures_tls/backend/openssl/index.html

Do you think these should be exposed?

**Comment by alexcrichton** [comment]
Thanks for the report! Right now the intention of the `backend` module is to mirror that of `std::os`, which is to say that it provides backend-specific extension traits for the types defined in the `futures-tls` crate. The intention here is that if you're configuring OpenSSL then you'd also link to the openssl crate itself. 

Along those lines, you'd so somethiing like:

```rust
extern crate openssl;
extern crate futures_tls;

use futures_tls::backend::openssl::ClientContextExt;
use openssl::x509::X509FileType;

// ...
```

Does that make sense? Let me know if that doesn't work out!

**Comment by kteza1** [comment]
Ahhh. I tried that before, Got this error and gave up too soon
```
native library `openssl` is being linked to by more than one package, and can only be linked to by one package

  openssl-sys v0.7.14
  openssl-sys v0.7.14 (https://github.com/alexcrichton/rust-openssl?branch=tmp#8b988494)
```

Fixed this by using your fork of openssl now
```
openssl = {git = "https://github.com/alexcrichton/rust-openssl", branch = "tmp"}
```
I suppose your changes are going to be merged upstream. Will use your branch till then. Thanks.

**Comment by alexcrichton** [comment]
Ah yes indeed! Right now actually I've got no extra changes to rust-openssl, there's just a bug in Cargo on stable if a git repository has a workspace Cargo.toml it doesn't work as a dependency. My "fork" just deletes the workspace Cargo.toml so this project can compile on stable Rust.

Note though I'd much prefer to use a crates.io version of rust-openssl, and @sfackler has indicated that a new version is coming soon! As soon as that's out I'll update this so the dependencies are much easier to write down (e.g. everything uses crates.io)

**Comment by sfackler** [comment]
By soon I mean tonight, btw.
