### ISSUE TITLE
Stream should be able to return state when iteration completes

### ISSUE THREAD

**Issue by sfackler** [alexcrichton/futures-rs#301]
Here's something I've run into while working on https://github.com/sfackler/rust-postgres/tree/master/postgres-tokio. Say I have the following setup:

```rust
pub struct Connection { ... }

pub struct Statement { ... }

impl Statement {
    fn query(self, params: &[&ToSql], conn: Connection) -> Rows {
        ...
    }
}

pub struct Rows { ... }

impl Stream for Rows {
   type Item = Row;
   type Error = Error;

   ...
}
```

There's some cool stuff going on here - while in normal sync rust-postgres we have to internally collect all rows of a query before returning them, `Statement::query` here can stream over them as their received from the database. Unfortunately, we need to get the `Statement` and `Connection` back when we're done. It seems like the current convention is to add an `into_inner` method to `Rows` which will do this, but there are a couple of problems there:

1. We can't naiively return the `Connection` back whenever, since we may be in the middle of reading rows from the server. We'd need to either return a `Future` of the statement and connection, which is a bummer since the only time you'll reasonably be calling this is once you're already finished reading all of them, or return them directly but panic or return `None` or something if you're not done iterating.
2. This isn't composable with any of the stream combinators since they don't offer access to the wrapped stream.

It seems like the best way to resolve this is to adjust the `Stream` interface a bit to allow this in a first class manner:

```rust
pub trait Stream {
    type Item;
    type Error;
    type State;

    fn poll(&mut self) -> Poll<StreamEvent<Self::Item, Self::State>, Self::Error>;
}

pub enum StreamEvent<I, S> {
    Next(I),
    Done(S),
}
```

`Collect` would similarly be adjusted to be a `Future<Item = (Vec<S::Item>, S::State)`, and similarly for other combinators.

It could alternatively be a separate trait but it seems like this would be a common enough use case to avoid the duplication?

**Comment by aturon** [comment]
Thanks @sfackler, this is a pretty interesting line of thought! I've put it on the docket for the 0.2 release, when we consider the next round of breaking changes.

**Comment by sfackler** [comment]
I'm working on a prototype of this: https://github.com/sfackler/futures-state-stream

**Comment by sfackler** [comment]
Some of the API changes for this are pretty straightforward (rename map to map_item and add map_state, for example), but there are some more interesting cases:

* What do do about `wait`? The best thing seems to be to iterate over `Item`, and have an `into_state` function that runs the iterator to completion and then returns the state.
* We'd presumably want something like `fn and_then_state<F, Fut>(self, f: F) -> AndThenState<Self, F> where F: FnOnce(Self::State) -> Fut`, but is that the best naming scheme? We'd also need a variant for `then` as well.
* What would `flatten` do with the states of the internal streams? Forget them?
* How should `take` work? Maybe have `type State: Option<S::State>`?
* How should `fuse` work? Guarantee a panic?

**Comment by sfackler** [comment]
I don't think `wait` can be prototyped out of crate due to reliance on `Spawn`, but I'll fill out the rest of the APIs.

**Comment by alexcrichton** [comment]
Agreed that this is interesting! You've got quite a few questions there, though, which to me seems a little uncomfortable. I'd probably vouch for one of two alternate routes for now:

* A convention that if you "finish with state" you are actually a stream of an either-like enum. Most of the time you just get one end of the either ("here's an item") but at the end you get the state back. If this sort of API isn't used much by users but is largely an implementation detail then this should have little ergonomic effect.
* Add `into_inner` and friends to all combinators (which we need to add anyway), and hope you're not working in a generic context. I'm not sure how often you'd be working in a generic context though and this'd need to plumb through generics? (e.g. be a trait method)

**Comment by sfackler** [comment]
The use case I have for this is being consumed by end users: https://github.com/sfackler/rust-postgres/blob/master/postgres-tokio/src/lib.rs#L890-L893, so the ergonomics of e.g. collect are pretty important.

As I've been working with it, I do feel that it probably makes sense for it to be a separate trait than `Stream`, since the use cases for them are fairly distinct from each other.

**Comment by alexcrichton** [comment]
Yeah it's true that if a bunch of combinators don't fit then perhaps a new trait is warranted. You can always trivially change a "stateful stream" to a normal stream in that case!

**Comment by Diggsey** [comment]
This would also be useful for several methods which already exist on `Stream`, eg. `take_while`, `take`, which currently have no way to return the remainder of the stream - all methods to do so either incur the runtime overhead of a channel, or have tricky-to-use APIs (the best option being to pass in a `FnOnce` to call with the stream "state" once it reaches the end).

Perhaps some combinators on a "normal" stream would return a stateful stream, and it's possible to convert a stateful stream to a normal stream *without* losing the state via the `FnOnce` callback, which it will automatically call when dropped, or when iteration reaches the end, whichever comes sooner.

**Comment by tomprince** [comment]
I was looking for something like this to split a stream in to multiple sub-streams delineated by a predicate like `take_while`.

**Comment by aturon** [comment]
I'm going to go ahead and close out this issue, due to the existence of @sfackler's crate and in particular his feeling that:

> As I've been working with it, I do feel that it probably makes sense for it to be a separate trait than Stream, since the use cases for them are fairly distinct from each other.
