### ISSUE TITLE
stream::unfold's signature is a bit restrictive

### ISSUE THREAD

**Issue by sfackler** [alexcrichton/futures-rs#302]
Specifically, `where F: FnMut(T) -> Fut, Fut: Future<Item = Option<(It, T)>>` seems preferable to `where F: FnMut(T) -> Option<Fut>, Fut: Future<Item = (It, T)>`, since there are cases where you don't know if there are more items at the time of the closure evaluation.

**Comment by sfackler** [comment]
Example usage of the proposed version: https://github.com/sfackler/rust-postgres/blob/9466dfed2dc694017c41b0e08259460487cf2d45/postgres-tokio/src/lib.rs#L621

**Comment by alexcrichton** [comment]
Agreed we should change. I thought we had an issue for this but apparently we don't.

In any case, tagging as 0.2!

**Comment by sfackler** [comment]
The same is true for `Stream::for_each`.

**Comment by alexcrichton** [comment]
I vaguely remember `for_each` intentionally using `Result` rather than `IntoFuture`. @aturon do you remember why?

**Comment by aturon** [comment]
@alexcrichton 

No deep reason. cc https://github.com/alexcrichton/futures-rs/pull/321, which if possible I'd like to land for teaching purposes.

**Comment by khadiwala** [comment]
I think the [tokio chat example](https://github.com/tokio-rs/tokio-core/blob/master/examples/chat.rs) is a pretty good example of this issue. The reader loop is much [nicer with an unfold](https://gist.github.com/khadiwala/8e0314484f454e868ab3fa5564c4fb7a) but you're forced to terminate the stream with an error (which is ignored later) instead of just using an empty, because the end of stream condition is async.

**Comment by alexcrichton** [comment]
Agreed!

**Comment by aweinstock314** [comment]
Regarding "I thought we had an issue for this but apparently we don't.", we do: https://github.com/alexcrichton/futures-rs/issues/260 (thought it would be useful to cross reference them, not sure which one should be considered the duplicate since there's more discussion on here).

**Comment by alexcrichton** [comment]
Aha yep! Closing in favor of that one: https://github.com/alexcrichton/futures-rs/issues/260
