### ISSUE TITLE
future::Shared can hang if a clone gets dropped

### ISSUE THREAD

**Issue by dwrensha** [alexcrichton/futures-rs#304]
Consider the following program:

```rust 
    use futures::Future;
    use futures::sync::oneshot;

    let mut core = ::tokio_core::reactor::Core::new().unwrap();
    let handle = core.handle();

    let (tx, rx) = oneshot::channel::<u32>();
    let f1 = rx.shared();
    let f2 = f1.clone();

    let (tx2, rx2) = oneshot::channel::<u32>();

    handle.spawn(
        f1.map_err(|_| ()).map(|x| *x).select(rx2.map_err(|_| ()))
            .and_then(|x| { println!("first task got {}", x.0); Ok(()) }).map_err(|_| ()));

    let (tx3, rx3) = oneshot::channel::<u32>();

    handle.spawn(f2.map(|x| tx3.complete(*x)).map_err(|_| ()));

    tx2.complete(11); // Causes `f1` to get cancelled.
    core.turn(Some(::std::time::Duration::from_millis(1)));

    tx.complete(42); // Should cause `f2` and then `rx3` to get resolved.
    let result = core.run(rx3).unwrap();
    assert_eq!(result, 42);
```

I expect this to terminate successfully. Instead, it hangs at the `core.run()`. The problem, as I understand it, is that once `f1` is cancelled, `tx.complete(42)` has no way of waking up the proper task. One way to solve this might be to add some `unpark()` logic in the destructor of `Shared<F>`.

**Comment by alexcrichton** [comment]
Thanks for the detailed report! I think I've fixed this in https://github.com/alexcrichton/futures-rs/pull/305, but it's not quite done in an optimal fashion unfortunately. Could you see if it fixes your use case locally, though? (the test here should pass at least)
