### ISSUE TITLE
IntoFuture on Result<T, E> isn't a good idea

### ISSUE THREAD

**Issue by ishitatsuyuki** [alexcrichton/futures-rs#307]
This leads to hiding errors, with the following example (taken from the tokio chat):
```rust
Interval::new(Duration::from_secs(1), &handle).into_future()
                                              ^~~~~~~~~~~~~~
                                               error handling expected
```

Actually, I don't think people use this to instantly construct leaf futures, since there's already some methods to do it.

**Comment by sfackler** [comment]
I am the person who ran into this, and I don't agree that the impl is an issue. This only happened in test code, and I otherwise find that implementation pretty useful.

**Comment by alexcrichton** [comment]
This winds up being a cornerstone of very common usage in the futures crate today, so I'm going to close this.
