### ISSUE TITLE
Consider renaming task park / unpark

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/futures-rs#312]
Placeholder issue for an 0.2 discussion.

Originally, the names were picked for symmetry with thread park / unpark. However, the behavior is sufficiently difficult that I believe the naming is leading to unnecessary confusion (this is also based off of observing questions in Gitter).

**Comment by leodasvacas** [comment]
To unpark a thread means immediately wake it, to unpark a task it usually means to schedule it to be polled. I'd suggest park -> suspend/delay/pause and unpark -> schedule. Since future is a time metaphor it seems helpful to use other time metaphors.

**Comment by carllerche** [comment]
> To unpark a thread means immediately wake it

That's not strictly true. unparking a thread has no guarantees in terms of **when** the thread gets scheduled to execute. Just like w/ futures, the OS scheduler is free to schedule the thread as appropriate.

**Comment by carllerche** [comment]
I propose either:

* `task::current()` & `Task::notify()`
* Leave it as is.

Now is the time to make the change (#436). It should either happen or we leave the naming as is.

**Comment by ipetkov** [comment]
+1 on `current`/`notify`. It always bothered me that `park` implied side effects when it had none

**Comment by alexcrichton** [comment]
Done! (#436)
