### ISSUE TITLE
Consider providing a Spawn trait

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/futures-rs#313]
Given the number of different types of executors for driving futures, it seems worth providing a trait representing the ability to spawn a task with a future.

One option:

```rust
/// Value that can spawn a future
///
/// On spawn, the executor takes ownership of the future and becomes responsible
/// to call `Future::poll()` whenever a readiness notification is raised.
pub trait Spawn<T: Future<Item = (), Error = ()>> {

    /// Spawns a future to run on this `Spawn`.
    ///
    /// This function will return immediately, and schedule the future `f` to
    /// run on `self`. The details of scheduling and execution are left to the
    /// implementations of `Spawn`.
    fn spawn_detached(&self, f: T);
}
```

[Implementation](https://github.com/carllerche/futures-spawn)

The reason the function is `spawn_detached` is that there also are variants built on top of this primitive that return a future representing the completion of the spawned future:https://github.com/carllerche/futures-spawn/blob/inference/src/lib.rs#L21-L73

`SpawnHelper` exists to make rustc happy in some cases. There could be better ways of implementing this entire abstraction so it is up for discussion.

I also updated CPU pool to work with this `Spawn` trait: https://github.com/carllerche/futures-threadpool

Relates to: tokio-rs/tokio-core#57, tokio-rs/tokio-core#77

**Comment by Diggsey** [comment]
This also allows implementing some more concurrency primitives, like a futures-based Mutex: https://github.com/Diggsey/futures-spawn/tree/sync

(Allocations could be reduced a little, but it's using purely safe code)

**Comment by alexcrichton** [comment]
Some notes from a discussion with @carllerche today:

* The `Spawn` trait seems good as-is
* We may wish to add `Future::background(self, &S: Spawn<Self>)` to ergonomically run in the background
* Methods could be added to `oneshot` modules for "spawn with a handle", e.g. `futures::{sync, unsync}::oneshot::{spawn, spawn_fn}`.
* Everything but `Spawn::spawn_detached` may wish to panic if the `S: Spawn` refuses the acceptance of the future.

**Comment by alexcrichton** [comment]
I've opened a PR for this change: https://github.com/alexcrichton/futures-rs/pull/455

**Comment by alexcrichton** [comment]
also cc @antoyo, this is what we were talking about in Mexico a few weeks ago.

**Comment by antoyo** [comment]
Thanks for your great work.
I'm keen to use this new feature.

**Comment by antoyo** [comment]
I played a bit with this new `Spawn` trait and `futures-glib` and I'm wondering how it will work with the networking code.
For instance, `TcpStream` needs a `Handle` in `tokio-core` while `TcpStream` in `futures-glib` requires a `MainContext` that is attached to a `Source`
I don't understand how we can make that generic with the new `Spawn` trait because, in the `futures-glib` case, we actually need a `MainContext` to call `Source::attach(MainContext)` so a `Spawn` would not be sufficient.
If we take `hyper` as an example, the `TcpStream` can either come from `futures-glib` or `tokio`.
Can you tell me how this should work?
(I can show you some code if needed.)
Thanks for your help.

**Comment by carllerche** [comment]
@antoyo I'm not really understanding the problem. Code would help (me at least)

**Comment by alexcrichton** [comment]
@antoyo oh so in futures-glib you'd have:

```rust
impl<F> Spawn<F> for Executor
    where F: Future<Item = (), Error = ()> + 'static,
{ 
    // ...
}
```

That'd just abstract the spawning of futures, but wouldn't allow abstracting over I/O. For I/O the [tokio-io](https://github.com/tokio-rs/tokio-io) crate would be used with `AsyncRead` and `AsyncWrite`, similar to what [hyper does today](https://github.com/hyperium/hyper/blob/1cd8ea36f33486c352b53cbbf92bba889077e85a/src/http/conn.rs#L32). That is, if the crate doesn't require a concrete I/O object, it'd operate generically over those two traits. For futures-glib this just means that those traits are implemented for the relevant I/O objects.

Now the tricky piece comes in when you actually want to do something concrete! For example issue a TCP connection in Hyper. For this Hyper [has a trait](https://github.com/hyperium/hyper/blob/master/src/client/connect.rs#L14-L26) where the [default implementation](https://github.com/hyperium/hyper/blob/1cd8ea36f33486c352b53cbbf92bba889077e85a/src/client/connect.rs#L41-L46) uses a `Handle` from tokio-core. There's unfortunately no way to abstract that generically, but the idea is that local crates would follow a similar pattern as to hyper. Providing a default implementation with a specific runtime (e.g. futures-glib or tokio-core) but a trait to slot in new implementations.

Does that make sense?

**Comment by antoyo** [comment]
Yeah, thanks.
I'll play with that in the next weeks.

**Comment by antoyo** [comment]
I started to look at this, but I have not managed to understand how I could do that.
For instance, in `hyper`, the `handle` is sent to `bind_client()` [here](https://github.com/hyperium/hyper/blob/66551345836fb60a5cc87d0b5b397164914eb45c/src/client/mod.rs#L170).
What to do about that?
In `tokio-proto`, `bind_client` needs a `Handle`.

I also have a related question.
I was looking into `tokio-uds` to see how to do the same but it seems tied to `mio`.
So is it the kind of crate that needs to be completely rewritten for `futures-glib`?
Thanks for your help.

P.S.: do you think we should continue this discussion elsewhere? If yes, where do you suggest?

**Comment by alexcrichton** [comment]
@antoyo ah yes so tokio-proto will need to be updated first here, as the [only reason it needs a `Handle`](https://github.com/tokio-rs/tokio-proto/blob/42ddd45cd34fde8ddd12bdf49a8147762787bf33/src/streaming/multiplex/client.rs#L80-L81) is actually to spawn something. Once that's implemented then Hyper would also be generic over a `Spawn` implementation to be usable with futures-glib.

Also yeah unfortunately for now `tokio-uds` will need to be duplicated for `futures-glib`, I don't believe it's possible for it to share code with the glib-based version.

Also no worries continuing discussion here! Fine by me :)
