### ISSUE TITLE
Consider returning a new `oneshot::Sender` from a successful `poll()`

### ISSUE THREAD

**Issue by Diggsey** [alexcrichton/futures-rs#319]
The `oneshot` channel is useful for request/response type architectures. However, at the moment, the receiving side of the channel must allocate a new channel on every request, which imposes an unnecessary allocation overhead.

When `poll()` is successful, it's guaranteed that the `Sender` side has been consumed, so it's safe to construct a new one on the receiver side and return it to the caller. This allows reusing the oneshot for subsequent requests.

**Comment by alexcrichton** [comment]
This seems like a great library that could be built externally, but one that'd have too much ergonomic overhead to be in this crate itself perhaps.
