### ISSUE TITLE
Never vs. PhantomData

### ISSUE THREAD

**Issue by cramertj** [alexcrichton/futures-rs#32]
[An RFC](https://github.com/rust-lang/rfcs/blob/773cbfb1a8f17835173f47a76f6aee72095775a8/text/1216-bang-type.md) was recently approved for the `!` (`Never`) type, which represents the type of a value that can never exist.

Several structs in of `futures-rs` use `PhantomData` to mark the type of values that can't exist, such as [the `Error` type of `Finished`](https://github.com/alexcrichton/futures-rs/blob/d99a7e20b4a3d1f6ddd52c416549987ae1dd23a5/src/finished.rs#L10), [the `Item` type of `Failed`](https://github.com/alexcrichton/futures-rs/blob/d99a7e20b4a3d1f6ddd52c416549987ae1dd23a5/src/failed.rs#L9), and [the `Item` and `Error` types of `Empty`](https://github.com/alexcrichton/futures-rs/blob/d99a7e20b4a3d1f6ddd52c416549987ae1dd23a5/src/empty.rs#L12). I believe that, once [this PR](https://github.com/rust-lang/rust/issues/35121) lands (and then makes its way to stable), these structs should be rewritten to use the `Never` type. `Empty`, for example, could be written as follows:
```rust
pub struct Empty {}

pub fn empty() -> Empty { // Is this even necessary any more?
    Empty {}
}

impl Future for Empty {
    type Item = !;
    type Error = !;

    fn poll(&mut self, _: &mut Task) -> Poll<Self::Item, Self::Error> {
        Poll::NotReady
    }

    fn schedule(&mut self, task: &mut Task) {
        drop(task);
    }
}
```

Unfortunately, this feature has yet to land on nightly, let alone stable. Therefore, a transition to `Never` is likely a ways off. As this library is already getting lots of attention, I believe there should be a plan for how and if to structure the library so that a future (hehe 😃 ) transition to `Never` is possible.

In order to be more consistent with terminology, I also think that `Empty` should be renamed to `Never`. `!` is called `Never` rather than `Empty` or `Void` as a result of the discussion [at the end of the `Never` PR](https://github.com/rust-lang/rfcs/pull/1216). The gist of it is that `Empty` isn't a future for an `Empty` value, it's a future for a value that can `Never` exist (i.e. it `Never` completes).

P.S. Great work on this library, @alexcrichton & company! I'm excited to use this in my future Rust projects.

**Comment by alexcrichton** [comment]
Oh man I'd love to make use of `!`! This seems like a super slick way to use that type, and I know I personally find it annoying that sometimes I have to specify the other type parameter of `failed`, `empty`, etc.

Right now though this library does compile on stable Rust, and I'd personally prefer to require that, but as soon as `!` lands on nightly then I'd love to add a nightly feature to this crate which adds versions of these combinators. Eventually once `!` is stable we can just deprecate all the old combinators in favor of the ones using `!`.

How's that sound?

**Comment by cramertj** [comment]
Sounds great! I'll keep an eye out on the `!` PR and follow up once it lands on nightly.

**Comment by cramertj** [comment]
The ergonomics of this feature didn't work out due to restrictions around default type parameters and missing trait impls for `!`. I'm closing for now with the intent to reopen later once `!` and default type parameters have had a chance to develop.
