### ISSUE TITLE
Consider using non-Fn traits in future combinator bounds

### ISSUE THREAD

**Issue by Diggsey** [alexcrichton/futures-rs#329]
Closure types cannot be named, `impl Trait` is still unstable and even when stabilized will only work in return type position for the immediate future (meaning its use is both limited, and contagious). Manually implementing `Fn` traits on custom types is also unstable, and likely to remain that way for some time based on the issues blocking it.

All combined, this make using future combinators by anyone but the top-level consumer of an API actually impossible without additional boxing: the only other work-arounds are to switch to nightly or to implement the logic from scratch.

The library could give users a bit of breathing room if it allowed non-Fn traits to be used in eg. the `map()` combinator. I see a couple of ways this can be done:
1) Create new traits, eg. `Mapping<From, To>` which are implemented for all `Fn` types automatically. This would be ideal, but I'm unsure if it will play well with coherence.

2) Failing that, create the same new traits, but instead of modifying the existing combinators, add similarly named combinators that take a custom type rather than a closure.

This would not give quite the convenience of a closure, but is a lot better than nothing, IMO.

**Comment by alexcrichton** [comment]
This is something that'll get solved with `impl Trait`, and in the meantime it allows for much more ergonomic usage at the expense of a few boxes. I think that `impl Trait` is near on the horizon, so I'm going to close.
