### ISSUE TITLE
Can S: Stream implement Iterator?

### ISSUE THREAD

**Issue by withoutboats** [alexcrichton/futures-rs#335]
I believe there are annoying coherence issues with this right now, but is this a reasonable impl with the way `Stream`s are usually defined?

```rust
impl<S: Stream> Iterator for S {
    type Item = Poll<S::Item, S::Error>;
    fn next(&mut self) -> Option<Poll<S::Item, S::Error>> {
        match self.poll() {
            Ok(Async::NotReady)       => Some(Ok(Async::NotReady),
            Ok(Async::Ready(Some(x))) => Some(Ok(Async::Ready(x))),
            Ok(Async::Ready(None))    => None,
            Err(err)                  => Some(Err(err)),
    }
}
```

In terms of stackless coroutines and & async/await, this could be very useful because it could allow users to treat streams essentially like iterators in the context of an async generator:

```rust
for value in stream {
    let value = await!(value)?;
}

**Comment by alexcrichton** [comment]
We do have a `.wait()` option which turns a `Stream` into an `Iterator`, but it blocks for the next element as opposed to shipping through `Async::NotReady`. Otherwise seems like if it's useful it'd be a nifty combinator to have regardless!

**Comment by alexcrichton** [comment]
I think that for now `Stream::wait` should suffice for blocking situations and otherwise we're relatively averse to propagating `NotReady` without a task b/c then we don't know where notifications go, so I'm going to close.
