### ISSUE TITLE
BiLock allocates when locking

### ISSUE THREAD

**Issue by Kixunil** [alexcrichton/futures-rs#337]
I'm surprised by the allocation. Is it absolutely necessary for some reason? If it was implemented just to get something working soon, I'd be interested in optimising it.

**Comment by alexcrichton** [comment]
Indeed! This is currently intentional, and only happens in the "slow path" where a task needs to block. PRs are of course always welcome to optimize this!

**Comment by Kixunil** [comment]
Ok, thank you, I'll look at it later.
