### ISSUE TITLE
Missing "tailcall" link

### ISSUE THREAD

**Issue by SimonSapin** [alexcrichton/futures-rs#34]
In https://github.com/alexcrichton/futures-rs/blob/master/TUTORIAL.md#user-content-send-and-static

> As a bonus, these bounds allow for some [interesting optimizations][tailcall].

But there is no URL associated with `tailcall`.

(BTW, I know what a tail call optimization is but I don’t see how these bounds enable it. I hope the intended link explains the latter and not just the former :))

**Comment by alexcrichton** [comment]
Oops! I intended to have a section on this and it ended up not coming to fruition, I'll link to the method for now.
