### ISSUE TITLE
futures::sync::mpsc::UnboundedSender::send conflicts with Sink::send

### ISSUE THREAD

**Issue by casey** [alexcrichton/futures-rs#343]
And it has a different signature and semantics. I wrote this PR to tokio-proto to call it explicitly:

https://github.com/tokio-rs/tokio-proto/pull/117

Can we rename it so that there is no conflict? Ideas for names:

`send_unbounded()` pretty explicit, and clear where the method is coming from
`send_now()` reflects the fact that it will complete immediately

**Comment by alexcrichton** [comment]
Thanks for the report! I think this is tracked in https://github.com/alexcrichton/futures-rs/issues/261, so I'm going to close in favor of that

**Comment by casey** [comment]
Oops, didn't notice. Sweet.
