### ISSUE TITLE
Provide an atomic Task cell

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/futures-rs#361]
Right now, a number of communication structures require a mutex to store the task handle. It would be nice if there were some kind of atomic Task cell that could be used instead.

I'm not sure if this is possible (most likely not easy), but I am creating the issue to track the feature request.

**Comment by alexcrichton** [comment]
Currently available at https://github.com/carllerche/futures-broadcast/blob/master/src/atomic_task.rs, we can probably clean up slightly and move in here

**Comment by alexcrichton** [comment]
This is being added in https://github.com/alexcrichton/futures-rs/pull/436

**Comment by carllerche** [comment]
I didn't actually expose it yet.

**Comment by alexcrichton** [comment]
Provided in https://github.com/alexcrichton/futures-rs/pull/550
