### ISSUE TITLE
Misleading "Sized not implemented" error when failing to import Future trait

### ISSUE THREAD

**Issue by nipunn1313** [alexcrichton/futures-rs#362]
Hello,

code snip:
```rust
extern crate futures;

//use futures::Future;

pub fn outer() -> i64 {
    let x = inner::get_future().map(|x| x).boxed();
    5
}

mod inner {
    use futures::{BoxFuture, Future};
    use futures::future;

    pub fn get_future() -> BoxFuture<(), ()> {
        future::ok(()).boxed()
    }
}
```

This code fails compilation with this misleading error:
```
error[E0277]: the trait bound `futures::Future<Error=(), Item=()> + Send + 'static: std::marker::Sized` is not satisfied
 --> src/lib.rs:6:33
  |
6 |     let x = inner::get_future().map(|x| x).boxed();
  |                                 ^^^ the trait `std::marker::Sized` is not implemented for `futures::Future<Error=(), Item=()> + Send + 'static`
  |
  = note: `futures::Future<Error=(), Item=()> + Send + 'static` does not have a constant size known at compile-time

error: no method named `boxed` found for type `futures::Map<futures::Future<Error=(), Item=()> + Send + 'static, [closure@src/lib.rs:6:37: 6:42]>` in the current scope
 --> src/lib.rs:6:44
  |
6 |     let x = inner::get_future().map(|x| x).boxed();
  |                                            ^^^^^
```

However, if you uncomment the "use futures::Future", things compile fine.

I believe the issue is that you can't use the "map" function on Future unless you import the Future trait, but this error message doesn't explain that at all. It definitely sent @rbtying and me on a wild compiler error goose chase. Was definitely expecting the more standard "Did you mean to import futures::Future?" error message.

Thanks!

**Comment by alexcrichton** [comment]
Thanks for the report! Unfortunately I think this may be a compiler bug so I've [moved upstream](https://github.com/rust-lang/rust/issues/35976). I'm gonna close in favor of that.

I know I've definitely fallen prey to this wild goose chase before!
