### ISSUE TITLE
Proposal: Futures must be run by `Executor`s

### ISSUE THREAD

**Issue by liranringel** [alexcrichton/futures-rs#368]
Currently `Future`s could be run by an `Executor`, and could also not be.
I'd suggest that `Future`s must be run by an `Executor`, and that the `Executor` will be saved in thread-local storage so a future's `poll` implementation could spawn new tasks.
The api could look like:
`executor::spawn(future);`

Motivation:
Futures are often wrapped in other futures, so a future might not be polled if the wrapping future does not poll it. Yet some implementations assume that the future will be polled.
@dwrensha presented an example in issue #330. In summary, `Shared` implementation assumes that `poll` will be called, but it could also not be called, what will eventually lead to deadlock for the other `Shared` clones.

If `Shared` could spawn a new `Future`, that will unconditionally be polled when its `Task` is unparked, it would solve #330 and probably other issues too.

**Comment by dwrensha** [comment]
> Yet some implementations assume that the future will be polled.

My current opinion is that such futures (of which `Shared` is an example) should be considered buggy. See https://github.com/alexcrichton/futures-rs/issues/330#issuecomment-274282717.

**Comment by carllerche** [comment]
I'm currently experimenting with an ["executor" trait](https://github.com/carllerche/futures-spawn/blob/master/src/lib.rs#L21-L29). One difficulty is that not all executors can handle all possible futures. For example, `Future` does not require `Send`, but a thread pool executor can only schedule futures bound with thread. This is why I have the `Spawn` trait be generic over the future type.

The problem with using a thread local to store a handle to the executor is that this would not be possible w/ the strategy that the `Spawn` trait uses. It also would not be possible to capture the limitations of the current executor.

**Comment by alexcrichton** [comment]
While I do think that this may be useful, I agree with @dwrensha that this likely isn't the best solution to #330.

**Comment by alexcrichton** [comment]
I'm going to close this for now as it's effectively what's already happening (executors drive futures), in parallel @carllerche is exploring an executor trait, and in the meantime we've solved #330 via other means.
