### ISSUE TITLE
Lock a resource during the whole time the task is running

### ISSUE THREAD

**Issue by karinqe1** [alexcrichton/futures-rs#369]
I have a resource that is going to get passed around like 
`resource.foo().and_then(|resource| resource.bar())` where `foo` and `bar` return `Future<Item=Resource, Error=MyError>`.

I don't want anything else to be able to use that resource until that task finishes, so I can't just lock the resource during polling - then it would still be possible to use it.

I originally wanted `Resource` to equal `MutexGuard<'a, ActualResource>`, but then I realized that I actually need a static lifetime - both because I currently have to return a Box (at least until 'impl Trait' is stable) and because I'm eventually spawning it with tokio's `Handle::spawn` which requires a static lifetime. My next idea was to have the resource stored in an `Option`, take it out when I want some futures to use it and then manually put it back again. However, this would mean that the users of my API would have to manually put the resource back (and things would break if they didn't), and I'd also have to actually return `Future<Item=Resource, Error=(Resource, MyError)>`, because some of the errors can be recovered from. I'm thinking about working around this by sending it back via a channel in `Drop`, but that sounds like a rather ugly hack.

Is there some solution to this?

**Comment by alexcrichton** [comment]
One possible solution is task-local data with the `task_local!` macro perhaps?

**Comment by karinqe1** [comment]
Is there some example of how to use it?

**Comment by alexcrichton** [comment]
It's used in basically the same way as thread locals in the standard library -- https://doc.rust-lang.org/std/thread/struct.LocalKey.html

**Comment by karinqe1** [comment]
I tried looking at it, but I still don't understand how to use it this way. As far as I can tell, thread_local does exactly the opposite of what I want - it gives each thread a separate and independent copy. What I want is to assure that the resource can be used on only one task and nowhere else. Is there some reasonably simple example of task_local?

**Comment by alexcrichton** [comment]
Using something like `task_local!` doesn't hand a copy to each task, it requires explicit initialization. Typically for a resource like this the value would be `RefCell<Option<T>>` or something like that. It starts out blank and then it's filled in later.

**Comment by dwrensha** [comment]
> I'm thinking about working around this by sending it back via a channel in Drop, but that sounds like a rather ugly hack.

I've used this approach several times, and I don't think it's ugly. You could have something like:

```rust
struct Resource {
    inner: Option<(ActualResource, oneshot::Sender<ActualResource>)>,
}

impl Drop for Resource {
    fn drop(&mut self) {
        let (r, tx) = self.inner.take().unwrap();
        tx.complete(r);
    }
}
```

**Comment by alexcrichton** [comment]
This has been pretty quiet for awhile so I'm going to close this.
