### ISSUE TITLE
Integration with GPU Streams/Queues

### ISSUE THREAD

**Issue by botev** [alexcrichton/futures-rs#371]
I don't think that this is going to be on your agenda, but for certain HPC tasks if we have an easy way of interfacing futures with the native GPU Streams/Queues that would be very nice. As far as I understand essentially you will need a different `pool` as well as a way to register the callbacks to the underlying stream for when the work there is done to call the `poll` in the rust future.

**Comment by alexcrichton** [comment]
I'm not really familiar with gpus much, but would be awesome to explore!

**Comment by botev** [comment]
So Nvidia cards have Streams, AMD call them queue, essentially it an async computational dispatchers (e.g. what a threadpool wrapped in futures is doing) with some hardware implementation.

**Comment by carllerche** [comment]
This could probably be implemented as a separate library. If you need help doing so, the [Tokio Gitter](https://gitter.im/tokio-rs/tokio) has people who can help write a custom futures lib.

**Comment by alexcrichton** [comment]
Ok I'm going to close this issue for now as there's probably not going to be much integration in this repo itself, but if any assistance is needed please feel free to reach out!
