### ISSUE TITLE
wait() with timeout

### ISSUE THREAD

**Issue by tekjar** [alexcrichton/futures-rs#376]
Hi,

https://docs.rs/futures/0.1.9/futures/future/trait.Future.html#method.wait

If I understand correctly, `wait` will block indefinitely when future isn't complete. I'm using mpsc bounded channels and my requirement is that `Sender.wait()` should block if the buffer is full but with a timeout. After timeout, `wait` should return an errror. Is this possible?

**Comment by alexcrichton** [comment]
This should indeed be possible!

If you take a look at the implementation of [`Spawn::wait_future`](https://github.com/alexcrichton/futures-rs/blob/c33c74020f24865c9152811a00e46fa50b53c05c/src/task_impl/mod.rs#L314-L328) it should be relatively easy to write your own version, such as this: https://gist.github.com/alexcrichton/871b5bf058a2ce77ac4fedccf3fda9c9

**Comment by tekjar** [comment]
@alexcrichton Oh thanks a lot :). Does it make sense to include this functionality directly in `futures-rs`?

**Comment by alexcrichton** [comment]
Yeah I've considered how to do so in the past. Dealing with the `Spawn` return value is kinda unfortunate, but it'd be easy enough for us to add `wait_future_timeout` to `Spawn`, it's just a bit of a hefty method name!

I could personally go either way on this.

**Comment by cjubb39** [comment]
Including this would make it easier to convert the codebase I'm working from `std::sync::mpsc` to Futures.  Am definitely in favor of having a `wait_timeout` capability

**Comment by alexcrichton** [comment]
I'm goign to close this in favor of https://github.com/alexcrichton/futures-rs/issues/198 as I think it basically boils down to the same thing, runtimes executing futures need the ability to block for a small period of time.
