### ISSUE TITLE
Question: unreliable behavior spawning on cpupool

### ISSUE THREAD

**Issue by Nimamoh** [alexcrichton/futures-rs#378]
Hello,

I've been using thread pool on one of my project. However, I came across an unreliable behavior. A detailed description of what I observed is depicted here on [stackoverflow](https://stackoverflow.com/questions/41950097/rust-futures-cpupool-inconsistent-behavior-explanations?noredirect=1#comment71096875_41950097)

Maybe I'm not using the lib correctly, can someone give me a hand?

**Comment by alexcrichton** [comment]
Ah so it looks like you're dropping a `CpuFuture`? Right now that's interpreted as "cancel the computation", so you'll want to either call `.forget()` or persist the future to ensure that it's not canceled.

**Comment by Nimamoh** [comment]
Ok, thanks for your help.
After keeping track of the producer future, I've been able to run this example correctly.
I assume that calling `.forget()` on a real application is not an option as it'll surely lead to memory leak.

**Comment by alexcrichton** [comment]
Oh note that `.forget()` doesn't actually leak memory, it just allows the computation to continue running if the `CpuFuture` is dropped.
