### ISSUE TITLE
Shadow `Sink::send` on `mpsc::Sender` with an inherent method that takes `&self`

### ISSUE THREAD

**Issue by abonander** [alexcrichton/futures-rs#380]
Essentially, duplicate [`UnboundedSender::send()`](https://docs.rs/futures/0.1.10/futures/sync/mpsc/struct.UnboundedSender.html#method.send). Comparing the implementations of `Sender` and `UnboundedSender`, this seems doable, though it might require duplicating some of the details (having an alternative of `do_send()` which takes `&self`).

**Comment by alexcrichton** [comment]
Thanks for the report! This is covered by https://github.com/alexcrichton/futures-rs/issues/261, though, so I'm going to close in favor of that.

**Comment by jonhoo** [comment]
Actually, this seems somewhat different to #261. There, it is about which `send` is used for an `UnboundedSender`. Here, is is about providing an `fn send(&mut self)` method for a *regular* `Sender`, no?

**Comment by carllerche** [comment]
I don't believe that this is actually possible. `UnboundedSender` can potentially take `&self` because it never has to handle back pressure (by virtue of being unbounded). Handling back pressure correctly basically requires `&mut self`.

**Comment by abonander** [comment]
Yeah I realized that it wasn't really doable so I just let it go.

**Comment by jonhoo** [comment]
Adding a `synchronous_send(&mut self)` still seems like something that would vastly improve the ergonomics of future channels though. The current "consume and replace" can be quite annoying to work with, especially when working futures into a pre-existing codebase.

**Comment by alexcrichton** [comment]
@jonhoo unfortunately though I don't think such an operation can be implemented by all channels?

**Comment by alexcrichton** [comment]
Oh wait nevermind, it definitely can be!

@jonhoo would https://github.com/alexcrichton/futures-rs/issues/389 be an issue you'd be interested in? There I think there's definitely a mode of operation we could enable where you spawn a sink and then get synchronous functions that block the current thread.

**Comment by jonhoo** [comment]
Hmm, yes, #389 seems like it could work towards something like this. Unfortunately I don't know that I have the spare cycles to take that on at the moment :/
