### ISSUE TITLE
Shared and join_all

### ISSUE THREAD

**Issue by stuhood** [alexcrichton/futures-rs#381]
Hey gang! Thanks for the library.

I have a reproducible case in `0.1.10` where I _think_ that a `JoinAll` consuming `Shared` futures `a` and `b` encounters an `Err` in `a` which leaves `b` in a state where `wait` hangs.

I've tried a bunch of angles to reduce this to a testcase, and will continue to attempt to reduce tomorrow. Just posting this now in case the example calls anything to mind.

**Comment by dwrensha** [comment]
Eek! I was hoping that with https://github.com/alexcrichton/futures-rs/pull/305 and https://github.com/alexcrichton/futures-rs/pull/373 we had stamped out this kind of problem.

> I have a reproducible case in `0.2.10`...

I'm assuming you mean futures-rs version `0.1.10`?

**Comment by stuhood** [comment]
Yes, apologies: `0.1.10`.

**Comment by alexcrichton** [comment]
Definitely sounds suspicious! Nothing comes to mind myself, but @stuhood if you've got a reproduction it'd be great to dig into that! Even a large reproduction would be helpful for drilling down.

**Comment by dwrensha** [comment]
@stuhood, your mention of `Future::wait()` makes me a little bit suspicious, as that method can cause deadlocks if not used carefully. Could you explain a bit more in depth what your program looks like? Are there multiple threads? How many clones does `b` have? How are you sure that `b` actually does resolve?

**Comment by stuhood** [comment]
@dwrensha : There is a main thread that launches DAGs of `Shared` futures onto a `CpuPool`, then `join_all(..).wait()`s on them, and that thread is successfully exiting. But all `Shared` futures are created via a method that records them (for dependency tracking purposes). After the main thread finishes waiting for the roots, it walks through the list of nodes in the DAG and `waits` on their `Shared` instances in order to visualize them.

So, worst case, I should be pretty well set up to visualize in order to track this down!

**Comment by dwrensha** [comment]
Interesting! So the DAG has something like `a.join(b)`, and the main thread observes the failure of `a`. How do you know that `b`'s underlying computation has finished? Note that if `b` is a `Shared` and `b1 = b.clone()`, then dropping/cancelling `b` has no direct bearing on the outcome of `b1.wait()`. To cancel the underlying computation you would need to drop all clones of the `Shared`.

**Comment by stuhood** [comment]
Is there a non-blocking way to inspect a `Shared` value for completion? I know the method name isn't available here, but `com.twitter.util.Future.poll` returns an Option representing whether the Future has completed, and it seems that that should be possible with `Shared` as well.

**Comment by dwrensha** [comment]
Currently, the only way to check for completion would be to call [`Future::poll()`](https://docs.rs/futures/0.1.10/futures/future/trait.Future.html#tymethod.poll)  on the `Shared`. This could be somewhat awkward, because you need to make sure that the `poll()` call takes place within the context of a `Task`. We could maybe add a `futures::task::ignoring()` function to make this more ergonomic (and this is perhaps a point in favor of switching futures-rs to use explicitly-passed tasks, as in https://github.com/alexcrichton/futures-rs/pull/374, so that you could do `b.poll(task::empty())`).

We could also consider adding a `Shared::is_done()` method. However, I wonder whether using `Shared` is actually the best approach for you particular problem. Perhaps it would make more sense for you to record the finished values in plain `Arc<Mutex<Option<T>>>` slots?

**Comment by stuhood** [comment]
I've managed to reduce this to exactly the case in the original description, BUT, it looks like ordering matters. When `join_all` on `a==Err` and `b==?`, and `a` is in the first slot of the join, latter `wait()`ing on `b` will block forever. Swapping `a` and `b` in the join does not reproduce.

----

@dwrensha :

> How do you know that b's underlying computation has finished?

By adding Debug and dumping the states of nodes in the graph, I've determined that the node calling join_all on `a` and `b` was the only Future that had a dependency on `b`, so no other combinator had reason to `poll` `b`.

My understanding of `wait()` though is that if the main thread ends up being the first to `poll` or `wait`, then it will be the one to execute the work it represents... in this case, a sub-DAG of `Waiting` `Shared` futures. I could definitely be understanding, because I have a lot of previous assumptions.

> However, I wonder whether using Shared is actually the best approach for your particular problem. Perhaps it would make more sense for you to record the finished values in plain Arc<Mutex<Option<T>>> slots?

In this graph, multiple nodes (and thus Futures) may be waiting on a particular dependency that has hasn't finished executing... I think that using a Mutex would mean having them busywait or block.

**Comment by stuhood** [comment]
The local subgraph looks like this:

![reduced](https://cloud.githubusercontent.com/assets/46740/22568472/d1ebfd16-e948-11e6-8108-78f05bf8ff8f.png)

The main thread is then `wait()`'ing on `b` and blocking forever.

**Comment by stuhood** [comment]
Immediately before blocking on a clone of `b`, the main thread observes:
```Shared { id: 2, Waiting(Unparker(true, []), ..) }```

Presumably the two other clones were 1) the initial `Shared` that was stored in the DAG, 2) the clone used in the `join_all`, which is now dropped.

**Comment by stuhood** [comment]
Alright, sorry for the false alarm guys. It looks like this was `wait()` being called under a lock in the DAG, which (since the entire subgraph had not begun running due to the cancelation) recursively triggered another lookup on the DAG while under the lock.

`wait()` is definitely error prone: I've opened #383 to add `peek()`, which is extremely useful in this case and others.
