### ISSUE TITLE
surprising interaction between task-local data and Shared futures

### ISSUE THREAD

**Issue by dwrensha** [alexcrichton/futures-rs#382]
Consider the following program, which constructs a single `Foo` future and then repeatedly polls it:

```rust
#[macro_use]
extern crate futures;

use futures::{Async, Future, Poll, future, task};
use std::thread;
use std::time;
use std::sync::mpsc;
use std::cell::Cell;

struct Foo {
    tx: mpsc::Sender<task::Task>,
}

impl Foo {
    fn new() -> Self {
        let (tx, rx) = mpsc::channel::<task::Task>();
        thread::spawn(move || {
            loop {
                match rx.recv() {
                    Ok(t) => {
                        thread::sleep(time::Duration::new(0, 10000));
                        t.unpark();
                    }
                    Err(_) => break,
                }
            }
        });

        Foo { tx: tx, }
    }
}

task_local! { static TASK_NUMBER: Cell<u32> = Cell::new(0) }

impl Future for Foo {
    type Item = ();
    type Error = ();

    fn poll(&mut self) -> Poll<Self::Item, Self::Error> {
        TASK_NUMBER.with(|tn| println!("poll(). task number = {}", tn.get()));
        let _ = self.tx.send(task::park());
        Ok(Async::NotReady)
    }
}

fn main() {
    let foo1 = Foo::new().shared();
    let foo2 = foo1.clone();

    thread::spawn(move || foo1.wait().unwrap());

    let f1 = future::lazy(move || {
        TASK_NUMBER.with(|tn| tn.set(1));
        foo2
    });
    f1.wait().unwrap();
}
```

It might seem reasonable to assume that `poll()` would always print out the same task number. However, it instead nondeterministically switches between 0 and 1.

Could this kind of thing cause problems for real usages of task-local data?

**Comment by dwrensha** [comment]
In other words, what good is task-local data if a future cannot assume that it's always run on the same task?

**Comment by alexcrichton** [comment]
Yeah I think task locals aren't that useful in generic combinators and generic libraries, but rather moreso for libraries with concrete implementations and usages (in theory).

You could kinda say the same thing about thread locals I guess? In that thread locals are still useful even though your function could run on any thread. One difference though is that you have a way to pin yourself to a thread (e.g. use `Rc`) whereas there's currently no way to pin yourself to a task.

**Comment by dwrensha** [comment]
After https://github.com/alexcrichton/futures-rs/pull/442, the above program deterministically prints out a single task number repeatedly, which is more in line with my expectations.
