### ISSUE TITLE
mpsc::Sender should be able to send the data from non-async thread

### ISSUE THREAD

**Issue by tailhook** [alexcrichton/futures-rs#389]
I.e. it should have a method `Sender::try_send` which returns error without parking current task (because there is no current task). Similarly to `UnboundedSender::send` but for bounded channel.

**Comment by alexcrichton** [comment]
The main way that this would be done would be through `executor::spawn` and like we have `poll_future` and `poll_stream`, we should probably temporarily at leaset add `poll_sink_complete` and `sink_start_send` (or something like that). That I believe is at least the bare bones necessary here.

**Comment by tailhook** [comment]
Hm, I assumed that exposing `do_send(Some(msg), false)` would work, no? The internals are pretty complex to figure that out at a glance.

**Comment by carllerche** [comment]
As I recall, @tailhook is correct in his analysis. There needs to be a way to try to send a value without a task handle. do_send is most likely the right way (but I am not looking at the code ATM).

Being able to try to send without a task is required to be able to respect the channel capacity. If a task is implicitly created for each send then the channel is effectively unbounded. 

We need this feature in tokio-proto to correctly support backpressure.

**Comment by alexcrichton** [comment]
Oh right yeah we need to support this, I was just saying we should do it for all sinks, not just channels.

**Comment by tailhook** [comment]
I don't think it's possible to do for all sinks. I even think that the whole idea of sink is to be executed in the context of the future, so it doesn't make much sense.

BTW, I've solved my own problem with an unbounded channel and a counter. This is even a little bit better because it allows introspection of the size of the queue.

**Comment by alexcrichton** [comment]
@tailhook the only requirement is a task, right? That's what `executor::spawn` sets up?

**Comment by tailhook** [comment]
@alexcrichton yes. But I'm not sure why you're asking. Do you want some method like `Future::wait()`, for  sending? While it might work, I don't have any use cases for that from the top of the head.

**Comment by alexcrichton** [comment]
Ah sorry so what I'm envisioning is an extension to the [`Spawn`](https://docs.rs/futures/0.1.10/futures/executor/struct.Spawn.html) API, like:

```rust
impl<S: Sink> Spawn<S> {
    fn poll_complete_sink(&mut self, unpark: Arc<Unpark>)
                          -> Poll<(), S::SinkError>;
    fn wait_complete_sink(&mut self) -> Result<(), S::SinkError>;

    fn start_send_sink(&mut self, unpark: Arc<Unpark>, item: S::SinkItem)
                       -> StartSend<S::SinkItem, S::SinkError>;
    fn wait_send_sink(&mut self, item: S::SinkItem)
                      -> Result<(), S::SinkError>;
}
```

That way you could use an arbitrary sink off a task (by creating a new task basically).

I don't mean to say though that we *shouldn't* add a `mpsc::Sender`-specific method. Just noting that we could generalize this as well to not only senders but all sinks.

**Comment by alexcrichton** [comment]
I've opened https://github.com/alexcrichton/futures-rs/pull/406 with my thinking.

**Comment by carllerche** [comment]
That works, I'd still like mpsc to have `try_send` to avoid the `Arc` :)
