### ISSUE TITLE
Consider adding `Stream::collect_bytes`

### ISSUE THREAD

**Issue by alexcrichton** [alexcrichton/futures-rs#390]
Some I/O applications are starting to represent streaming bodies as a `Stream` where each item is a chunk of bytes. For convenience, though, it might be nice to have a combinator such as:

```rust
trait Stream {
    fn collect_bytes(self) -> impl Future<Item = Vec<u8>, Error = Self::Error>
        where Self::Item: AsRef<[u8]>,
    { /* ... */ }
}
```

**Comment by luser** [comment]
The explicit motivator for this was [`hyper::Body`](https://hyper.rs/hyper/master/hyper/struct.Body.html), which is a `Stream` with `Item = [hyper::Chunk](https://hyper.rs/hyper/master/hyper/struct.Chunk.html)` where `hyper::Chunk` is `Deref<[u8]>` and `AsRef<[u8]>`. I can imagine that working with `Stream`s whose items are effectively byte slices is going to be pretty common for users of tokio, and often it's necessary to process the entire stream contents once available.

**Comment by carllerche** [comment]
I wonder if this should go on `Stream` itself, or perhaps there should be a separate (sub?) trait that has additional features specifically for streams of byte chunks.

For example, there could be additional fns providing the total size of the payload (if known), and there could be more than helper function, `collect_bytes` could allocate a buffer internally, `collect_bytes_into` (naming tbd) could take an existing buffer, etc...

Perhaps this functionality should live outside of the `futures` crate.

**Comment by seanmonstar** [comment]
It being tied directly to "bytes" sounds odd in the futures crate. It could be generic, just played with this in a playpen, just a minimal version that isn't yet async:

```rust
trait Stream {
    // ...

    // name as 'concat' isn't important part
    fn concat<T, I>(&mut self, fill: T) -> SomeReturnTypeThatImplsStream
    where Self::Item: IntoIterator<Item=I>,
          T: Extend<I>,

    {
        // ...
    } 
}
```

This works to fill up a `Vec<u8>` or other container when receiving a stream of `Vec`s (or stream of `IntoIterator<Item=u8>`, or a `Vec<Entry>` when receiving a few entries at a time. Or a HashMap, etc.

**Comment by stuhood** [comment]
It would be a true test of specialization if a completely generic form of `flatten` worked here.

**Comment by seanmonstar** [comment]
Thanks to specialization, this will will use the faster `Vec::extend_from_slice` in more recent Rust versions, so flattening (an excellent name!) would use the fast route for bytes any ways.

**Comment by scottlamb** [comment]
This might be better if done at a higher level. Going with the hyper case for a moment, it'd be nice to use the `Content-Length` (if present) to do `Vec::with_capacity` rather than growing the vector as needed. Also, folks probably want a limit on the number of bytes they'll collect in this fashion, and it'd be nice to use the `Content-Length` for that as well if possible, to avoid collecting the limit then throwing it away.

**Comment by alexcrichton** [comment]
I definitely agree that the *perfect* solution here may not exist best at the `Stream` layer, but then again `collect` is rarely perfect. I don't think we necessarily have to shy away from imperfect combinators if they're still quite convenient to use. For example in sccache's use case the performance is *absolutely critical*, so a slightly-less-efficient implementation would be totally fine.

**Comment by luser** [comment]
> For example in sccache's use case the performance is absolutely critical, so a slightly-less-efficient implementation would be totally fine.

I'm assuming you meant to write **not** absolutely critical here. :)

**Comment by alexcrichton** [comment]
Oh oops, sorry yes I did indeed mean *not* critical!

**Comment by alexcrichton** [comment]
Closed by https://github.com/alexcrichton/futures-rs/pull/394
