### ISSUE TITLE
"error: reached the recursion limit during monomorphization (selection ambiguity)" with chunks

### ISSUE THREAD

**Issue by conradev** [alexcrichton/futures-rs#393]
Compiling the following code fails with:

```
error: reached the recursion limit during monomorphization (selection ambiguity)
```

```rust
extern crate futures; // 0.1.10

use futures::{stream, Stream, Future};
use futures::sync::oneshot;

fn main() {
    let (tx, rx) = oneshot::channel(); // future to fetch a collection of objects
    tx.complete((0..200).collect());

    rx.map(|l: Vec<usize>| stream::iter(l.into_iter().map(|i| Ok(i))))
        .flatten_stream()
        .chunks(50)
        .map(|i| Ok(i)) // do work with batch of objects
        .buffer_unordered(5)
        .collect();
}
```

```
rustc 1.15.0 (10893a9a3 2017-01-19)
```

The idea here is to batch process a bunch of objects. If I remove the `chunks(50)` line, the code successfully compiles 😮

**Comment by dwrensha** [comment]
Possibly related to #367.

**Comment by conradev** [comment]
Some more info:
- This happens all the way back to `0.1.3`, when `Chunks` was introduced.
- I resolved the issue for now by waiting synchronously for the collection of objects, and then making the stream, removing the need for the `map` and `flatten_stream`.

**Comment by alexcrichton** [comment]
I wonder if this may be a bug in the compiler? We've caught some before through this library. It'd be helpful to reduce the library to the bare bones though to see what's necessary to trigger the bug.

**Comment by alexcrichton** [comment]
Ok I've reduced it at https://github.com/rust-lang/rust/issues/40003

**Comment by goffrie** [comment]
I suppose this issue can be closed now?
