### ISSUE TITLE
Adapters should overwrite `wait`

### ISSUE THREAD

**Issue by ticki** [alexcrichton/futures-rs#397]
`wait` (and friends) can potentially be much faster than looping (like in lock, which can use the `futex` syscall), but the adapters (like `Map`) don't care. They simply fallback to the default implementations, while they could forward the calls to the inner future.

Here's an example: `Map` [only implements `poll`](https://docs.rs/futures/0.1.10/src/futures/future/map.rs.html#28), this mean that if you use `mutex.lock().map(|x| blah).wait()`, there is a quite significant performance tradeoff, as the lock simply then acts as a spinlock by repeatedly calling `poll`, instead of using the `wait` overwritten my custom lock future might have.

So adapters like `Map` should overwrite `wait`. In this case, it should look something like:

```rust
fn wait(self) -> Result<Self::Item, Self::Error> where Self: Sized {
    self.inner.wait().map_ok(self.map)
}
```

It is needed for

- [ ] `Map`
- [ ] `MapErr`
- [ ] `OrElse`
- [ ] `AndThen`
- [ ] `Then`
- [ ] `Fuse`
- [ ] `Flatten`
- [ ] `CatchUnwind`

(possibly incomplete list)

**Comment by nikomatsakis** [comment]
See also #360

**Comment by alexcrichton** [comment]
I'm not sure that this is an entirely great idea because this means that each future in a chain would create a separate task (as the default implement of `wait` creates a separate task). Preserving those precise semantics (one wait == one task) may be quite tricky.

**Comment by ticki** [comment]
huh, `wait` spawns a task?

It isn't documented AFAICS. What code would break without that guarantee?

**Comment by alexcrichton** [comment]
Yes, wait [spawns a task](https://github.com/alexcrichton/futures-rs/blob/74700604fae154bbef176973285d0a8013e21d53/src/future/mod.rs#L275), and while not documented I think it's wasteful/less efficient to spawn many tasks regardless of the breakage aspect.

Crates using `task_local!` will also break I believe.

**Comment by ticki** [comment]
I'm somewhat surprised by that, and I still fail to see where it could break (I mean, in theory, you could make code that breaks, but is that assumption ever used in practice?).

I would say it fails to be truely zero-cost, if it cannot use optimized waits.

**Comment by alexcrichton** [comment]
Due to the breaking semantics here I'm going to close this in favor of https://github.com/alexcrichton/futures-rs/issues/360 which I believe should have many similar benefits.
