### ISSUE TITLE
Future::poll should return a reference

### ISSUE THREAD

**Issue by Benjamin-L** [alexcrichton/futures-rs#399]
Currently, `Future::poll` returns `Poll<Self::Item, Self::Error>`, while `Future::wait` also returns `Result<Self::Item, Self::Error>`. Since `poll` borrows `self` rather than taking ownership, it is often needed to clone the item. Ideally, `poll` should return a reference to the item to avoid this issue. The alternative type signature would be:
```rust
fn poll<'a>(&'a mut self) -> Poll<&'a Self::Item, Self::Error>;
```
This could also be made as a new function to not break backwards compatibility.

**Comment by Stebalien** [comment]
Unfortunately, one usually wants the item by value. This often isn't an issue because items aren't usually stored in futures. Instead, they're computed (or fetched from somewhere else) within the body of the `poll` function and returned immediately.

If you do need to store the item, I recommend using an `Option<Self::Item>` internally instead of cloning.

**Comment by carllerche** [comment]
@Benjamin-L I believe you may be misunderstanding something. There is no need to clone right now (unless cloning is the desired behavior). Could you elaborate why you think that cloning is required. As a data point, I have been using futures a lot and have not ever cloned (again, unless I explicitly wanted to).

**Comment by Benjamin-L** [comment]
I probably am missing something. I had code that was something like this:
```rust
struct FutureImpl {
    inner: UnsafeCell<T> //T is not Copy
}

impl Future for FutureImpl {
    type Item = T;
    type Error = ();
    fn poll(&mut self) -> Poll<T, ()> {
        if done() { //a little more complicated than this
            unsafe {
               Ok(Async::Ready((*self.data.get()).clone()))
            }
        }
        else {
            Ok(Async::NotReady)
        }
    }

    fn wait(self) -> Result<T, ()> {
        while !done() {
            thread::sleep_ms(5);
        }
        unsafe {
            unsafe {
                self.data..into_inner()
            }
        }
    }
}
```

**Comment by Stebalien** [comment]
In this case, you'd probably want to use an `Option` (`UnsafeCell<Option<T>>`). In `poll()`, you'd unwrap the option the first time `done()` returns `true`.

However, you probably don't even need to implement this yourself.  From that snippet, I can't really tell what's going on but I assume that some other thread is filling in `inner`.  If so, you should probably be using a [one-shot channel](https://docs.rs/futures/0.1.10/futures/sync/oneshot/fn.channel.html).

**Comment by alexcrichton** [comment]
Thanks for the report! Unfortunately though almost all of the `futures` crate is built around having a future return a value so I don't think this will be possible to do.

I believe for your use case you may want a separate layer above the future which caches the value a future creates and then only hands out references. I believe there's a `lazycell` crate on crates.io which may be helpful in this situation as well.

**Comment by stuhood** [comment]
> I believe for your use case you may want a separate layer above the future which caches the value a future creates and then only hands out references. I believe there's a lazycell crate on crates.io which may be helpful in this situation as well.

This is also approximately what `future::Shared` does, albeit in a threadsafe fashion (ie, with an `Arc`). Optimizing the implementation and UX of `future::Shared` to make it cheap and easy to use for this case would benefit a lot of users.

(sidenote: I don't have need of a non-send `future::Shared`, but I wonder whether there is need for a version that uses `Rc`?)

**Comment by Benjamin-L** [comment]
Thanks for the advice! It turns out that the one-shot channel was perfect for this. Feel free to close this issue as it looks like it isn't actually a problem.
