### ISSUE TITLE
Confusing order of tuple returned by promise()

### ISSUE THREAD

**Issue by tomaka** [alexcrichton/futures-rs#4]
The `promise` function returns a tuple of `(Promise, Complete)`.

The `Promise` object is similar to the `Receiver` object of the channels in the stdlib, while the `Complete` object is similar to the `Sender` object.

However in the stdlib, the `channel()` function returns a tuple of `(Sender, Receiver)`.

I find it confusing that the order of what `promise()` returns is the opposite of what `channel()` returns.

**Comment by alexcrichton** [comment]
Sounds reasonable to me!
