### ISSUE TITLE
Unable to chain `mpsc` channels with `send_all`.

### ISSUE THREAD

**Issue by jonhoo** [alexcrichton/futures-rs#401]
I'll prefix this with the fact that I'm relatively new to futures-rs, so I may be completely off-base. My (simplified) use-case is that I have two channels, and I want to feed one channel into the other (i.e., pipe them). Unfortunately, it seems like this isn't possible due to the `Stream::Error` type of `mpsc;:Receiver` not implementing `Into<mpsc::SendError>` (if I'm reading the errors right).

Specifically, I expected the following code to work:
```rust
extern crate futures;

use futures::{Future, Sink, Stream};

fn main() {
    let (tx1, rx1) = futures::unsync::mpsc::channel(1);
    let (tx2, rx2) = futures::unsync::mpsc::channel(1);
    tx1.send("hello").wait().unwrap();
    tx2.send_all(rx1).wait().unwrap();
    let done = rx2.wait();
    println!("{:?}", done.collect::<Vec<_>>());
}
```
But instead the compiler complains:
```text
error[E0271]: type mismatch resolving `<futures::unsync::mpsc::Receiver<&str> as futures::Stream>::Error == futures::unsync::mpsc::SendError<&str>`
 --> src/main.rs:9:9
  |
9 |     tx2.send_all(rx1).wait().unwrap();
  |         ^^^^^^^^ expected (), found struct `futures::unsync::mpsc::SendError`
  |
  = note: expected type `()`
  = note:    found type `futures::unsync::mpsc::SendError<&str>`

error: no method named `wait` found for type `futures::sink::SendAll<futures::unsync::mpsc::Sender<&str>, futures::unsync::mpsc::Receiver<&str>>` in the current scope
 --> src/main.rs:9:23
  |
9 |     tx2.send_all(rx1).wait().unwrap();
  |                       ^^^^
  |
  = note: the method `wait` exists but the following trait bounds were not satisfied: `futures::unsync::mpsc::SendError<_> : std::convert::From<()>`,`futures::sink::SendAll<futures::unsync::mpsc::Sender<&str>, futures::unsync::mpsc::Receiver<&str>> : futures::Future`, `futures::sink::SendAll<futures::unsync::mpsc::Sender<&str>, futures::unsync::mpsc::Receiver<&str>> : futures::Stream`

error: aborting due to 2 previous errors
```
This problem will (perhaps obviously) also happen if you are mixing `sync::mpsc` and `unsync::mpsc`. I thought I'd mention it so that that use-case is also considered when coming up with a fix.

In case it is of interest, and might have a way around this problem, my "real" use-case is that I have a `std::iter::Peekable`, and want to send each value from that iterator onto a `sync::mpsc::Sender`. However, I cannot simply use `stream::iter`, because my `map` needs access to the *next* element of the iterator (hence the need for a `Peekable` in the first place). I'm not trying to achieve this by using an `unsync::mpsc::channel` that is piped into the target channel. But of course this triggers the issue above. Suggestions for better approaches are welcome!

**Comment by pierre-l** [comment]
I'm quite new to futures-rs too, so I may be completely off-base too, but isn't this exactly why the map_err function exists?

**Comment by jonhoo** [comment]
I tried fiddling with `map_err`, but couldn't find a way to create a `mpsc::SendError` (it has private fields and no public constructor), and thus I can't make them match up.

**Comment by alexcrichton** [comment]
Ah yeah right now the way to do this would be:

```rust
tx.send_all(rx.map_err(|_| panic!()))
```

@jonhoo does that work for you?

In general the receiver's error type will never be instantiated, so the closure above is never run. The `panic!` just tells the compiler "please fill in a value here" so it'll change the error type at will.

**Comment by alexcrichton** [comment]
Oops didn't mean to close.

**Comment by jonhoo** [comment]
So I guess `unreachable!()` is really what we should put there then. It's an unfortunate hack, but works for now, thanks!

I actually ended up using this hacky solution instead:
```rust
let mut tx = Some(tx);
while let Some(x) = iter.next() {
    // code that uses x and iter.peek()
    match tx.take().unwrap().send(p).wait() {
        Ok(tx_again) => {
            tx = Some(tx_again);
        }
        Err(_) => {
            unreachable!();
        }
    }
}
tx.take().unwrap().flush().wait().unwrap();
```

**Comment by alexcrichton** [comment]
That should do it! I think you can even elide the `Option` layer around `tx` in that example?

**Comment by jonhoo** [comment]
Ah, yes, you're right. I forgot that it's okay to re-assign to a mutable variable after moving out of it.

**Comment by alexcrichton** [comment]
Ok cool, in that case sounds like this is a solved issue, so closing.

**Comment by jonhoo** [comment]
Hmm.. So the solution is
```rust
tx.send_all(rx.map_err(|_| unreachable!()))
```
That seems kind of dirty, but I guess it's fine?

**Comment by alexcrichton** [comment]
Yeah we definitely want to improve the story around errors there, it's hopefully not the solution forever!
