### ISSUE TITLE
Futures without error case.

### ISSUE THREAD

**Issue by ticki** [alexcrichton/futures-rs#416]
Currently, futures evaluates to `Result<T, E>`, but a more general approach would be simply `T`.

Why? Futures can be used for things like locks.

**Comment by carllerche** [comment]
This has been discussed. The issue right now is the lack of trait aliasing. It is impossible to set `IoFuture<T> = Future<Result<T, io::Error>>`. Given that having errors is the majority case by far, the current API was opted for in exchange for some inconvenience when there really aren't any errors.

For example, you can set the error type to be `Void` or `!` once that lands.

In general though, not having an error case is a very very small percentage of the time, so I would be interested in hearing why your case doesn't need an error.

**Comment by alexcrichton** [comment]
To add to what @carllerche mentioned, there's also questions about, for example:

* Currently `join` is special-cased to return quickly on an error, this would not be possible with `Future<T>` vs `Future< T, E>`
* In practice 99% of futures right now are intended for I/O backed futures (e.g. with Tokio), and baking it in directly to the trait is far more ergonomic (for the time being)


I'd personally like to explore this at some point in the future, especially if we consider moving `Future` into the standard library. Currently though I don't think we're quite at the point where we can optimally leverage `Future<T>` and still satisfy the rest of the ecosystem around futures right now.

**Comment by Stebalien** [comment]
@ticki while I agree in principal (it feels icky)...

> Futures can be used for things like locks.

...most locks can fail due to poisoning.

However, non-failing futures (or streams) could be useful for, e.g., event-based programming:

```rust
let change_handler = my_object.on_change().for_each(|my_object, event| ...));
```

**Comment by carllerche** [comment]
I'm going to close the issue for now. At some point in the future (when trait aliases or other required lang features land), we can reopen investigating removing the associated error type.
