### ISSUE TITLE
Add an API for calling `poll_cancel` off task

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/futures-rs#419]
There generally should be some way to do this (on `oneshot` or any other type w/ `poll_cancel`) as it is common to use these types to feed data into the task system from external sources.

**Comment by mjkillough** [comment]
There is some related discussion on #317.

I would find this feature useful, as I am using `oneshot` to send data from a synchronous thread into tasks in my event loop. (The event loop effectively queues work on the separate thread, but not in a way that maps to `futures-cpupool`. The tasks in the event loop can request that the separate thread listen on a queue and send any popped value through the `oneshot`. [The code is here](https://github.com/mjkillough/rust-asgi-server/blob/master/src/channels/reply_pump.rs) if you're interested). The synchronous thread is a busy-loop and I'd like to check if any of the `oneshot`s have been cancelled each loop, to avoid the thread doing more work than necessary. I am not worried about the `oneshot` saying that it isn't cancelled and then having the `oneshot` be cancelled later: it'll get tidied up in the next iteration of the loop after it's cancelled.

**Comment by rphmeier** [comment]
I did this with a little hack that seems to work: https://github.com/paritytech/parity/blob/45c0a971426f83da7dc0a9772e426b13f147f69a/ethcore/light/src/on_demand/mod.rs#L337

But I don't know if it's technically correct

**Comment by carllerche** [comment]
I think that technically works. Calling wait makes me a bit uneasy but it
should never actually block. There will be allocation overhead but that
should go away in the future.
