### ISSUE TITLE
[Question]Why CpuPool pool my future only once

### ISSUE THREAD

**Issue by redtankd** [alexcrichton/futures-rs#421]
After reading the document https://tokio.rs/docs/going-deeper/tasks/ , I think CpuPool would complete a Future. But the below function is blocked and Myfuture is never repoll. Is my understanding about the document wrong?

```rust
#[test]
fn test() {
    struct Myfuture {
        ok: bool
    }

    impl Future for Myfuture {
        type Item = ();
        type Error = ();

        fn poll(&mut self) -> Poll<Self::Item, Self::Error> {
            
            if self.ok {
                println!("\nMyfuture: I am ready");
                return Ok(Async::Ready(())); 
            } else {
                println!("\nMyfuture: I am not ready");
                self.ok = true;
                return Ok(Async::NotReady);
            }
        }
    }

    let pool = CpuPool::new(2);
    pool.spawn(Myfuture{ ok: false }).wait().unwrap();
}
```

**Comment by alexcrichton** [comment]
Thanks for the report! You may want to preuse the [`Future::poll` documentation](https://docs.rs/futures/0.1.11/futures/future/trait.Future.html#tymethod.poll) as I think it may help clear this up.

The tl;dr; is that if `NotReady` is returned then it's the responsibility of the future to at some point call `task::park` and then unpark that handle when it's ready to make progress, the future won't be automatically polled.

**Comment by redtankd** [comment]
Thanks for your answer. But the comment for executor::Spawn::execute()  says "A specialized function to request running a future to completion on the specified executor." Is it possible for Myfuture?

**Comment by alexcrichton** [comment]
Currently, no, because the `poll` function is not correctly implemented to adhere to the contract of the `Future` trait. If you were to insert `task::park().unpark()` you'd simulate the contract being adhered to, though, which would fix the issue above.
