### ISSUE TITLE
Chaining streams triggers "reached the recursion limit during monomorphization"

### ISSUE THREAD

**Issue by cetra3** [alexcrichton/futures-rs#424]
Using this branch here: https://github.com/cetra3/apache_log/tree/recursion_limit

Trying to compile renders the following message:

```
cargo build
   Compiling apache_log v0.2.0 (file:///Users/cetra/Desktop/apache_log)
error: reached the recursion limit during monomorphization (selection ambiguity)

error: Could not compile `apache_log`.
```

I'm wondering if there is another way to accomplish what I'm trying to do, or whether there is some setting I can set to increase the `recursion limit`

**Comment by alexcrichton** [comment]
May be related to https://github.com/alexcrichton/futures-rs/issues/367 or https://github.com/alexcrichton/futures-rs/issues/393 or https://github.com/rust-lang/rust/issues/40003. I'd love to work around these errors but unfortunately I'm not sure how to do so :(
