### ISSUE TITLE
Futures could be zero-allocation (at least for tokio)

### ISSUE THREAD

**Issue by leodasvacas** [alexcrichton/futures-rs#430]
I'm learning futures and am wondering if futures be zeroer-cost for tokio. From the [tokio docs](https://tokio.rs/docs/going-deeper/tasks/):
> As an executor the Core type is responsible for providing an implementation of Unpark when polling futures. This implementation just needs to wake up the event loop, so for all futures it’s just the SetReadiness type that mio provides.

All tokio needs to provide is a `SetReadiness` which already does it's own allocating and ref-counting. However futures require that to be turned into an `Unpark` trait object and wrapped in another `Arc`. The single allocation guarantee of futures turns into a needless allocation for tokio.

<s>Could the `Arc` be avoided by taking something like a `Borrow<Unpark> + Send + Sync` trait object?</s>. No because trait objects cannot be `Clone`.

Avoiding the trait object in futures would require a lot of meta-programming if at all possible. Tokio could use a specialized futures crate but that isn't worth it given the benchmark that shows tokio within 0.3% of raw mio.

**Comment by alexcrichton** [comment]
I don't think that this would be easily possible to have literally zero allocations per future in Tokio, but if you've got benchmarks showing that allocation is high up I think we can definitely reduce 2 to 1 allocations per future in Tokio.

**Comment by leodasvacas** [comment]
@alexcrichton I don't have benchmarks though I might make some out of curiosity.

There is a public relations aspect, you go from "futures impose one allocation" to "futures impose at most one allocation, in particular no extra allocation is needed when working with mio such as in tokio".

**Comment by carllerche** [comment]
It's plausible to make changes to futures such that the allocation can be avoided, but it currently isn't a terribly high priority and I don't know if Tokio itself would ever opt into it.

If there are benchmarks showing that the allocations are noticeable at all, I think that would help inform prioritization. Currently, I would be surprised if the allocation matters at all given how expensive sys calls tend to me..

That being said, if we were to actually count the number of allocations needed to run a single task using a single TcpStream, I think it would be more than 2 right now. Off the top of my head, Mio makes one for the registration, which tokio-core uses, Tokio allocates twice, once for the task and once for the Unpark handle (I believe). There is also an allocation internally for the TcpStream. So, I believe that takes it up to 4 allocations?

I think that could be reduced to 2 in the common case w/o impacting ergonomics... reducing it to zero would require changes to the API and will most likely never be the primary way to use Tokio.

**Comment by alexcrichton** [comment]
I think this was covered in #436, so closing. Let me know though if I'm wrong!
