### ISSUE TITLE
Consider switching Arc<Unpark> to an opaque type

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/futures-rs#432]
This issue is mostly a placeholder for a discussion leading up to 0.2. 

Currently, Arc<Unpark> is used to pass around the unpark handle. This API has a hard requirement on Arc which means that an allocation is required even if it isn't strictly necessary.

I propose switching that to an opaque struct, something like UnparkHandle which would allow the internal representation to change in the future. 

There could be a conversion from Arc<Unpark> as I think we would need to maintain that indefinetly. 

Relates to #430

**Comment by alexcrichton** [comment]
I'd be surprised if we could do this, but I'd be willing to try!

**Comment by alexcrichton** [comment]
Done in #436!
