### ISSUE TITLE
Possible new release?

### ISSUE THREAD

**Issue by 46bit** [alexcrichton/futures-rs#438]
Hi. The minor changes since `v0.1.11` are needed for me to release a crate, so I'd love it if you could make a new release. Cheers!

**Comment by alexcrichton** [comment]
Certainly!

**Comment by 46bit** [comment]
Sorry… it turns out I'd forgotten to submit a patch. #439

**Comment by alexcrichton** [comment]
@46bit was that the only one, or do you also need https://github.com/alexcrichton/futures-rs/pull/426?

**Comment by 46bit** [comment]
@alexcrichton I don't need #426 but it's probably worthwhile to get that merged before the next release.

**Comment by 46bit** [comment]
@alexcrichton right then, that's all the changes, if you could re-rerelease that'd be awesome. :)
