### ISSUE TITLE
future::Fuse is a bit weird and has out of date documentation

### ISSUE THREAD

**Issue by Stebalien** [alexcrichton/futures-rs#44]
The documentation talks about `Some`/`None` which are nowhere in sight. Instead, it returns `NotReady` if the value has already been returned. That's probably fine although returning `Some(value)` and then `None` forever would be more in-line with `Iterator::fuse`.

I know this issue is a bit vague but, beyond fixing the documentation, I don't really know the correct thing to do here.

----
Just to be clear, this is talking about [this Fuse](http://alexcrichton.com/futures-rs/futures/struct.Fuse.html).

**Comment by alexcrichton** [comment]
Ah yeah this was all a remnant of a time long since passed, thanks for the issue!
