### ISSUE TITLE
Stream pipe

### ISSUE THREAD

**Issue by operutka** [alexcrichton/futures-rs#440]
Hi,

I was wondering if there was a way how to pipe a `Stream` and a `Stream + Sink` objects together (let's call them objects A and B). I didn't find any ready-to-use solution, so I tried to make my own (see below).

The semantics of the _pipe_ operation is similar to _forward_. However, _forward_ returns a future whereas _pipe_ should return a stream. In other words, _pipe_ should get items from object A, pass them to object B and return a stream of items from B.

Note that this is not the same operation as _map_ or _filter\_map_. Passing an item to B may yield zero or more items from B. Moreover, B may yield items even without passing an A item to it.

I got inspired by implementation of `Forward` and created the following solution:
```rust
#[derive(Debug)]
#[must_use = "streams do nothing unless polled"]
pub struct Pipe<T: Stream, U> {
    stream:   Fuse<T>,
    sink:     U,
    buffered: Option<T::Item>,
}

pub fn new<T, U>(stream: T, sink: U) -> Pipe<T, U>
    where T: Stream,
          U: Stream + Sink<SinkItem=T::Item>,
          U::SinkError: From<T::Error>,
          U::Error: From<U::SinkError>,
{
    Pipe {
        stream:   stream.fuse(),
        sink:     sink,
        buffered: None,
    }
}

impl<T, U> Pipe<T, U>
    where T: Stream,
          U: Stream + Sink<SinkItem=T::Item>,
          U::SinkError: From<T::Error>,
          U::Error: From<U::SinkError>,
{
    fn poll_stream_item(&mut self) -> Poll<Option<T::Item>, T::Error> {
        // take the buffered item if there is one
        if let Some(item) = self.buffered.take() {
            return Ok(Async::Ready(Some(item)))
        }

        self.stream.poll()
    }

    fn try_start_send(&mut self, item: T::Item) -> Poll<(), U::SinkError> {
        debug_assert!(self.buffered.is_none());
        if let AsyncSink::NotReady(item) = try!(self.sink.start_send(item)) {
            self.buffered = Some(item);
            return Ok(Async::NotReady)
        }
        Ok(Async::Ready(()))
    }

    fn feed_sink(&mut self) -> Poll<(), U::SinkError> {
        loop {
            match try!(self.poll_stream_item()) {
                Async::Ready(Some(item)) => try_ready!(self.try_start_send(item)),
                Async::Ready(None)       => return self.sink.close(),
                Async::NotReady          => return self.sink.poll_complete()
            }
        }
    }
}

impl<T, U> Stream for Pipe<T, U>
    where T: Stream,
          U: Stream + Sink<SinkItem=T::Item>,
          U::SinkError: From<T::Error>,
          U::Error: From<U::SinkError>,
{
    type Item = U::Item;
    type Error = U::Error;

    fn poll(&mut self) -> Poll<Option<Self::Item>, Self::Error> {
        // feed the internal sink
        try!(self.feed_sink());

        // retrieve the next item from the sink stream
        self.sink.poll()
    }
}

impl<T, U> Sink for Pipe<T, U>
where T: Stream + Sink,
      U: Stream + Sink<SinkItem=T::Item>,
      U::SinkError: From<T::Error>,
      U::Error: From<U::SinkError>,
{
    type SinkItem  = T::SinkItem;
    type SinkError = T::SinkError;

    fn start_send(&mut self, item: Self::SinkItem) -> StartSend<Self::SinkItem, Self::SinkError> {
        self.stream.start_send(item)
    }

    fn poll_complete(&mut self) -> Poll<(), Self::SinkError> {
        self.stream.poll_complete()
    }
}
```

**Comment by alexcrichton** [comment]
Interesting, this does seem like a use case that's not particularly covered well today. My best guess to achieve this using existing combinators is to split the `Stream + Sink`, `forward` the stream/sink pair, and then there's a future to schedule somewhere and a stream to pull from.

Does that work for your use case?

**Comment by operutka** [comment]
Thanks, that's a good point. I didn't consider this solution. However, there is still one problem here. When I split B into stream/sink pair, forward A into the B sink and schedule the task somewhere, I loose control over the error handling on the input.

To make it a little bit more obvious, consider the following code in tokio:

```rust
let mut core = TokioCore::new()?;
let handle = core.handle();

let addr = addr.to_socket_addrs()?
    .next()
    .ok_or(io::Error::new(io::ErrorKind::Other, "unable to resolve a given address"))?;

let service = ... // some object implementing Stream + Sink

let client = TcpStream::connect(&addr, &handle)
    .and_then(|stream| {
        let framed = stream.framed(SomeCodec);
        let (tcp_sink, tcp_stream) = framed.split();
        let (svc_sink, svc_stream) = service.split();

        // handle.spawn() takes a future F: Future<Item=(), Error=()>, so
        // I have to drop all possible errors here. I can log them but I cannot
        // cancel processing of the "output" future.
        let input = tcp_stream.forward(svc_sink)
            .then(|_| Ok(()));

        handle.spawn(input);

        let output = tcp_sink.send_all(svc_stream)
            .and_then(|_| {
                Ok(())
            });
        
        output
    });

core.run(client)
```

On the other hand, calling `poll()` on the `Pipe` struct will result in error if anything fails. It also simplifies the code a little bit:
```rust
...
let client = TcpStream::connect(&addr, &handle)
    .and_then(|stream| {
        let framed = stream.framed(SomeCodec);
        let (tcp_sink, tcp_stream) = framed.split();

        // all errors are propagated here
        let messages = tcp_stream.pipe(service);

        tcp_sink.send_all(messages)
            .and_then(|_| {
                Ok(())
            })
    });
...
```

**Comment by alexcrichton** [comment]
Oh yeah that's definitely true, the error'll need to get juggled around to get to the right location. Basically I think it's definitely possible to create such a combinator, and your implementation looks correct. I'm not sure if it belongs in the `futures` crate itself, though?

If you wanted to avoid the `spawn` you could also just `join` the `send_all` with the `forward`, and that should also let you handle the errors.

**Comment by operutka** [comment]
I'm not suggesting to include this combinator in the `futures` create. :) I was just wondering if there was an easy and "right" solution for this use case. Thanks a lot for pointing out the split and join. I wouldn't probably figured it out myself.

**Comment by alexcrichton** [comment]
Ok, sounds good to me! In that case I'll close, but let me know if you've got any more questions.
