### ISSUE TITLE
Future trait is public by two names

### ISSUE THREAD

**Issue by yorickjh** [alexcrichton/futures-rs#444]
Future can be imported by package users as futures::Future or futures::future:Future, and neither is marked deprecated.

For consistency and simplicity, it should be one or the other.

**Comment by yorickjh** [comment]
Also applies to Stream, Sink and a few other traits pub use'd from the root lib.rs.

**Comment by carllerche** [comment]
Thanks for the report. This follows a pattern from std. For example,
HashMap is available from the collections module and the
collections::hash_map module. It is idiomatic to reexport common types in
the parent module.

**Comment by yorickjh** [comment]
Seems odd, but fair enough. 'scuse my Rust newbishness. :)
