### ISSUE TITLE
Stream::merge is confusing

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/futures-rs#449]
I would not have expected the returned stream to yield `MergedItems` with a `Both` variant. I would have expected `merge` to take streams of the same type and return a stream of the same yielded types.

My *guess* is that this was an attempt to handle fairness, however, that could be done by just alternating which stream is polled first.

**Comment by alexcrichton** [comment]
Note that `Stream::select` implements the "two streams of same type, returning that same item" paradigm

**Comment by carllerche** [comment]
That is true... I would have expected `select` to be `merge`... Is having both implementations worth it? I didn't even think of looking for select...

**Comment by alexcrichton** [comment]
Nah with 0.2 I think we should delete `merge` unless we find a use case for it.

**Comment by alexcrichton** [comment]
oops didn't mean to close

**Comment by carllerche** [comment]
I guess we should flag it as deprecated... unless there is a use case for it (of which I am not aware).

**Comment by alexcrichton** [comment]
I'd r+ such a PR!

**Comment by Ralith** [comment]
It might be worth making the 0.2 `Stream::select` implementation consistent with the 0.2 `Future::select`, which iirc is planned to be what is now `Future::select2`. That could mean making `Stream::select` return an enum with either item type, like `Stream::merge` without the `Both` case as originally suggested in this issue.

**Comment by ishitatsuyuki** [comment]
There is definitely usage for merge, I'm planning to use it for creating reactive variable bindings with possible input changes of multiple types.

However, `Both` is totally nonsense. It makes the code complicated for most cases, since we're going to duplicate the handling for `Both` case. Also, it increases memory usage, while it's rare that two futures finishes at once.

**Comment by ishitatsuyuki** [comment]
The `Both` case can be seamlessly replaced with `zip()` which is exactly designed for this purpose.

**Comment by carllerche** [comment]
@ishitatsuyuki the point is that `Stream::select` IS `merge` w/o `Both`.

**Comment by ishitatsuyuki** [comment]
@carllerche isn't that without variant at all?

**Comment by carllerche** [comment]
What variant?

**Comment by ishitatsuyuki** [comment]
Stream::select only produces one type of output, while merge has two variants. That's an important feature, but the Both case isn't and simply annoying.

**Comment by carllerche** [comment]
@ishitatsuyuki I'm not sure what you are proposing. Either, you have to take a uniform type (like `select`) or you have to introduce a variant like `Both`.

I think `merge` will be deprecated in favor of `select`, and if you need to select across multiple types, you can map the streams first.

**Comment by ishitatsuyuki** [comment]
@carllerche We don't need `Both` at all, only `First` or `Second`. While the variants are important, implementing `Both` complicates both library side and user side of code (it becomes a special case and most user would split it into two). That's why I also mentioned `zip()` as a replacement.

**Comment by troplin** [comment]
I'm using `merge` together with `take_while` to inject a shutdown signal into the stream. Pity that it's deprecated now.

But I agree with @ishitatsuyuki that the `Both` variant is superfluous and should be replaced with 2 consecutive yields of `First` and `Second`, the same way as in `select`.

**Comment by carllerche** [comment]
@troplin well, can you replace your usage of `merge` with `select?

**Comment by ishitatsuyuki** [comment]
There's two issue here:
1. The role of `merge` and `select` is swapped out in Streams compared to Future.
2. A merging method with different variant is still useful. @troplin probably wants a `Second` variant for the signal.

**Comment by troplin** [comment]
@carllerche As @ishitatsuyuki pointed out, I need an enum anyway to inject the signal into the data stream. But implementing `merge` in terms of `select` is not exactly magic, so this is probably what I'll end up doing if `merge` will be removed.
