### ISSUE TITLE
and_then variation for FutureResult to handle mismatch error types

### ISSUE THREAD

**Issue by sezaru** [alexcrichton/futures-rs#465]
Hello, first of all, I'm not quite sure if this is the best place to post this, but since couldn't find a better future-rs specific place to ask and I think other people may have the same problem, I decided to post it here.

So, I want to be able to have a special `and_then` variation for futures that will work with different errors returned from the functions, converting then to the caller function return type using trait `From`.

To better illustrate what I mean by that, I will show a simple example using std `Result` type and then expand it to `FutureResult`.

Let's say I have these types:

    pub enum BuilderError {
        ElementMissing(&'static str),
    }

    pub enum XmlError {
        XmlCreationFailed(writer::Error),
        ConversionToUtf8(FromUtf8Error),
    }

    pub enum WebserviceError {
        XmlError(XmlError),
        BuilderError(BuilderError),
    }

    impl From<XmlError> for WebserviceError {
        fn from(error: XmlError) -> WebserviceError {
            WebserviceError::XmlError(error)
        }
    }

    impl From<BuilderError> for WebserviceError {
        fn from(error: BuilderError) -> WebserviceError {
            WebserviceError::BuilderError(error)
        }
    }

So I have 3 enums for my errors, `WebserviceError` enum will implement `From` trait so I can convert `XmlError` and `BuilderError` to it.

Now I have these functions:

    pub fn spawn(self) -> Result<ServiceStatus, BuilderError> { ... }

    pub fn create_xml(service_status: super::ServiceStatus) -> Result<String, XmlError> { ... }

and a function that will use the above functions to return a `Result<String, WebserviceError>`:

    fn test() -> Result<String, status::WebserviceError> {
        ...
        Ok(builder)
            .and_then_with_conversion(status::ServiceStatusBuilder::spawn)
            .and_then_with_conversion(status::create_xml)
    }

This syntax is possible because of my custom `and_then_with_conversion` function which is implemented as follows:

    trait AndThenWithConversion<T, E> {
        fn and_then_with_conversion<U, E2, F: FnOnce(T) -> Result<U, E2>>(self, op: F) -> Result<U, E>
            where E: std::convert::From<E2>;
    }

    impl<T, E> AndThenWithConversion<T, E> for Result<T, E> {
        fn and_then_with_conversion<U, E2, F: FnOnce(T) -> Result<U, E2>>(self, op: F) -> Result<U, E>
            where E: std::convert::From<E2>
        {
            self.and_then(|t| op(t).map_err(From::from))
        }
    }

As you can see, this function will simply call `and_then` followed by a `map_err(From::from)` which will make the conversion.

Note that the return value is `Result<U, E>` but the lambda function `op` return type is a `Result<U, E2>`.

Now, I tried to implement the same logic for `FutureResult`, but I couldn't because it's implementation differs greatly.

As far as I understand, `FutureResult` `and_then` returns a object that implements `AndThen` trait. But I'm not sure how to handle it to change the error type that it produces.

Also, another variation that will implicitly convert a `Result` to a `FutureResult` without the explicit `future::result` function call would be nice too.

So, is that possible? If so, does it make sense to have a special case for it in the library?

And, even if it does not, can you help me to implement it so I can use in my projects?

Thanks a lot

**Comment by alexcrichton** [comment]
Thanks for the report! For error conversion we've got the [`from_err` combinator](https://docs.rs/futures/0.1.13/futures/future/trait.Future.html#method.from_err) in general, and some conversions of futures bake in the `From` conversions but not others. In general using `From` everywhere tends to not play nicely with type inference (makes it difficult to infer types everywhere), but would using `from_err` help here?

**Comment by sezaru** [comment]
Hey Alex, thanks for the response!

So, `from_err` is like `map_err` but maybe a little less verbose right? Using it I was able to implement my function like this:

    fn test() -> future::BoxFuture<String, status::WebserviceError> {
        ...
        future::ok(builder)
        .and_then(|builder| future::result(builder.spawn()).from_err())
        .and_then(|service_status| future::result(status::create_xml(service_status)).from_err())
        .and_then(|xml| status::async_perform(xml).from_err())
        .boxed()
    }

This is quite nice and works as expected!

But it is a little more verbose than my `Result` example, is it possible to abstract `future::result` and `.from_err()` call away so I can rewrite it someway like this?

    fn test() -> future::BoxFuture<String, status::WebserviceError> {
        ...
        future::ok(builder)
        .and_then(from_err(result(status::ServiceStatus::spawn)))
        .and_then(from_err(result(status::create_xml)))
        .and_then(from_err(status::async_perform))
        .boxed()
    }

**Comment by alexcrichton** [comment]
Yeah that's about it, `.from_err` is just `map_err` but with a baked in clsoure really.

We could certainly consider extending `result` for 0.2 yeah, but I think for the 0.1 series it may cause enough type inference breakage to not be able to land :(
