### ISSUE TITLE
Dependency Updates

### ISSUE THREAD

**Issue by ishbir** [alexcrichton/futures-rs#47]
Dependencies in lots of the sub-libraries are specified as absolute numbers down to the patch. This can pose problems when new versions of the libraries are released or the downstream user needs to use an older one because of various reasons.

For example, in `Cargo.toml` of `futures-curl`, the version string of `curl` should be changed to `0.3` if that works. If not that then `^0.3.3` since `0.3.4` is already out. At the moment I'm unable to compile by specifying `0.3.4` in the `Cargo.toml` of my binary because of a version conflict. Similarly, the version of `crossbeam` in `futures-cpupool` should be changed to `^0.2.10`. Same for `scoped-tls` and `slab` in `futures-mio`. And the `Cargo.toml` of `futures` itself specifies the version for various sub-libraries as `0.1.0` whereas the sub-libraries reference `futures` as `0.1`. I think the former should be changed to `0.1`.

**Comment by alexcrichton** [comment]
Thanks for the report! The syntax here is actually I think special to cargo where `= "1.2.3"` is by default a [caret requirement](http://doc.crates.io/specifying-dependencies.html#caret-requirements). This means that a dependency of `= "0.3.3"` is actually the same as `= ">= 0.3.3, < 0.4.0"`.

I'm surprised though that you weren't able to use 0.3.4? If you run `cargo update -p curl` it should pull it in automatically, but was that not happening?

**Comment by ishbir** [comment]
My bad. I didn't run `cargo update` but just ran `cargo build` expecting it to function. Apologies.
