### ISSUE TITLE
Type mismatch on the error type when using and_then

### ISSUE THREAD

**Issue by jimmycuadra** [alexcrichton/futures-rs#472]
This isn't a bug report, but a request/suggestion for improved docs, or if it's possible somehow, better compiler errors for this common error when using `Future::and_then`:

```
.and_then(|whatever| {
 ^^^^^^^^ expected enum `foo::Error`, found enum `bar::Error`
```

As a futures newbie trying to learn, I've encountered this many times and I eventually figured it out after trial and error with combinators, but by the next time it happens I can't remember how I fixed it. I somehow haven't formed a clear mental model of what is happening in this case. I think it'd be helpful to document this somewhere. It might not make sense in the API docs for `and_then`, per se, but perhaps some sort of guide to futures a la the guide to Tokio on https://tokio.rs/.

Here is my thought process when I see this error:

> Why is `and_then` complaining about an error type? `and_then` doesn't take an error, it takes the value from a successful operation... Which error is it referring to? The error of the future that this call is chaining onto? Or the error of the future produced by this call? What method do I use to fix it? `map_err`? `from_err`?

**Comment by jimmycuadra** [comment]
This might be a dupe of #402. Feel free to close this if so.

**Comment by alexcrichton** [comment]
Ah yeah looks to be so!
