### ISSUE TITLE
Change stream::iter to not require an iterator of Result

### ISSUE THREAD

**Issue by alexcrichton** [alexcrichton/futures-rs#480]
Just work over an iterator of T and don't fail!

**Comment by sfackler** [comment]
Could it instead be changed to

```rust
fn iter<I>(it: I) -> Iter<I::IntoIter>
where
    I: IntoIterator,
    I::Item: IntoFuture
{
    // ...
}
```

I think it'd be backwards compatible (other than the documentation about not blocking needing to change)

**Comment by alexcrichton** [comment]
@sfackler that's possible yeah, along the lines of #477 as well. I'd personally prefer for the function to not operate over results though and instead work over bare `T` instances (with a generic "figure out later" error `E`).

**Comment by sfackler** [comment]
@alexcrichton isn't that what the signature above does? `I::Item = Result<T, E>` is just one example of an `IntoFuture` argument.

**Comment by alexcrichton** [comment]
Oh I'm thinking of:

```rust
fn iter<I, E>(it: I) -> impl Stream<Item = I::Item, Error = E>
    where I: IntoIterator;
```
