### ISSUE TITLE
Minor wording issue in docs for futures::sync::oneshot::Sender

### ISSUE THREAD

**Issue by silmeth** [alexcrichton/futures-rs#482]
Docs for `oneshot::Sender` in the description of the [`send` method](https://docs.rs/futures/0.1.13/futures/sync/oneshot/struct.Sender.html#method.send) say:

> Completes this oneshot with a successful result.
> 
> This function will consume `self` and indicate to the other end, the `Receiver`, that the error provided is the result of the computation this represents.

The *the error provided* part sounds off and confusing. Shouldn’t it be *the value provided*, as the method is used to complete the future with a successful result? It seems like a copy-paste mistake.

**Comment by alexcrichton** [comment]
Oh oops indeed! PRs are of course always welcome to update this!
