### ISSUE TITLE
Event (signal) API

### ISSUE THREAD

**Issue by stepancheg** [alexcrichton/futures-rs#489]
One of basic prititives of inter-thread communication is either condvar or [event](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686915(v=vs.85).aspx) or futex or [std::synchronic](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0126r2.pdf).

For example, any of them can be used to implement a queue:

```
writer threads:
loop {
    update shared data structure in non-blocking fashion
    signal
}

reader threads:
loop {
    wait for signal
    read shared data structure without lock
}
```

Such primitive is important, because, for example, futures' unbounded channel can be easily implemented with such event + queue from `std::sync` (or simply `VecDeque` for `unsync`). (And not so easily without it without deep understanding of futures internals).

futures-rs lacks such primitive building block (and `Task` API is hard and inconvenient).

I think futex-like API is probably best choice.

**Comment by carllerche** [comment]
Could you explain why `Task::notify` (formerly `Task::unpark`) is not sufficient for these cases?

**Comment by stepancheg** [comment]
Probably, `Task::notify` is too low level. It is hard to work with it without good understanding of internals.

For example, if you have more than one subscriber, and you want to "park", you need to remove previous self task.

And if you want to unpark all the subscribers, you need to iterate over all of them and do unpark.

For example, I'm having hard time understanding how `Sender::park` and `Receiver::unpark_one` works.

Futex-like API could hide all the details. With futex I just call `wait` and `notify_one`/`notify_all`.

But probably I've just used standard threading primitives too much.

OK, I think I should close the issue, give it some though and reopen it later.
