### ISSUE TITLE
Progress on NotReady

### ISSUE THREAD

**Issue by derekdreery** [alexcrichton/futures-rs#491]
I was wondering if anyone had mentionend this use-case:

I have a ui and want to load some io resource from network or similar, and I want to report progress of the io. 

This would correspond to having some type parameter on `NotReady` so that information could be passed, and this type would probably default to `()`. I'm not sure if this is possible in the current future implementation, or if it would be better as a separate crate.

**Comment by alexcrichton** [comment]
There's a few options I think that may be possible to get this done with today's setup:

* If you've got a custom instance of `Future` you could add a method to detect how much progress is made perhaps and arrange for that method to be called when you'd like to know how much is ready.
* You could also make a `Stream` where the item coming out is an enum of either "done" or "this is how much progress I've made"

Would either of those work for your situation?

**Comment by leodasvacas** [comment]
How are you running your future? Perhaps the future could communicate the progress to the UI thread before returning `NotReady`? I think it's common for top level futures to return `()` and communicate progress through [a channel](https://doc.rust-lang.org/std/sync/mpsc/index.html). Your future would hold the `Sender` and the UI thread would hold the `Receiver`.

**Comment by derekdreery** [comment]
Hi thanks for the responses, it seems like the approach suggested is to implement progress outside of the Future trait, which is fine for me.
