### ISSUE TITLE
Race in ThreadUnpark?

### ISSUE THREAD

**Issue by stepancheg** [alexcrichton/futures-rs#500]
If `park` and `notify` are called concurrently, this is possible:

```
thread A: call park
thread B: call notify
thread A: if !self.ready.swap(false, Ordering::SeqCst) // if !false // if true
thread B: ready = true
thread B: self.thread.unpark()
thread A: Thread::park
```

So, result is thread A is parked, however `notify` is called.

I'm not sure I understand properly what should `ThreadUnpark` do, I'm just trying to find why my program hangs, and found this function.

**Comment by alexcrichton** [comment]
Thanks for the report! This is expected behavior here, though, and there's no race here. The semantics of park/unpark can be [found here](https://doc.rust-lang.org/std/thread/#blocking-support-park-and-unpark).
