### ISSUE TITLE
Question about truly asynchronous nature of futures

### ISSUE THREAD

**Issue by belfz** [alexcrichton/futures-rs#509]
I'm a novice enthusiast of Rust lang, coming from the JavaScript land (with Node.js background too).
Recently I tried to wrap my head around the implementation of Futures in this library. I expected the behaviour of those to be truly asynchronous (like Promises in JS land), but instead I can't get even close to what I think would be natural in this context.

As an example, let's take a piece of JavaScript code first, utilising Promise:
```javascript
const p = Promise.resolve(42);

// logs last
p.then(val => console.log(`the answer is ${val}`));

// logs first
console.log('this actually logs first');

```
and the output:
```
this actually logs first
the answer is 42
```
You can notice, that Promise's `.then()` handler, despite being attached **before** the `console.log('this actually logs first');` line, actually yields it's output last. This is expected - Promise is handled asynchronously and does not block the rest of the "synchronous" code from executing.

I tried to achieve the similar result with Rust and futures-rs library - however, I couldn't find an example that would bring me even bit closer to what we can see above. The only way (so far I know about) that I can "extract" a value resolved from the Future, is by calling `.wait()` method, *which results in blocking behaviour*:
```Rust
extern crate futures;
extern crate futures_cpupool;

use futures::Future;
use futures_cpupool::CpuPool;

fn main() {
    let pool = CpuPool::new_num_cpus();
    let future_answer = pool.spawn_fn(|| {
        let answer: Result<u32, ()> = Ok(42);
        answer
    });

    let answer = future_answer.wait().unwrap();
    println!("the answer is {}", answer);

    println!("this actually logs last, because I had to call 'wait()' on the Future");
}
```
output:
```
the answer is 42
this actually logs last, because I had to call 'wait()' on the Future
```

 At the same time it's intuitive (I can expect that the method named `wait` will somehow block) and counter-intuitive (I expected that we aimed for asynchronous nature, so why do I even have to `.wait()` in order to "consume" the Future?).

**My question is**: am I missing something, and if so - how can I achieve non-blocking nature of Futures, similar to a JS example (presumably without a need to `.wait()` every time)?

Or maybe my expectations are wrong, and this is just the way things work in threaded model (versus event loop-based execution environment of JavaScript engines)?

BTW. I saw _similar_ [discussion here](https://github.com/alexcrichton/futures-rs/issues/50), but I have a feeling that the questions I have haven't been answered yet.

I really appreciate explanations to these questions - always eager to learn new concepts, especially for a language that fascinates me that much.

**Comment by fudini** [comment]
Not sure that using CpuPool will get you the results you want, but using tokio's event loop will:

```rust
extern crate futures;
extern crate futures_cpupool;
extern crate tokio_core;

use futures::Future;
use futures_cpupool::CpuPool;
use tokio_core::reactor::Core;

fn main() {
    let pool = CpuPool::new_num_cpus();
    let mut core = Core::new().unwrap();

    let future_answer = pool.spawn_fn(|| {
        let answer: Result<u32, ()> = Ok(42);
        answer
    });

    let answer = future_answer.map(|answer| {
        println!("the answer is {}", answer);
    });

    println!("this logs first now");

    core.run(answer).unwrap();
}
```

**Comment by belfz** [comment]
Thank you @fudini - great answer! This is *exactly* what I was looking for.

**Comment by alexcrichton** [comment]
Ah also note that the concurrency which is exercised in your original JS example is closest to `Handle::spawn` in tokio-core. What you can do is spawn the future into an event loop to see the interleaving desired.

For example, I might translate your JS example to:

```rust
extern crate futures;
extern crate tokio_core;

use futures::future::{Future, ok};
use tokio_core::reactor::Core;

fn main() {
    let mut core = Core::new().unwrap();

    let p = ok::<_, ()>(42);

    // logs last
    let p = p.map(|answer| println!("the answer is {}", answer));

    // logs first
    println!("this logs first now");

    // run the computation in `p`
    core.run(p).unwrap();
}

```
