### ISSUE TITLE
The TLS connection was non-properly terminated

### ISSUE THREAD

**Issue by rustomax** [alexcrichton/futures-rs#51]
Compiling and executing `techempower1` (`cargo run --release`) works fine, but getting the following error message from curl:

```
$ curl https://localhost:8080/json
curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.
```

**Comment by alexcrichton** [comment]
Oh the servers there aren't actually running TLS, they're all just plain HTTP. If you want to try out a TLS server you can try:

```
$ cargo run --manifest-path futures-minihttp/tls-example/Cargo.toml
$ curl --cacert futures-minihttp/tls-example/src/server.crt https://localhost:8080/plaintext
```

Does that work for you?

**Comment by rustomax** [comment]
Thanks for the quick reply. Actually it's just a problem with me blindly following the documentation [here](https://github.com/alexcrichton/futures-rs/blob/master/futures-minihttp/techempower1/README.md).  it says, "Then, make a connection `curl https://localhost:8080/json`". Changing the URL to plain http `curl http://localhost:8080/json` solves the problem.

**Comment by alexcrichton** [comment]
Oh oops! I'll fix those docs, thanks for the poitner!
