### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by jimmycuadra** [alexcrichton/futures-rs#510]
It would be useful to have a changelog for a high level overview of what has changed in each release of futures. This could either be a file in the source or notes on the GitHub releases page for each tagged release. Right now it's necessary to look through the commit log which can be hard to decipher for meaningful changes at times.

**Comment by alexcrichton** [comment]
FWIW the [git tags](https://github.com/alexcrichton/futures-rs/releases) should all have detailed notes, but if someone wanted to assemble that into a CHANGELOG.md that'd be awesome! Would be easy to duplicate the info between there and the tag in the future!
