### ISSUE TITLE
Add support for returning different futures from branches?

### ISSUE THREAD

**Issue by KeenS** [alexcrichton/futures-rs#522]
Current futures do not support different futures (types) from branches

```rust
fetch_data().and_then(|maybe_data| {
  match maybe_data {
    // error because `Ok` and `Join` are different types
    None => ok(None),
    Some(data) => fetch_more().join(Ok(data)),
  }
})
```

current solution is to use `Box` and create a trait object. It let us return different types.
However, It also introduces dynamic dispatch, which isn't zero-cost.

Thus I suggest a new `branch` API, which looks like

```
fetch_data().and_then(|maybe_data| {
  match maybe_data {
    // both arm of branch returns `Branch<Ok, Join<_, _>>`
    None => ok(None).branch().first(),
    Some(data) => fetch_more().join(Ok(data)).branch().second(),
  }
})
```

FYI the same API have already implemented to [`transaction-rs`](https://docs.rs/transaction/0.2.1/transaction/trait.Transaction.html#method.branch) (and source is [here](https://github.com/KeenS/transaction-rs/blob/master/transaction/src/branch.rs)).
And a tiny microbenchmark [showed](https://github.com/KeenS/transaction-rs/blob/master/transaction-stm/benches/boxed_vs_branch.rs#L87) 7% speed up.

How do you like this? I'll implement up to `Branch5` and submit a PR if you like.

**Comment by alexcrichton** [comment]
Thanks for the report! This sounds similar to https://github.com/alexcrichton/futures-rs/pull/356 perhaps? I think we've having `Either` types up to `EitherN` (or something like that) although adding dedicated methods hasn't gotten off the ground yet.

**Comment by burdges** [comment]
There were discussion in Rust RFCs repo about anonymous enums once upon a time, which sound like the ideal solution in the long term.  It might look like `-> enum Future` return type instead of `-> impl Future`, along with maybe `enum [expression]` inside that handles the negative reasoning of mapping form types to variants.  An `Either` approach might look like `-> Either3<impl Future, impl Future, impl Future>` with at best some `either!` procedural macro inside for the negative reasoning.

**Comment by KeenS** [comment]
@alexcrichton 
> This sounds similar to #356 perhaps?

Exactly. I scanned issues before reporting this issue but not PRs so I missed it, sorry.

> although adding dedicated methods hasn't gotten off the ground yet.

Then, I think this builder approach is one option.

> An Either approach might look like `-> Either3<impl Future, impl Future, impl Future>`

Isn't it sufficient that implementing Future for `Either3<F1, F2, F3>` where F1, F2, F3 is a Future (or, IntoFuture)? I think there are no overwrapping problem because tuples are already IntoFuture.

**Comment by KeenS** [comment]
closing as duplicated. I'll join the discussion at #356 .
