### ISSUE TITLE
Docs do not mention JoinAll maintaining order

### ISSUE THREAD

**Issue by alteous** [alexcrichton/futures-rs#524]
The documentation for [`join_all`](https://docs.rs/futures/0.1.14/futures/future/fn.join_all.html) (and also `JoinAll`) does not mention any guarantees of the futures resolving in the order they are given, however this is implied in the examples and seems to be evident in the implementation.

If ordering is intended to remain unchanged could this be noted explicitly?

**Comment by alexcrichton** [comment]
Fixed in https://github.com/alexcrichton/futures-rs/pull/525
