### ISSUE TITLE
Presumed deadlock with sync::mpsc

### ISSUE THREAD

**Issue by alexcrichton** [alexcrichton/futures-rs#529]
https://travis-ci.org/alexcrichton/futures-rs/jobs/249262983

```
     Running target/debug/deps/mpsc-8f8a597072297523

running 12 tests

test recv_close_gets_none ... ok

test send_recv ... ok

test send_recv_no_buffer ... ok

test send_recv_threads ... ok

test send_shared_recv ... ok

test send_recv_threads_no_capacity ... ok

test stress_drop_sender ... ok

test stress_receiver_multi_task_bounded_hard ... ok

test stress_shared_bounded_hard ... ok

test stress_shared_unbounded ... ok

test tx_close_gets_none ... ok

test stress_close_receiver has been running for over 60 seconds

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

I doubt that's spurious...

**Comment by carllerche** [comment]
linux 64 bit I assume?

**Comment by alexcrichton** [comment]
That specific deadlock was x86_64-apple-darwin, and after a bunch of runs I couldn't reproduce on Linux, although that doesn't necessarily mean it's OSX-specific.

**Comment by alexcrichton** [comment]
Closing due to https://github.com/alexcrichton/futures-rs/pull/582

**Comment by jpastuszek** [comment]
I am actually observing problem with `futures::sync::mpsc::Receiver` not waking up `Sender` in another thread. I can see that thread is still waiting on `mio::sys::unix::kqueue::{{impl}}::select` (`libsystem_kernel.dylib'kevent`) after I call `close()` or drop the `Receiver` in another thread on MacOS in some circumstances.

In my program I have a thread running `core.run()` with future that `send_all()` data read (and split by line) from named pipe (using tokio-file-unix crate). To exit the thread I `close()` the `Receiver` end. This works in case when I call `close()` first and then kill the process at the other end of the pipe. It will fail to unblock `kevent`/`core.run()` if I kill the process first and then `close()` the `Receiver`.
To work it around I have added `oneshot` pair that I `select2()` with that future and after `close()` call on `Receiver` I also `send(())` the `oneshot` channel to make sure the `core.run()` will exit on this future.
I don't know what role does the named pipe play in this scenario but `Receiver::close()` should be as reliable as `Sender::send()` in make `core.run()` call to exit?

**Comment by alexcrichton** [comment]
@jpastuszek interesting! If you can reduce the number of components involved that'd be great, but otherwise want to open an issue with instructions of how to reproduce?
