### ISSUE TITLE
Working with boxed streams

### ISSUE THREAD

**Issue by torkleyy** [alexcrichton/futures-rs#538]
It's likely that I am missing something, but I cannot really use `Box<Stream<..>>`, since the `self`-consuming methods don't work with it. I got a `Box<Stream<Item = u8, Error = io::Error>>` and I would just like to transform it into `Result<Vec<u8>, io::Error>`. How would I do that?

**Comment by alexcrichton** [comment]
Would `fold` or `collect` work for your use case?

**Comment by torkleyy** [comment]
That's what I tried, but `Self` needs to be `Sized`.

**Comment by dwrensha** [comment]
Does `use futures::Stream;` help? See https://github.com/rust-lang/rust/issues/35976.

**Comment by torkleyy** [comment]
@dwrensha Yes, it does. Thank you!
