### ISSUE TITLE
empty.rs:37 drops a `&mut Task`

### ISSUE THREAD

**Issue by llogiq** [alexcrichton/futures-rs#54]
If I understand the specifics of `std::mem::drop(_)`, this only drops the `&mut` reference, *not* the `Task`. Unfortunately, it is impossible to drop a value by its mutable borrow. I am not sure how to handle this, perhaps the `Task` needs a `drop(&mut self)` method that can be called instead.

**Comment by alexcrichton** [comment]
Ah yeah this was just there because of previous incarnations, removed!
