### ISSUE TITLE
Add a way to iterate a stream in parallel

### ISSUE THREAD

**Issue by canndrew** [alexcrichton/futures-rs#542]
There may already be a way to do this, but I can't see it from looking at the docs.

The documentation for the `Stream::for_each` method says:

>The closure provided will be called for each item this stream resolves to successfully, producing a future. That future will then be executed to completion before moving on to the next item.

I'd like a way to iterate over a stream, executing a closure which returns a future for each item, but for execution of that future to *not* block the rest of the stream. Something like `for_each` but which allows the resulting futures to run in parallel. Alternatively, a version of `flatten` that doesn't insist on running one stream to completion before moving onto the next would also suffice.

Is there any reason why this wouldn't be possible or is there already some way to do it that I'm not seeing?

**Comment by alexcrichton** [comment]
Would `buffered` or `buffer_unordered` help here perhaps?

**Comment by canndrew** [comment]
Oh, yes! `buffer_unordered` but with an infinitely-growable buffer is what I was imagining. I think the `usize` argument made me skip it when reading the docs. `buffer_unordered` will work though.

Sorry for the noise.
