### ISSUE TITLE
flattening Receiver impossible

### ISSUE THREAD

**Issue by rubdos** [alexcrichton/futures-rs#547]
Hi. I have a `futures::sync::oneshot::Receiver` on which I use map, and return a new future. I thought that I could use `flatten` on the result to get myself a nicely flattened future, but that's impossible.

My current solution looks like this.

```Rust
            let connector = connect_rx.map(move |(address, name, version)| {
                ::Connection::connect(&address, &handle)
                    .and_then(move |connection| { 
                        connection.hello(&name, &version)
                    })
            })
            .map_err(|e| {
                ::std::io::Error::from(::std::io::ErrorKind::BrokenPipe)
            })
            .flatten()
```

For some reason, flatten will only accept std::io::Error's, and not the Canceled type that `Receiver` has as Error type:

```
    the trait `std::convert::From<futures::Canceled>` is not implemented for `std::io::Error`
```

Is this desired behaviour? If so, is this documented somewhere?

**Comment by alexcrichton** [comment]
Thanks for the report! This may just be a case of a bad error message. If you call `map_err` first and then use `and_then` instead of `map`, does it work?

**Comment by rubdos** [comment]
> If you call map_err first and then use and_then instead of map, does it work?

Seems like it does, but that's logical, right?

I wonder what part demands the std::io::Error here, is that IntoFuture?

**Comment by alexcrichton** [comment]
Maybe some extra conversions or more help for type inference? Hard to say without having more of the concrete types in play here :(

Looks like it's working though, so closing.
