### ISSUE TITLE
Futures should play nicer with pattern matching

### ISSUE THREAD

**Issue by mqudsi** [alexcrichton/futures-rs#551]
So as a newcomer to `future-rs`, I had a hard time wrapping my brain around why I couldn't build a decision tree based off of futures.

My intuitive approach was as follows:

```rust
    let routine = match predicate {
        //result can be obtained synchronously
        Ok(x) => future::ok(x),
        Err(_) => {
            //we need to asynchronously obtain the value instead
            let x = async_funcction()
                .map(|x| some_transform)
                .map_err(|err| println!("Failure in async value obtain! {:?}", err))
        }
    }
    .and_then(|final_value| {
        //we have obtained the value either synchronously or asynchronously
        //now do something asynchronous with it
        ....
    });
```

This obviously doesn't work, because the match arms have different types. Does rust offer an ergonomic solution to this problem that could be adopted?

**Comment by alexcrichton** [comment]
Thanks for the report! Unfortunately there's not a great solution to this today. On stable you can use `Box<Future>` or if you know there's exactly two branches you can use the `Either` type in this crate. On nightly though we'll soon have [`#[async]` and `await!`](https://github.com/alexcrichton/futures-await) which should make this much nicer!

**Comment by mqudsi** [comment]
Thanks, @alexcrichton. I'm excited to rust coming one step closer to full-fledged, hopefully-someday-native async/await support; the linked document looks like a good start!

**Comment by mqudsi** [comment]
Oh, and as to my initial question: as soon as I realized I was barking up the wrong tree, I was able to use `futures::future::result` (I wish it were named `from_result` to be more consistent with the rust api) to basically deconstruct the predicate into `map` and `map_err` as my two cases, then continue on my merry way.

**Comment by alexcrichton** [comment]
Ok great! In that case I think I'll close this for now.

Right now `result` is intended to mirror the `ok` and `err` apis to create the "noop" future where it just matches the name of what it returns.
