### ISSUE TITLE
Grow CpuPool::spawn_stream/spawn_stream_unbounded

### ISSUE THREAD

**Issue by khuey** [alexcrichton/futures-rs#552]
Since we grew an mpsc based `spawn` and `spawn_unbounded` and `CpuPool` is now an `Executor`, it would be nice to polish this off by adding convenience methods directly to `CpuPool`.

The main difference afaict is that mpsc's `SpawnHandle` doesn't provide for cancellation.

**Comment by alexcrichton** [comment]
I think this is a dupe of https://github.com/alexcrichton/futures-rs/issues/470, so closing in favor of that. Good to add now though!
