### ISSUE TITLE
Add a method to Future like map that does not allow for mutation of the resolution

### ISSUE THREAD

**Issue by mehcode** [alexcrichton/futures-rs#562]
Unsure of a good name but I use `tap` in the example.

```rust
make_request().tap(|| {
  // [...] Executes on successful resolution of the future but does not see or 
  // alter the future
})
```

Recently I've been playing with futures and I've had a need to do _something_ when a future is resolved but that _something_ has little to do with the future being resolved. I could use `map` and forward the value but I'd rather express my intent more clearly.

```rust
// Functionally equivalent to the proposed 'tap'
make_request().map(|response| {
  // [...] Executes on successful resolution of the future but does not alter the future
  response
})
```

---

For more context, see https://github.com/mehcode/salt-rs/blob/master/examples/time.rs#L21-L29

**Comment by alexcrichton** [comment]
Adding an `inspect` combinator along the lines of `Iterator::inspect` sounds great to me! Could even add one to `Stream` as well.
