### ISSUE TITLE
busy loop when waiting on Stream::buffered()

### ISSUE THREAD

**Issue by dwrensha** [alexcrichton/futures-rs#57]
Consider the following program:

```rust
extern crate futures;
extern crate futures_io;
extern crate futures_mio;

use futures::Future;
use futures::stream::Stream;
use futures_io::{copy, TaskIo};

pub fn main() {
    let mut l = futures_mio::Loop::new().unwrap();
    let srv = l.handle().tcp_listen(&"127.0.0.1:5000".parse().unwrap());

    let future = srv.and_then(move |server| {
        server.incoming()
            .and_then(|s| TaskIo::new(s.0))
            .map(|i| i.split())
            .map(|(a,b)| copy(a,b).map(|_| ()))
            .buffered(10)
            .collect()
    });

    let _ = l.run(future);
}
```

Before https://github.com/alexcrichton/futures-rs/commit/9804cec6d61969f1961aa57ae0e2541f8057a804, this program successfully acted as a TCP echo server. Now it hangs, pegs a CPU, and fails to echo any data sent to it.

**Comment by alexcrichton** [comment]
Oops! Thanks for the report!

**Comment by dwrensha** [comment]
Thanks, but I think some bugginess remains. Now my program works if there is only ever one concurrent connection, but fails as soon as it receives more than one concurrent connection.

**Comment by alexcrichton** [comment]
Aha! Fixed in https://github.com/alexcrichton/futures-rs/commit/bce2ad2655db67728a1f7334919d689f334e7d48

**Comment by dwrensha** [comment]
Yay tests!
