### ISSUE TITLE
Wrapped type accessors for concrete futures and streams (e.g. Map)

### ISSUE THREAD

**Issue by dylanede** [alexcrichton/futures-rs#572]
Currently, once a future/stream has been used as a building block for a combinator (e.g. through calling `.map`) it is impossible to operate on that instance of that type directly, which would be useful if that future/stream type had methods on it other than those implemented through `Future`/`Stream`. One way of dealing with this is to provide a way of getting at the wrapped type, perhaps through a trait with methods like `.inner()` and `.inner_mut()`. `Map`, `Filter` and friends would then each implement this trait. In order for combinators like `Join` to work with this, the return type of `inner` could be a tuple of references in those cases.

Thoughts?

**Comment by alexcrichton** [comment]
Ah yeah we've done this for lots of types that are streams but haven't done it for futures just yet. I don't think there's particularly any reason not to, though, should be relatively easy to add!

**Comment by carllerche** [comment]
All future types should have `get_ref()` / `get_mut()` and `into_inner`. If those fns are missing on any, they can be added in a PR.

**Comment by dylanede** [comment]
Judging from https://docs.rs/futures/0.1.15/futures/?search=get_ref, it's pretty much just streams and sinks that have these methods on them, as you say @alexcrichton. Do you reckon it would be worth collecting these methods into a trait at all?

**Comment by alexcrichton** [comment]
Perhaps eventually, but for now just sticking to inherent methods should be fine

**Comment by jpastuszek** [comment]
```rust
struct GiveBack<I, E, S> where S: Stream<Item=I, Error=E> {
    stream: Option<S>,
    sender: Option<oneshot::Sender<S>>
}

impl<I, E, S> GiveBack<I, E, S> where S: Stream<Item=I, Error=E>  {
    fn new(stream: S) -> (GiveBack<I, E, S>, oneshot::Receiver<S>) {
        let (sender, receiver) = oneshot::channel();
        (
            GiveBack {
                stream: Some(stream),
                sender: Some(sender)
            },
            receiver
        )
    }
}

impl<I, E, S> Stream for GiveBack<I, E, S> where S: Stream<Item=I, Error=E>  {
    type Item = I;
    type Error = E;

    fn poll(&mut self) -> Poll<Option<Self::Item>, Self::Error> {
        self.stream.as_mut().unwrap().poll()
    }
}

impl<I, E, S> Drop for GiveBack<I, E, S> where S: Stream<Item=I, Error=E>  {
    fn drop(&mut self) {
        let stream = self.stream.take().unwrap();
        let sender = self.sender.take().unwrap();
        sender.send(stream).ok();
    }
}
```

Usage
```rust
        let (stdout, future_stdout) = GiveBack::new(self.stdout.unwrap());

            stdout
                .inspect(|log_line| println!("wait ready: {}", log_line))
                .take_while(|log_line| future::ok(!log_line.contains("engine started.")))
                //.take_while(|log_line| future::ok(!log_line.contains("Suricata")))
                .fold(Vec::new(), move |mut boot_log, log_line| {
                    boot_log.push(log_line);
                    future::ok(boot_log)
                })
                .map(move |boot_log| {
                    Suricata {
                        config: config,
                        process: process,
                        stdout: None,
                        eve_log: eve_log,
                        _state: Ready {
                            boot_log
                        },
                    }
                })
                // TODO: should not need to map_err -> custom Receiver as it cannot get canceled
                .join(future_stdout.map_err(|_canceled| ()))
                .map(|(mut suricata, stdout)| {
                    suricata.stdout = Some(stdout);
                    suricata
                })

**Comment by alexcrichton** [comment]
I think we've added these where we could and otherwise PRs are more than welcome if there are some laggard ones!

**Comment by dylanede** [comment]
`IntoFuture` is also missing these methods.
