### ISSUE TITLE
Reasoning for stream::iter deprecation?

### ISSUE THREAD

**Issue by bluejekyll** [alexcrichton/futures-rs#576]
I've been relying on this in some tests, specifically the ability to test Err's in the Stream. It looks like the replacement iter_ok is the replacement, but it only yields Ok, is this correct?

**Comment by alexcrichton** [comment]
Aha interesting! I just assumed this was never used b/c it was pretty unergonomic to do so. The hope here is that the current `iter_ok` implementation eventually becomes the `iter` implementation (in the next major version).

I did realize though, in updating tests, that there's no way to create a in-memory stream easily that returns an error. Are the streams in your tests just consisting of an error or do they consist of items before an error? We may want to consider a stream combinator that immediately returns an error, the eventual semantics we'd like for `Stream` is that an `Err` instance terminates the stream, but that wouldn't work so hot with the current `iter` where you can return lots of items after an `Err`

**Comment by bluejekyll** [comment]
Here's the example: https://github.com/bluejekyll/trust-dns/blob/master/server/tests/timeout_stream_tests.rs#L15

Basically I'm just taking a list of items, and then validating my logic in a "TimeoutStream" I implemented a while ago. Not sure if there's something better than that now. It's a list of test data, so literally `Ok`s and `Err`s.

> the eventual semantics we'd like for Stream is that an Err instance terminates the stream

This is interesting, I need to think about some of my impls that currently expect errors from the stream. Such as timeouts. Without doing an in depth review of it, at a minimum there may be a lot of code I need to update. Maybe the semantics won't have changed, but I worry that I'm relying on Errors right now in my streams for distinct errors with particular messages, as opposed to errors in the entire stream.

**Comment by carllerche** [comment]
It seems like keeping around both `iter` and `iter_ok` would be acceptable.

**Comment by alexcrichton** [comment]
@bluejekyll oh to be clear what I mean is that a generic stream would be considered "fused" once an error is returned (in that it can't be reliably polled again) although for any instance of a specific stream you could of course refine that contract.

@carllerche I'd imagine the functionality `iter_ok` provides today to be more in-demand than the result-based version, so that's why I wanted to deprecate `iter` as-is at least.

Perhaps we could add `iter_result` for an iterator over results?

**Comment by bluejekyll** [comment]
> for any instance of a specific stream you could of course refine that contract

Perfect.

> Perhaps we could add `iter_result` for an iterator over results?

I'm only using this in tests at the moment, so we don't need to muddy the waters just for that if noone else is relying on this.

**Comment by alexcrichton** [comment]
Nah so I don't think it's uncommon to need to create a stream that yields an error in tests, and without `iter` there's not actually a great way to do that I think? `future::err(x).into_stream()` is as close as we get but that's slightly wordy for something that shouldn't be too hard to get at.

**Comment by sid0** [comment]
[`std::fs::read_dir`](https://doc.rust-lang.org/std/fs/fn.read_dir.html) is an example of an iterator in core that returns `Result` instances.
