### ISSUE TITLE
The `slot` abstraction again

### ISSUE THREAD

**Issue by tailhook** [alexcrichton/futures-rs#586]
Hi,

Thinking more about #585 and #570 I'm not sure I was quite right.

I think I need a `poll_cancel` in a majority of my use cases to avoid memory leaks.

I think the channel can be made single-producer - single-consumer, with `poll_cancel`, because that would make implementation much simpler. Then restoring current behavior can be done by user by wrapping a sender into an `Arc` (because `swap` method takes a readonly reference).

Alternatively, is there a viable implementation of `poll_cancel` with multi-producer channel?

Note: we should decide this before futures 0.1.17 comes out :)

**Comment by alexcrichton** [comment]
This sounds plausible to me, albeit this still may be relatively niche compared to the existing mpsc channel. Currently the only real implementation of `poll_cancel` AFAIK is to just have a vector of tasks, which isn't great, unfortunately.

@carllerche do you have thoughts here?

**Comment by tailhook** [comment]
> Currently the only real implementation of poll_cancel AFAIK is to just have a vector of tasks, which isn't great, unfortunately.

Is there a way to deduplicate the tasks in vector? Otherwise, I think memory leak is more serious than just not using `poll_cancel` :)

>  still may be relatively niche compared to the existing mpsc channel

My use cases are: resolving (and updating) a DNS name, or any other information synced from a remote location, publishing progress of an operation. From this list, only the latter could perhaps be multi-producer, but it's required too.

**Comment by alexcrichton** [comment]
You could give each sender an ID and ensure that each sender has at most one task blocked, but you'd still need a slot for each sender.

**Comment by carllerche** [comment]
I actually wanted `mpsc::Sender::is_canceled` recently, which is significantly different than poll_cancel of course.

That said, the `Sender` already has a way to [track its task task](https://github.com/alexcrichton/futures-rs/blob/master/src/sync/mpsc/mod.rs#L99). Implementing `poll_cancel` would require pushing that node in a "notify me on cancel" queue. Of course, as @alexcrichton hinted at, if that queue gets large, dropping the RX could be expensive as it would need to notify that entire queue...

**Comment by alexcrichton** [comment]
Closing due to https://github.com/alexcrichton/futures-rs/pull/621
