### ISSUE TITLE
implementation of From<Arc<T>> for NotifyHandle doesn't work for non-sized T

### ISSUE THREAD

**Issue by tmccombs** [alexcrichton/futures-rs#588]
This means that Arc<T> doesn't implement `Into<NotifyHandle>` for trait types. in particular `Arc<Notify>` doesn't implement `Into<NotifyHandle>`.  I can't think of any particular reason why this has to be the case.

**Comment by alexcrichton** [comment]
Thanks for the report! This is actually required on a fundamental level, however, due to how the implementation works with vtables and whatnot.

**Comment by leodasvacas** [comment]
It's not that fundamental, we need `into_raw` and `from_raw` to be implemented for `Arc<T: ?Sized>` in std. [As you can see](https://doc.rust-lang.org/alloc/arc/struct.Arc.html) they are for sized types only, but it should be possible to implement them for DSTs somehow.

**Comment by alexcrichton** [comment]
@leodasvacas that's not true, if we were to actually support this on unsized types it would require an extra layer of indirection as we need the data to be precisely a pointer large, not two.

I actually intended to close this earlier, so I'm going to go ahead and...
