### ISSUE TITLE
Implementing Thread Pool Without "OldExecutor"

### ISSUE THREAD

**Issue by manuel-rhdt** [alexcrichton/futures-rs#589]
I'm trying to build a custom thread pool as an executor for futures. I am having trouble implementing the required traits for executors. futures-cpupool uses the `OldExecutor` (`execute::Executor`) trait to execute the `Run`s provided by the internal futures implementation.

However the `OldExecutor` trait seems to be deprecated soon so I want to understand the replacement API with `future::Executor` as the main trait for executors.

The public API I aim for is similar to that of the futures-cpupool crate. As far as I can see I have to implement the `future::Executor` for my `Threadpool` structure. The implementation of the `execute` method therein should then create a task for the future with `execute::spawn` and then in one of the threads `poll_future_notify` should be called. For that to happen I need to provide a type `Arc<T> where T: Notify` that enables my future to notify the threadpool when it should be polled again. I am not sure how to provide a struct that implements `Notify` as the `notify`-implementation has to manage somehow that new work gets scheduled on the threadpool which means that it needs to call `poll_future_notify` in turn. Is it therefor required that the `Notify`-structure has a member with an `Arc` pointing to itself? Or am I missing something?

Also it seems like the "Notifier"-struct needs to store the spawned future (type `Spawn`) so it can continue executing the task when it is polled. However since `Notify: Send + Sync` I need to wrap it in a Mutex and I still can't get it to compile for various other reasons.

It seems to me that the implementation using the `OldExecutor` trait was much simpler than with the current API. Can you tell me if any of my assumptions were wrong when trying to implement my executor? Is there anything to make my life simpler?

Code snippets:

```
pub struct Notifier<F> {
    inner: Arc<Inner>,
    spawn: Mutex<Option<Spawn<F>>>,
}

impl<F: Future<Item = (), Error = ()> + Send + Sync> executor::Notify for Notifier<F> {
    fn notify(&self, _: usize) {
        self.inner.threads.exec(move || {
            let spawn = self.spawn.lock();
            let spawn = spawn.unwrap().take().unwrap();
            let notify = SpawnedTask {
                inner: self.inner.clone(),
                spawn: Mutex::new(Some(spawn)),
            };
            // can't reuse spawn here --- Compiler Error
            spawn.poll_future_notify(&Arc::new(notify), 0);
        });
    }
}

impl<F> Executor<F> for Threadpool
where
    F: Future<Item = (), Error = ()> + Send + Sync + 'static,
{
    fn execute(&self, future: F) -> Result<(), ExecuteError<F>> {
        let spawn = executor::spawn(future);
        let notify = Notifier {
            inner: self.inner.clone(),
            spawn: Mutex::new(Some(spawn)),
        };
        notify.notify(0);
        Ok(())
    }
}
```

**Comment by carllerche** [comment]
[`futures-pool`](https://github.com/carllerche/futures-pool) is a thread pool implementation that doesn't use the old `Executor`. Maybe that can help.

**Comment by manuel-rhdt** [comment]
Thank you, this indeed helped me implementing my threadpool. I still think though that the deprecation of the old Executor increases the difficulty of implementing some executors.

**Comment by alexcrichton** [comment]
@manuel-rhdt it's definitely true that the old executor is slated for deprecation at some point, and it's also definitely true that it's more difficult to implement this paradigm without it! That being said it was our thinking that this sort of executor/implementation is quite rare and hence the increase in difficulty isn't so so bad, but do you find yourself implementing this pattern in a number of locations?

**Comment by manuel-rhdt** [comment]
@alexcrichton Ok I see the benefits of the new Executor trait and it is indeed quite rarely needed to implement executors. I just tried to do this for my own sake to better understand futures and was a bit surprised of the complexity and needing `unsafe` blocks in the executor implementation. 

But given the code in `futures-pool` as an example it was manageable for me to complete my small project. So I think the current situation is ok ;)

**Comment by alexcrichton** [comment]
Heh  yeah diving into the implementation of a number of constructs in `futures` and Tokio can get pretty hairy pretty quickly... In any case though sounds like we're all good, so I'm going to close this
