### ISSUE TITLE
BiLock does not poison on panic

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/futures-rs#595]
Looking through `BiLock`, it doesn't appear that there is any poisoning logic when a thread panics while locked. I would assume that the same safety issues that happen with `Mutex` would be possible with `BiLock`. If so, wouldn't the `BiLock` have to be poisoned?

**Comment by alexcrichton** [comment]
Seems plausible yeah? I don't feel particularly strongly either way

**Comment by carllerche** [comment]
Well, I assumed that Mutex poisoned to ensure soundness? Is that incorrect?

**Comment by alexcrichton** [comment]
Oh no, poisioning is for "more correct in more situations hopefully", not memory safety

**Comment by carllerche** [comment]
Ok, then I don't really care either.
