### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by phil-opp** [alexcrichton/futures-rs#60]
The core `futures` crate is very close to being buildable in `no_std` crates (with `liballoc` and `libcollections`). I've applied all necessary changes in an [experimental branch](https://github.com/alexcrichton/futures-rs/compare/e9381c2dd020f95604c7eec17764ba7f85040e7c...phil-opp:wip-no-std) and it compiles without problems.

There are only two rough spots:

- The `LIMITED` executor can't be used as it relies on a thread local variable. To circumvent this, we can set the default executor to `Inline`.
- We can't `catch_unwind`.

--

I'd love to use this library in my `no_std` crates. Are there any plans to add `no_std` support, e.g. through a cargo feature?

**Comment by alexcrichton** [comment]
Oh whoa, awesome! I'm surprised you were able to get that far :)

Currently `LIMITED` isn't a "fundamental requirement" so it'd be easy to remove I think. I've debated in the past jettisoning it as it doesn't seem too useful any more anyway.

That being said I'm still worried about the `Arc` in `Task` for `#![no_std]` support. This ends up requiring nightly Rust for the `alloc` crate, as well as perhaps having inappropriate OOM behavior where the whole process would be aborted.

I'd be totally on board with pushing as far as we can towards no_std, though, so long as it doesn't end up hamstringing the std users!

**Comment by alexcrichton** [comment]
I have good news on this front, we've got an upcoming PR which should make the `Future` trait itself trivially `#![no_std]` compatible, so I'll post back here when that happens :)

**Comment by phil-opp** [comment]
That's great! I'm looking forward to it :)

**Comment by alexcrichton** [comment]
Ok, [PR is here](https://github.com/alexcrichton/futures-rs/pull/77)
