### ISSUE TITLE
Future type for Option

### ISSUE THREAD

**Issue by petehayes102** [alexcrichton/futures-rs#601]
Would it be possible to create a new `Future` type that is modelled on an `Option`, rather than a `Result`? I know this could be achieved using existing combinators, but it'd be really handy to have a type that is purpose made.

I'd be happy to have a go at a PR if people think it's a good idea.

**Comment by alexcrichton** [comment]
Do you mean something where `wait` returns `Option<T>` instead of `Result<T, E>`?

**Comment by petehayes102** [comment]
Yep. You could also implement similar combinators, e.g. `map_none()` etc.

**Comment by alexcrichton** [comment]
Ah ok, in that case it's definitely not easy to do today as you can't get away from the `type Error` in the future trait. In general working with `Future` is very much baked in with working with `Result` as well. Forgoing this is very far out on the horizon so I'm going to close this for now, but a local trait to add such combinators may work well!

**Comment by petehayes102** [comment]
No worries. Thanks for the heads up mate! :)
