### ISSUE TITLE
sink::Buffered accepts 1 more than capacity

### ISSUE THREAD

**Issue by casey** [alexcrichton/futures-rs#608]
In `start_send`, it looks like`item` will be buffered if `self.buf.len() == self.cap`:

```
fn start_send(&mut self, item: Self::SinkItem) -> StartSend<Self::SinkItem, Self::SinkError> {
    self.try_empty_buffer()?;
    if self.buf.len() > self.cap {
        return Ok(AsyncSink::NotReady(item));
    }
    self.buf.push_back(item);
    Ok(AsyncSink::Ready)
}
```

If this is the case, `self.buf` will contain `amt + 1` items.

Not sure what the best fix is. To avoid a re-allocation, we should allocate `self.buf` with capacity `amt + 1`. If we want to guarantee that `self.buf` never contains more than `amt` items, it seems like it will make the logic in start_send more complicated, since it will need to attempt to send `item` to avoid hanging.

**Comment by alexcrichton** [comment]
I think we could just tweak the logic to only hold `self.cap` elements in the local deque, right?

**Comment by casey** [comment]
The issue with that, which is minor, is that a buffer with 0 capacity will will block. `start_send` will return not ready, but the task will never be notified.

This can be fixed by attempting to send the item if the buffer is empty / the capacity is zero:

https://github.com/casey/futures-rs/commit/bf7fceaada2a57cfb9e289cd44ad318ba1fa1af3

**Comment by alexcrichton** [comment]
The implementation can be fixed though to just try to forward to the underlying sink on 0 capacity?

**Comment by casey** [comment]
Sounds good, opened #613
