### ISSUE TITLE
Can stream/sink be extended to become observable/observer?

### ISSUE THREAD

**Issue by 3n-mb** [alexcrichton/futures-rs#611]
#### Context
API for stream, with likes of `map`, `take`, `filter` all looks and smells like operators of observables. And if one wants to create library with observables, rust style, it seems that this may be a good start. Futures are here already. And futures (promises) are a special case of observables.

[Docs](https://tokio.rs/docs/getting-started/streams-and-sinks/#concurrency) do say something about concurrency, sort of hinting that current implementation of streams cannot be directly used as rust's observables pattern.

#### Why observables?
It has been noticed that casting program's logical processes with observables helps developer to articulate quite complex processes in a readable/digestible code.

Incoming data is one type of events. Another type of events are mere signals between/inside processes. Events are treated as a first order objects, while observables (streams, where events flow) are second order objects. Clean separation of a second order abstract layer allows it to be used for process-shaping code, i.e. operators like `map`, `take`, `debounce` etc.

Each chain of observables is a logical process, a sequence of particular actions, setup in a particular order. When a cold observable is subscribed to, it becomes an active process.
This is a very clean and useful abstraction.

#### Desired thing: observables, rust style
When writing processes in observables, one shouldn't explicitly use threads. Instead, operators should provide for parallel execution were needed.
Of cause, rust's types naturally protect against common errors with parallelism, hence, a strong believe that observable style library will fit right with rust.
*Side note: I prefer name stream to observable and name sink to observer*.

Case 1.
When an operation in a section of observables is heavy (or blocking a thread), we may want to have such section run in parallel, in some thread pool.

Case 2.
When there are few adjacent operators that are light, and non-blocking, non-futuring, we may want to run such section in exactly one thread. Potential switch of threads between tiny operations just adds an overhead, hence this case is needed in an efficiency-promising language :smile: 

Case 2a.
Sections from case 2 may also be run in parallel. Similarly to how parallelism is introduced in [mentioned docs](https://tokio.rs/docs/getting-started/streams-and-sinks/#concurrency) for streams.

Case 3.
In sections that run in one thread, we may want to have operations that return future, and that future is flattened. Say, in a chain `stream.op1().op2(). ...`, if `op5` is a `flatMap` and produces a future, that is not resolved yet, an executor may start processing events that are ready, like new event at `op1`.
Is this the case with current stream?

#### Questions:
 - How easy is it to make streams for case 1?
 - What do you think about having case 2, not only case 1? Bonus here is that current streams may already be implementing this, sort of.
 - How far current streams from case 3? Or, are streams mere analog of pipelines, like  ones used in jetty for processing incoming data? I.e. how far streams are from observables, at least is a case of one thread.

**Comment by alexcrichton** [comment]
Thanks for the report! I think I may not personally be too too familiar with observables, but is this something that could be a combinator on the stream/sink trait perhaps? Maybe like `inspect` on iterators?

**Comment by 3n-mb** [comment]
@alexcrichton 
- When you say combinator, I think you mean `and_then`, `map`, implemented for streams. Is this correct?
Indeed, rust's ability to add custom `foo` for a trait, is what folks in javascript call "lifting" function to make it an operator, accessible via dot (`x.foo(...)`). This is how a myriad of operators will be implemented, of cause.
- From [inspect doc](https://doc.rust-lang.org/std/iter/struct.Inspect.html): *An iterator that calls a function with a reference to each element before yielding it.* The word *yielding* stands out? Do we have generators in rust?

**Comment by 3n-mb** [comment]
@alexcrichton I am confused about scheduling and executors. Can you point me (in code) to the way Futures are scheduled and executed? And are streams producing task that are scheduled like Futures (point to code)?
Recalling that comment in docs about no-concurrency in current streams, if execution and scheduling in streams is like in future, there is generally no guarantee for streams concurrency, unless either somewhere ordering is added, or scheduling is a bit different from promises. Which is it? Can you point to code.
Thank you, in advance.

**Comment by 3n-mb** [comment]
@alexcrichton I found in tests, code for futures, which looks totally like things done with observables.
It is [from cpupool test](https://github.com/alexcrichton/futures-rs/blob/master/futures-cpupool/tests/smoke.rs#L20)
```rust
let res = a.join(b).map(|(a, b)| a + b).wait();
```
In rx-js it will be something like
```javascript
a.zip(b).map((a,b) => a+b).subscribe(res => ...);
```
When `a` and `b` are observables(streams) with one event in each, above js code does same as rust code. As for `zip`, it is [one of operators](http://reactivex.io/documentation/operators/zip.html).

Analogy is superb. More so, I constantly see *futures do nothing unless polled*, while cold observables don't emit, unless subscribed. (It better sounds, cold streams don't emit unless subscribed. Hot streams are emitting.)

**Comment by alexcrichton** [comment]
@3n-mb from what I'm understanding it sounds like streams are roughly equivalent? I'm not sure if there's limitations in one system or another?

**Comment by 3n-mb** [comment]
@alexcrichton I am not quite fluent in code base, and my concern was brought up by *streams are not concurrent* part of the section, while commonly used `flatMap` observable's operator is.
Rustifying, and not being 100% strict, signature for flatMap is
```rust
fn flatMap(self: Stream<X>, fn_closure: (x: X) -> Future<Y>) -> Stream<Y>
```
This runs `fn_closure` concurrently. Can stream have this? If not, what should change in scheduling inside `Stream` to accommodate concurrency.

**Comment by 3n-mb** [comment]
Once we get concurrency in `Stream`, or have `ConcurrentStream` adding operators (combinators) will be an easy part. Very easy part, indeed (modulus optimizations :smile: ).

**Comment by tailhook** [comment]
>  This runs fn_closure concurrently. Can stream have this? If not, what should change in scheduling inside Stream to accommodate concurrency.

See [buffered](https://docs.rs/futures/0.1.16/futures/stream/trait.Stream.html#method.buffered) and [buffered_unordered](https://docs.rs/futures/0.1.16/futures/stream/trait.Stream.html#method.buffer_unordered). They do exactly what you're saying. Making them parallel (i.e. running in different threads) rather than barely concurrent requires a bit of more work though.

**Comment by 3n-mb** [comment]
@tailhook this is cool :+1: All parts for Observables are here.

**Comment by 3n-mb** [comment]
I think we can add in [stream module docs](https://docs.rs/futures/0.1.16/futures/stream/index.html) that this is an analog of observables, used in other langs.
