### ISSUE TITLE
Question about error/completion contract with streams

### ISSUE THREAD

**Issue by 3n-mb** [alexcrichton/futures-rs#615]
Observables are commonly done to [fulfill this contract](http://reactivex.io/documentation/contract.html)
Do `Stream`'s adhere to it? And if not, it which point is it different?

1) Error or completion may happen only once. No more events expected, after one of these happens. Do `Stream`'s act this way?
2) If we have a chain `stream.op1(...).op2(...).op3(...)`, and let's assume there is a parallel execution at points 1 and 3, when error happens at 3. Execution in 1 may not be stopped, its fine. But, when execution at 1 is done, will result go into point 2, to start execution there, or, will the stream flow be stopped?

**Comment by 3n-mb** [comment]
It seems, from #206 that errors don't close stream.
The question is then, when v0.2 with proper behaviour is expected?

**Comment by alexcrichton** [comment]
Thanks for the report! I believe this does indeed fall under https://github.com/alexcrichton/futures-rs/issues/206 which is planned for the 0.2 release, so I'm going to close this.
