### ISSUE TITLE
Oneshot may panic if the receiver is closed

### ISSUE THREAD

**Issue by Diggsey** [alexcrichton/futures-rs#620]
The implementation of oneshot is racy, which results in a random chance of it panicking when the receiver is closed and the sender tries to send at the same time.

I wrote a test to demonstrate the issue: https://github.com/Diggsey/futures-rs/commit/aa70fbce690cd5b92bd7e8e59661a20061ecf142

The issue is with the assertion made in this comment: https://github.com/alexcrichton/futures-rs/blob/master/src/sync/oneshot.rs#L123 which is not true, because the receiver sets the complete flag also when it is closed.

A correct lock-free implementation is essentially impossible without either:
- Reserving space in the data structure for at least two values of type `T`
- Making `close()` consume `self` and return any "in transit" value directly, instead of having the caller poll the future.

**Comment by Diggsey** [comment]
I have implementations of oneshot which solve the problem for each possible variation which I can PR.

**Comment by alexcrichton** [comment]
Thanks for the report! PRs would be great!

It sounds like the solution is to just set a local boolean in `close` to prevent it from doing anything in `poll`?

**Comment by Diggsey** [comment]
@alexcrichton Unfortunately no: see https://docs.rs/futures/0.1.16/futures/sync/oneshot/struct.Receiver.html#impl

`poll` is *supposed* to be callable after a oneshot is closed, as that's the only way to ensure an item is not lost in the oneshot.

**Comment by Diggsey** [comment]
So there are basically four options:
1) Remove this behaviour entirely
2) Add space for an extra value of the element type
3) Make `close` return any in-transit value directly and consume self
4) Use a lock to protect the stored value

I think 3) is the best option, or 2) while backwards compatibility needs to be maintained. Being able to not lose the value is too important for 1) and 4) would mean oneshots are no longer lock-free.

**Comment by Diggsey** [comment]
Hm, actually with some tweaks it would be possible to store just an extra boolean if it keeps track of which side set "complete" first.

**Comment by alexcrichton** [comment]
Fixed in https://github.com/alexcrichton/futures-rs/pull/641
