### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/futures-rs#628]
The licensing of this repository states:

> `futures-rs` is primarily distributed under the terms of both the MIT license and
the Apache License (Version 2.0), with portions covered by various BSD-like
licenses.

* *which* portions are covered by "various BSD-like licenses"?
* What is a BSD-like license? Which license?
* How is software licensed under MIT **AND** Apache 2? This implies that it carries the super set of both licenses (not that the user gets to pick). What does the super set of both licenses mean?

**Comment by alexcrichton** [comment]
Done in https://github.com/alexcrichton/futures-rs/commit/2d95ac92c46eb1f287bffe21f164362661fd0c24
