### ISSUE TITLE
Promise has no mechanism to signal the consume end cancelled interest

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/futures-rs#63]
I have implemented an alternative implementation of `Promise` that provides a cancellation future, but it would be preferable to expose this functionality upstream.

https://github.com/tokio-rs/tokio/blob/master/src/util/future/val.rs#L143

**Comment by alexcrichton** [comment]
@carllerche do you have some example code using the cancellation half? I've got an idea for something along the lines of:

```rust
fn poll_cancel(&mut self) -> Poll<(), E> {
    // ..
}
```

Where you can't actually extract a future per-se but you can check to see if it's canceled and if it's not (e.g. returns `NotReady`) your future task would be "auto-scheduled" to get a notification when it is indeed canceled.

I'm not sure though if this would play well with implementations using this, so I'd just want to play around with a few possibilities.

**Comment by carllerche** [comment]
`poll_cancel` could work better in that it removes the need to track an extra future. I'm happy to go that route.

I don't have any code yet using it. Currently working on it as we speak though.

**Comment by alexcrichton** [comment]
Ok cool, I'll look into implementing soon
