### ISSUE TITLE
Is StaticRef supposed to be public?

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/futures-rs#637]
I see [`StaticRef`](https://github.com/alexcrichton/futures-rs/blob/master/src/task_impl/mod.rs#L657) isn't actually used anywhere. It seems like a useful thing to expose.

That said, I probably wouldn't expose it by making the type public..

Probably something like `NotifyHandle::from_static<T: Notify>(_: &'static T) -> Self`

**Comment by twmb** [comment]
Isn't `StaticRef` used in client libraries where a `&'static T` is used as a `NotifyHandle`?

**Comment by cramertj** [comment]
Yeah, it's used in [this public impl of `From`](https://github.com/alexcrichton/futures-rs/blob/master/src/task_impl/mod.rs#L684).

**Comment by carllerche** [comment]
Ag, I missed that. Oops.
