### ISSUE TITLE
An equivalent of `mergeAll` from Rx observables for streams?

### ISSUE THREAD

**Issue by nathansobo** [alexcrichton/futures-rs#640]
In Rx, there's a method on observables called [`mergeAll`](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-mergeAll) that transforms a stream of streams into a stream that yields results from any of the underlying streams as they are available. The `flatten` method seems close, but it imposes ordering such that results of a given child stream only become available when the streams before it are completed.

I'm looking to build a multiplexed request handler that transforms a stream of incoming requests to a stream of responses to all of those requests and writes them to a sink. The only way I have found so far is to spawn a new future for each request in a `for_each` callback that writes the stream of responses to an `unsync` channel, then read from the channel outside of the `for_each`. It feels like it could be more elegant. Am I missing something.

I'm new to Rust and tokio, so my apologies if this isn't the right form for a question like this. If that's the case, please let me know.

**Comment by carllerche** [comment]
It would definitely be interesting to write something like the `mergeAll` and it should be possible by building it on top of [`FuturesUnordered`](https://docs.rs/futures/0.1.17/futures/stream/struct.FuturesUnordered.html).

That said, I'm not entirely following how that would work for your case. It looks like you want to map a stream of values (requests) -> a stream of futures of a value (futures of the response).

I believe that is already possible with (`buffer_unordered`)[https://docs.rs/futures/0.1.17/futures/stream/trait.Stream.html#method.buffer_unordered]

**Comment by nathansobo** [comment]
> That said, I'm not entirely following how that would work for your case. It looks like you want to map a stream of values (requests) -> a stream of futures of a value (futures of the response).

Well, my responses are actually streams. The requests are spawning subprocesses and I want to stream back output from those subprocesses on an ongoing basis.

**Comment by carllerche** [comment]
You could implement something like "merge all" by writing a combinator that is composed of `FuturesUnordered`. For each stream, convert it into `Future<(T, Stream<T>)>` (future of (head, rest)) by calling `Stream::into_future`, then push that into the `FuturesUnordered` (using the `push` fn).

Then, for each value that is yielded out of the futures unordered (`(head, rest)`), push `rest.into_future()` back into the `FuturesUnordered` and return `head`.

That should be equivalent.

**Comment by nathansobo** [comment]
Thanks a lot for your time. I figured I'd need to write a new combinator to use it but it took a second to realize that. I'll close this out but report back with a code snippet if I am successful in case it helps others.
