### ISSUE TITLE
Weird compiler error about Trait objects

### ISSUE THREAD

**Issue by matt961** [alexcrichton/futures-rs#644]
```
type DownloadPage = Box<Future<Item=Body, Error=Error>>;

pub fn download_page(uri: Uri, handle: &Handle)
                     -> Result<DownloadPage, &str> {
    new_http_client(handle)
        .map(move |client| {
            Box::new(client.get(uri).and_then(move |res| {
                println!("{}\n", res.headers());
                println!("{}\n", res.status());
                futures::future::ok(res.body())
            }))
        })
}
```
The above doesn't work, while the following does:
```
type DownloadPage = Box<Future<Item=Body, Error=Error>>;

pub fn download_page(uri: Uri, handle: &Handle)
                     -> Result<DownloadPage, &'static str> {
    let client = new_http_client(handle)?;

    Ok(Box::new(client.get(uri).and_then(move |res| {
        println!("{}\n", res.headers());
        println!("{}\n", res.status());
        futures::future::ok(res.body())
    })))
}
```

At first I thought I just messed something up with `Result`'s combinators, but this error message leads me to believe otherwise...

![image](https://user-images.githubusercontent.com/11224476/32864469-2ce765aa-ca14-11e7-884e-0384c484a6fa.png)

Am I misunderstanding something about how Trait objects come to be? Or, is this error unintended? `AndThen` most definitely implements `Future`. Thanks!

**Comment by alexcrichton** [comment]
I think this is just a compiler bug? Nothing to do with this crate? 

I believe this is just a case where type inference isn't working far enough perhaps

**Comment by matt961** [comment]
Ah okay. "Abusing" combinators has been my thing lately since  `if let` was starting to clutter my code. Thanks Alex
