### ISSUE TITLE
CpuPool is lame after fork

### ISSUE THREAD

**Issue by illicitonion** [alexcrichton/futures-rs#649]
The following code hangs forever:
```rust
extern crate futures;
extern crate futures_cpupool;
extern crate libc;

use futures::future::Future;

fn main() {
    let pool = futures_cpupool::Builder::new().create();
    let pid: i32 = unsafe { libc::fork() };
    println!("Forked: {}", pid);
    let f: Box<Future<Item = String, Error = String>> = Box::new(pool.spawn_fn(move || {
        println!("Running on pool in PID {}", pid);
        Ok(format!("PID {} done", pid))
    }));
    println!("Joined on future: {}", f.wait().unwrap());

    if pid != 0 { 
        let mut status = 0;
        unsafe {
            libc::waitpid(pid, &mut status, 0); 
        }   
    }   
}
```

The CpuPool in the forked child appears to never schedule work. (If I create the pool after the fork, it runs fine).

Is there any way for me to detect that a CpuPool is unable to schedule work? Or for a CpuPool to re-initialise itself after a fork? Or a wrapper type I can use which will None itself out after a fork, or re-initialise the CpuPool after a fork? Or really any way of handling the situation?

Right now, I have code which, when I explicitly fork manually, re-initialises a RwLock<Option<CpuPool>>, but requiring me to proactively do this when I notice that I've forked seems error-prone.

**Comment by alexcrichton** [comment]
I think this is just how multithreaded programs work with forking? I don't think there's really anything we can do about this...

**Comment by carllerche** [comment]
Yes, if a program has threads, you cannot fork unless you immediately call exec. This is just a limitation with how fork works. The issue is that, when you add threading to the mix, the fork might happen while another thread has locked a global mutex. In the forked process, that mutex will never be unlocked, leading to a deadlock.
