### ISSUE TITLE
Reference counting in CpuPool and Inner

### ISSUE THREAD

**Issue by pmarcelll** [alexcrichton/futures-rs#65]
What's the reasoning behind using a custom reference counting in Inner in futures-cpupool? The inner is already wrapped in an Arc and sending the close messages on drop can be implemented for Inner itself instead of CpuPool.

**Comment by alexcrichton** [comment]
Unfortunately the `Inner` structure is also referenced by all of the worker threads, so a `Drop` implementation wouldn't work b/c it's still alive.

It is a bit ad-hoc, though, here, and I'd love to fix!

**Comment by pmarcelll** [comment]
I found a bug, the return value of the fetch_sub [here](https://github.com/alexcrichton/futures-rs/blob/bce2ad2655db67728a1f7334919d689f334e7d48/futures-cpupool/src/lib.rs#L180) will never be 0.

**Comment by alexcrichton** [comment]
Ah yeah when I was reviewing this I ended up locating https://github.com/alexcrichton/futures-rs/commit/85920702f31599287bcb38e82a36699d4f854825, is that the bug you were thinking of?

**Comment by pmarcelll** [comment]
No, it still leaks in my opinion.

Here is the code:
```rust

    // in new()
    let pool = CpuPool {
        inner: Arc::new(Inner {
            queue: MsQueue::new(),
            cnt: AtomicUsize::new(1), // <- starts with 1
            size: size
        }),
    };

impl Drop for CpuPool {
    fn drop(&mut self) {
        if self.inner.cnt.fetch_sub(1, Ordering::Relaxed) != 0 {
            // when only one instance is left, and it's being destroyed, fetch_sub returns 1, cnt becomes 0,
            // but this always returns here, because fetch_sub retruned 1, and not 0
        }
        // this never gets called
        for _ in 0..self.inner.size {
            self.inner.queue.push(Message::Close);
        }
    }
}
```

**Comment by alexcrichton** [comment]
Ah right whoops, returns the previous not the current count.
