### ISSUE TITLE
There is no way to combine the Tokio reactor with CurrentThread

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/futures-rs#652]
As the title says, I don't believe that the current RFC actually describes a way to combine the current thread executor and the tokio reactor on a single thread.

I believe that the original spike used a `FuturesUnordered`, but that doesn't actually integrate with any of the current thread executor APIs.

**Comment by aturon** [comment]
Just to be clear, you're shooting for the goal of being able to call `CurrentThread::spawn` within futures running on a combined reactor/executor?

IOW, it's not sufficient to mimic today's Tokio, where the combined object is itself an executor, distinct from `CurrentThread` as an executor?

**Comment by carllerche** [comment]
Yes, you would essentially need to build your own equivalent to the `CurrentThread` executor that is able to integrate with the Tokio reactor.

**Comment by aturon** [comment]
Can we solve this by providing an additional API like `block_with_init` that provides custom park/unpark functionality?

**Comment by carllerche** [comment]
An additional API to what? I'm not following the proposal.

In order to integrate the two, the reactor needs to be passed to `CurrentThread` and used as the blocking mechanism. Futures that get notified on `CurrentThread` then need to unblock the reactor.

**Comment by aturon** [comment]
Right. I'm proposing we add `block_with_notify` to `CurrentThread` that allows you to pass in functions for blocking and unblocking.

**Comment by carllerche** [comment]
As you already know, I have a proposal [here](https://github.com/tokio-rs/tokio-rfcs/pull/3#issuecomment-333003271).

You could probably replace the wakup trait with a `NotifyHandle` instance at the cost of a dyn dispatch. Executors already need to inject a dyn dispatch for their notify handle, so my original thought w/ a `Wakeup` trait is that we would want to avoid having two dynamic dispatches.

It might be possible to use `T: Notify + Clone` instead of `Wakeup`, but I am not 100% sure about that. The `Notify` trait is  designed for a different use case (which is why it doesn't require `Clone` and has `clone_id` and `drop_id` fns).

**Comment by aturon** [comment]
@carllerche Ah, I'd actually forgotten that that proposal keyed on the current thread executor (my cache is pretty thrashed these days...)

I quite liked that proposal, and it seems like an ideal fix for this issue. But I wonder if we should just punt on this issue for the initial publication, so that we have more time to play with it?

**Comment by aturon** [comment]
Er no, we can't punt, since we will need to offer `tokio-core` and should have it compatible with the `CurrentThread` executor.

@carllerche, how would you feel about making a PR based on your earlier proposal?

**Comment by carllerche** [comment]
@aturon I can work on that.

**Comment by carllerche** [comment]
This is resolved by #665
