### ISSUE TITLE
Extracting a value from a finished Future

### ISSUE THREAD

**Issue by Relrin** [alexcrichton/futures-rs#672]
Hello!

Currently I'm trying to connect the existing parts of my code with redis-async crate (which is works with Tokio), but stuck with getting a value from a finished Future. So, in actual moment I have the following piece of code:
```rust
fn get_user_id(&self, raw_token: String, handle: &Handle) -> Result<String> {
    let redis_socket_address = self.redis_address.parse().unwrap();
    let redis_connection = paired_connect(&redis_socket_address, handle);

    let get_user_id_future = redis_connection.and_then(move |connection| {
        // returns Ok("some user ID") when everything is good
        connection.send::<String>(resp_array!["GET", raw_token])
    });

    let mut processing_result = Ok(String::from(""));
    handle.spawn(get_user_id_future.then(move |response| {
        processing_result = match response {
            Ok(user_id) => Ok(String::from(user_id)),
            Err(_) => {
                let message = String::from("Token is expired or doesn't exist.");
                Err(PathfinderError::AuthenticationError(message))
            }
        };
        Ok(()) // Yes, here we can't return the value. Here should be `Ok(())` in the end, I guess
    }));

    processing_result
}
```
Could the already finished `Future` return to me a final value somehow (without channels or some hacks)? Because I didn't found a suitable thing or a method, that let me to do this way.

**Comment by alexcrichton** [comment]
Thanks for the report!

This is sort of a "how do you program with futures?" question in the sense that one of the main purposes of async/futures programming is you *don't* extract a finished value from a future. For example this function may wish to return a future of a string rather than the string itself.

Alternatively if you do want to block the calling thread then that's when you need to start using methods like `Core::run` in tokio-core

**Comment by Relrin** [comment]
I'm using future-rs crate for implementing WebSocket-over-Kafka reverse proxy, so that endusers will not be guessed that working with message bus (in my case is Kafka). WebSocket connection handling/processing is implemented with the [tokio-tungstenite](https://github.com/snapview/tokio-tungstenite) crate.

If shortly describe the cases how it works, then it will be like the following algorithm:
1) Client is getting a token for reverse proxy outside (for example, from an Auth/Auth microservice, which is saving tokens in Redis).
2) Reverse proxy after handshake stage is extracting the token from headers and check it (and the piece of code is taken from a middleware that doing it). If we're getting error, then closing a connection and don't doing something else.
3) Client sending requests, so that they will be transformed into messages in the appropriate format for a message bus. Any further work will have done by the separate microservice, which is also will return a response for a caller.

In my current codebase the `Core::run` method is already using [here](https://github.com/OpenMatchmaking/pathfinder/blob/feature-token-check/pathfinder/src/proxy.rs#L119). Also, I don't think that is a good idea to create a separate core instances for handling Redis/Kafka requests instead of sharing the one existing instance, because of potential performance hit?

**Comment by alexcrichton** [comment]
Yes you probably don't want to create multiple instances of a `Core` but if you do want this to be a synchronous interface (not an asynchronous one) then you'll want to arrange the thread's `Core` to be available to this method, which may require putting it into TLS or similar

**Comment by Relrin** [comment]
As far as I understood, we have a few possible ways how to deal with the futures inside of another future:
1) Synchronous way
- Use synchronous crates for request to your needs (for example, "redis-rs" for Redis and "kafkra" for Kafka). 
- Pass an existing `Core` (like an argument in function) and invoke the prepared future. Does it lead to block not also a certain future, but a main core thread in general (therefore, more performance hits)?
2)  Asynchronous way
- Create a separate `Core` instance per each inner stuff, which is going to return a value instead of future of something. Just invoke the `core::run` where it necessary and receive a result.

Correct? Perhaps synchronous way it easier to implement and understand, in comparison with the asynchronous approach, but what is better?

**Comment by alexcrichton** [comment]
Er sorry I think I may just be accidentally confusing things. I'm not really sure what the goal is here (to be synchronous or asynchronous) or what libraries are in use (whether they're synchronous or synchronous) or what the overal architecture of the application/library is supposed to be. I've mostly been giving little bits of advice hoping you'll know where they go :(

**Comment by Relrin** [comment]
Well, I'm just trying to figure out how to deal with the case, when you have a different parts (server, redis, kafka and so on) of an application which is going to work in async way. Honestly saying, I don't know what to do further, first of all because of lack of an experience with futures in general. And this my first experience with it. :)
For this particular case I'd like to go by more simple way, so that it will work without any issues in the future. Potentially some parts (like Redis/Kafka) could be synchronous, but what to choose better?

**Comment by alexcrichton** [comment]
Oh sure yeah no worries! It's just difficult to answer questions on my end when the application architecture is so fluid. You know far more details about what you're doing than I so if it's not listed here I'm just relying on guesswork to figure out what's going on! 

In terms of overall application architecture that's probably a discussion best left to IRC/gitter rather than an issue tracker here. If you don't know that you'll need asynchronous interfaces out of the gate I'd recommend synchronous ones as they're typically easier to work with the first time around.

**Comment by Relrin** [comment]
> If you don't know that you'll need asynchronous interfaces out of the gate I'd recommend synchronous ones as they're typically easier to work with the first time around.
As far as I understood, in this case if external dependencies (or crates) onto synchronous and change appropriate calls (like polling the Redis instance) the it will work as expected, right? 
However, this will not lead to the fact that future will be blocked when synchronous code will be invoked there (or am I perhaps mistaken?).
P.S. Just want to make ensure that I'll do it in the right way.
