### ISSUE TITLE
Implement stream::iter_ok_repeat()

### ISSUE THREAD

**Issue by mikecaines** [alexcrichton/futures-rs#674]
This would combine the functionality of `iter_ok()` and `repeat()`, enabling you to for example, iterate over a `Vec` indefinitely.

Example implementation by Arnavion:
https://play.rust-lang.org/?gist=e7d884f577e27696f140502d6d337860&version=undefined

**Comment by alexcrichton** [comment]
Thanks for the report! Do you think this'd get wide enough use to justify going into the `futures` crate itself? In general there's an endless number of combinators we *could* add so we have to draw the line somewhere. It's not really clear where the line is but this personally to me at least feels somewhat esoteric enough to leave external?

**Comment by mikecaines** [comment]
I've realized since that the same functionality can be achieved via `::futures::stream::iter_ok(my_vec.into_iter().cycle())`, so I think this can just be closed.

**Comment by alexcrichton** [comment]
Ok!
