### ISSUE TITLE
Unsatisfied bounds in case of earlier _inner_ type mismatch error

### ISSUE THREAD

**Issue by mqudsi** [alexcrichton/futures-rs#676]
In case of a type mismatch when chaining/mapping between a `FutureResult<x,y>` and `FutureResult<x,z>`, the compiler also emits (invalid) errors about unsatisfied bounds for any subsequent future operations, even though the type mismatch is only the inner type within the `FutureResult<_,_>` (i.e. in all cases the result of the operation is a future).

Here's an example ([git link](url)):

```rust
    let f = future::result::<(),()>(Ok(()))
        .map_err(|_| "&'static str error")
        .and_then(|_|
             future::result(Ok(())
                .map_err(|()| "String error".to_owned())
            )
        )
        .and_then(|_| future::result::<(), String>(Err("another &'static str error".to_owned())))
```

generating the following errors, the second of which is the point of this issue:

```rust
   Compiling futuretest v0.1.0 (file:///mnt/c/Users/Mahmoud/git/futuretest)
error[E0271]: type mismatch resolving `<futures::FutureResult<(), std::string::String> as futures::IntoFuture>::Error == &str`
  --> src/main.rs:12:10
   |
12 |         .and_then(|_|
   |          ^^^^^^^^ expected struct `std::string::String`, found &str
   |
   = note: expected type `std::string::String`
              found type `&str`

error[E0599]: no method named `and_then` found for type `futures::AndThen<futures::MapErr<futures::FutureResult<(), ()>, [closure@src/main.rs:11:18: 11:42]>, futures::FutureResult<(), std::string::String>, [closure@src/main.rs:12:19: 15:14]>` in the current scope
  --> src/main.rs:17:10
   |
17 |         .and_then(|_| future::result::<(), String>(Err("another &'static str error".to_owned())))
   |          ^^^^^^^^
   |
   = note: the method `and_then` exists but the following trait bounds were not satisfied:
           `futures::AndThen<futures::MapErr<futures::FutureResult<(), ()>, [closure@src/main.rs:11:18: 11:42]>, futures::FutureResult<(), std::string::String>, [closure@src/main.rs:12:19: 15:14]> : futures::Future`
           `&mut futures::AndThen<futures::MapErr<futures::FutureResult<(), ()>, [closure@src/main.rs:11:18: 11:42]>, futures::FutureResult<(), std::string::String>, [closure@src/main.rs:12:19: 15:14]> : futures::Future`

error: aborting due to 2 previous errors

error: Could not compile `futuretest`.

To learn more, run the command again with --verbose.
```

Resolving the type mismatch fixes the first error and makes the second error go away entirely.

**Comment by alexcrichton** [comment]
Thanks for the report! I'm not really sure what's actionable for this though? What would be the fix that you'd expect from this?

**Comment by mqudsi** [comment]
I'm not sure either, to be honest.

Is there any sort of hint that could be provided to the compiler about the trait of the return type such that it could be aware of the (future) presence of these methods?

**Comment by alexcrichton** [comment]
Ah ok in that case I don't think there's anything we can do so I'm going to close. Unfortunately libraries can't hint to the compiler in terms of default types for type inference reasons :(

**Comment by mqudsi** [comment]
Perhaps I should file this in the compiler github?

**Comment by alexcrichton** [comment]
If you'd like!

**Comment by mqudsi** [comment]
ref https://github.com/rust-lang/rust/issues/46646
