### ISSUE TITLE
Deprecated items can be used with no warning

### ISSUE THREAD

**Issue by sgrif** [alexcrichton/futures-rs#695]
There are a bunch of deprecated items in this crate, however there is no indication given to the user that they are deprecated. The `#[deprecated]` attribute does nothing on `pub use` items (perhaps this should be fixed in the language). This code compiles with no warnings, even though `futures::done` is deprecated.

```
extern crate futures;
use futures::done;

pub fn main() {
    let _ = done::<_, ()>(Ok(1));
}
```

**Comment by alexcrichton** [comment]
Indeed! I think as you've found though this is due to some rustc bugs. We could go further and rewrite these to functions where we can, but overall it's not entirely important as most of these are ancient now and hidden from the docs anyway.

**Comment by sgrif** [comment]
Up to you, just wanted to make sure you knew. Feel free to close if you don't think there's any action needed. :)

**Comment by alexcrichton** [comment]
Ok, in that case I'm gonna close this, but if it ends up being a problem we can reopen.
