### ISSUE TITLE
stream::Inspect should have a forwarding impl of Sink

### ISSUE THREAD

**Issue by zargony** [alexcrichton/futures-rs#700]
I just noticed that `stream::Inspect` doesn't contain a forwarding impl for `Sink`. Therefore, you lose the sink direction of a transport after `inspect`ing it. Is this by intention?

It would also be nice to be able to inspect errors, e.g. with `inspect_err`. Maybe `inspect`'s closure should get a result instead of an item, since if you're inspecting the stream, you most probably want to be aware of items or errors (at least in my case I noticed this a several times). However, passing a result would be a breaking change.

Inspecting the sink flow could be interesting as well, maybe with `sink_inspect` and `sink_inspect_err`

Let me know what you think and I'll prepare a PR

**Comment by alexcrichton** [comment]
Nah seems fine to add a forwarding impl for sinks! For inspecting errors though we'd probably want a separate combinator rather than changing the existing one.

**Comment by breeswish** [comment]
Expect to seeing support for `inspect_result` (i.e. inspect for both success and failures), useful for things like collecting metrics which is invoked no matter success or failure && does not change results.
