### ISSUE TITLE
Release futures 0.1.18?

### ISSUE THREAD

**Issue by stbuehler** [alexcrichton/futures-rs#715]
Hi, I think #669 deserves a new release :)

Also I think it would be helpful to add two labels:
- `feature` (or `wishlist`): stuff that might deserve to be added in crates in `futures-rs`
- `ideas`: interesting ideas that should be implemented in separate crates first

There are many unlabeled issues in the tracker, and it is not clear whether the project is in bad shape or just has many wishlist items.

Did you consider using the milestones feature for smaller release steps?

**Comment by alexcrichton** [comment]
Sure thing, released!

Also sounds like a good tagging system to me, I'll add some tags.
