### ISSUE TITLE
Propose to change `CpuPool::new` to accept `usize` instead of `u32`

### ISSUE THREAD

**Issue by zummenix** [alexcrichton/futures-rs#88]
Currently `CpuPool::new` accepts `u32` but `num_cpus::get` returns `usize`.

**Comment by alexcrichton** [comment]
Right now there's a `CpuPool::new_num_cpus` function for this, and otherwise I feel like `u32` here is more appropriate than `usize` because the variable doesn't need to be proportional to memory?

**Comment by zummenix** [comment]
I use `num_cpus::get` for `CpuPool::new` and for `Stream::buffered`, and I want to make sure that they use the number from the same function. 
In general I feel like using `usize/isize` is more suitable for public api because it allows use without cast. We still can use `u32` internally.

**Comment by alexcrichton** [comment]
Tweaked in https://github.com/alexcrichton/futures-rs/commit/69c30efcf765089aed6de0e98e04f14da1a491d1
