### ISSUE TITLE
Not clear how to make composition of futures with `CpuPool::execute`

### ISSUE THREAD

**Issue by zummenix** [alexcrichton/futures-rs#89]
I use `CpuPool` to perform parallel computations in streams, here is my snippet of code:
```rust
let entires: Vec<DirEntry> = ...
let cpu_pool = CpuPool::new(num_cpus::get() as u32);
let stream = futures::stream::iter(entries.into_iter().map(|entry| Ok(entry)))
    .map(|entry| {
        cpu_pool.execute(move || {
            // - open file using `File::open` - returns `Result`
            // - read file using `futures_io::read_to_end` - returns `ReadToEnd` future
            // - parse content of a file using `ReadToEnd::and_then` (this is a heavy task)
        })
    })
    .buffered(num_cpus::get() * 2)
    .filter(...)
    .collect();
```

**Comment by jeandudey** [comment]
Using `File::open` is more appropriate because the `execute` returns a future to **work** that's running on the thread pool, and you can use `try!` if an error happens when using `File::open` or methods of `Read`, `Write`.

**Comment by alexcrichton** [comment]
Thanks for the report @zummenix!

The `CpuPool` type is intended for blocking and/or intensive computations, so you probably won't want to execute more asynchronous/future-based work on it with the closures you're submitting. For that reason you'll probably not want to call `read_to_end` nor `and_then` in the closure passed to `cpu_pool.execute`, but rather you'll just do the normal blocking I/O the standard library provides with standard synchronous code.

I believe that'll give you the parallelization you want, does that make sense?

**Comment by zummenix** [comment]
I can move `File::open` and `read_to_end` calls outside of execution block but I still need to run computation heavy tasks and handle `Result`'s errors somehow. Current interface forces me to `unwrap` things (partially because I'm lazy, partially because I don't care for now). 
In my opinion, better would be for `CpuPool::execute` to accept a `Future` or `IntoFuture`, but I don't know how effective/easy to implement it would be. Something like this:
```rust
let future = File::open(path).and_then(|mut file| {
    let mut buf = Vec::new();
    try!(file.read_to_end(&mut buf));
    Ok(buf)
}).into_future().and_then(|buf| {
    Ok(try!(parse(buf))
});
cpu_pool.execute(future)
```

**Comment by alexcrichton** [comment]
Oh sorry, to clarify, the purpose of `CpuPool::execute` is not to run a future but rather run a computation on the thread pool itself. Futures are intended to model asynchronous computations or otherwise future events happening, but here we just need to do some synchronous work (reading a file) I believe, right?

As an example, I believe this may suffice for you? Or is this not what you're thinking?

```rust
extern crate futures;
extern crate futures_cpupool;

use std::io::{self, Read};
use std::fs::File;
use std::panic;
use std::path::Path;

use futures::{BoxFuture, Future};
use futures_cpupool::CpuPool;

struct Parsed;

fn parse(pool: &CpuPool, path: &Path) -> BoxFuture<Parsed, io::Error> {
    let path = path.to_path_buf();
    let res = pool.execute(|| {
        let mut f = try!(File::open(path));
        let mut contents = Vec::new();
        try!(f.read_to_end(&mut contents));
        try_parse(&contents)
    });
    res.map_err(|e| panic::resume_unwind(e))
       .and_then(|e| e)
       .boxed()
}

fn try_parse(data: &[u8]) -> io::Result<Parsed> {
    panic!()
}
```

**Comment by zummenix** [comment]
@alexcrichton Thanks for clarification and example. I guess, you're right.
