### ISSUE TITLE
Taking a CpuPool

### ISSUE THREAD

**Issue by bluetech** [alexcrichton/futures-rs#91]
Suppose a library wants to do some work on a thread pool and return a future for the result. For concreteness, it might be:

- Wrapping a blocking IO API (in this case #threads > #cpus makes sense).
- Doing CPU intensive work (in this case #threads > #cpus does not make sense).

It does not sound like a good idea for each such library to create its own thread pool (`CpuPool`). Hence, the library should take the thread pool by dependency injection. This is good for sharing a thread pool among multiple libraries, testing, leaving control in the hands of the library user, etc.

My question is: what type should the library take for the thread pool? Taking a `CpuPool` is an option but seems overly restrictive. Does it make sense to have a trait for that, and the library can then take the trait instead of a concrete struct?

For example, in Java the standard method for this is the ["executor framework"](https://docs.oracle.com/javase/tutorial/essential/concurrency/executors.html) - particularly the interfaces [`Executor`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Executor.html), [`ExecutorService`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ExecutorService.html) etc. This was also stolen by [python](https://docs.python.org/3/library/concurrent.futures.html) and [ruby-concurrency](http://ruby-concurrency.github.io/concurrent-ruby/file.thread_pools.html) and maybe others.

**Comment by camlorn** [comment]
Maybe an implicit threadpool stored in TLS, then primitives that access it?

Passing a threadpool around would get cumbersome if you had to funnel it through all the futures.  You could store it with any number of things, but a simple "go do this closure over there" seems useful to me.  Are there many cases in which you would want more threads than CPUs?  Because if not, the thread pool could also implicitly construct itself.

**Comment by alexcrichton** [comment]
There's a little bit of this being fleshed out in https://github.com/alexcrichton/futures-rs/pull/95, but I think in general this is going to require some form of threading around a `CpuPool` to spawn work on if you want to spawn work onto a thread pool.

**Comment by bluetech** [comment]
OK, if you don't think there's a use-case for a trait, I will just have the user pass in a `CpuPool` in my library for now. I will save you a lecture about the dependency inversion principle :)

**Comment by alexcrichton** [comment]
@bluetech oh I'm not saying that there's no use for this, I just wanted to give an update to the current state of affairs. We may end up needing a more official trait after all, but it may also be best to flesh out a bit first and see if it comes up.
