### ISSUE TITLE
unbounded channel with non-blocking non-future sender and Stream receiver

### ISSUE THREAD

**Issue by stepancheg** [alexcrichton/futures-rs#98]
I need to send messages to the event loop from other threads. Event loop works like this (in pseudocode):

```
loop {
    let item = channel.receive();
    write(socket, serialize(item));
}
```

futures-rs provides only synchronous channel, which it not suitable for this case: because sender should not block indefinitely if socket is not available for writing.

Seems like futures-rs could provide another building block: channel with unbounded size and non-blocking sender (as in `std::sync::mpsc::channel`) and with `Stream` interface to the receiver.

**Comment by stepancheg** [comment]
OK, I've found it: it is `loop.handle().channel()`. It is not clear is it a `channel` to be used only within even loop, or sender could live outside. Going to read sources.

**Comment by alexcrichton** [comment]
Ah yes, indeed! And also yes, a channel from the event loop will rely on the event loop running somewhere.
